import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const partsDir = path.join(__dirname, "parts");
const outputFile = path.join(__dirname, "..", "spec.able");

async function main() {
  const entries = await fs.readdir(partsDir);
  const partFiles = entries
    .filter(name => name.endsWith(".able.part"))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

  if (partFiles.length === 0) {
    throw new Error(`No part files found in ${partsDir}`);
  }

  const contents = await Promise.all(
    partFiles.map(file => fs.readFile(path.join(partsDir, file), "utf8")),
  );

  const banner = [
    "## This file is generated by stdlib/src/spec/build.mjs",
    "## Do not edit directly; update the files under stdlib/src/spec/parts and rerun the builder.",
    "",
  ].join("\n");

  const output = banner + contents.join("");
  const normalized = output.replace(/\n\n+/g, "\n");
  await fs.writeFile(
    outputFile,
    normalized.endsWith("\n") ? normalized : `${normalized}\n`,
    "utf8",
  );
  console.log(`Wrote ${outputFile} from ${partFiles.length} part(s).`);
}

main().catch(err => {
  console.error(err);
  process.exitCode = 1;
});
