// Code generated by internal/semanticabi/cmd/manifestgen; DO NOT EDIT.

package semanticabi

const (
	TagKindString                  uint32 = 1
	TagKindBool                    uint32 = 2
	TagKindChar                    uint32 = 3
	TagKindNil                     uint32 = 4
	TagKindVoid                    uint32 = 5
	TagKindInteger                 uint32 = 6
	TagKindFloat                   uint32 = 7
	TagKindArray                   uint32 = 8
	TagKindHashMap                 uint32 = 9
	TagKindHasher                  uint32 = 10
	TagKindFunction                uint32 = 11
	TagKindNativeFunction          uint32 = 12
	TagKindFunctionOverload        uint32 = 13
	TagKindStructDefinition        uint32 = 14
	TagKindTypeRef                 uint32 = 15
	TagKindStructInstance          uint32 = 16
	TagKindInterfaceDefinition     uint32 = 17
	TagKindInterfaceValue          uint32 = 18
	TagKindUnionDefinition         uint32 = 19
	TagKindPackage                 uint32 = 20
	TagKindDynPackage              uint32 = 21
	TagKindDynRef                  uint32 = 22
	TagKindError                   uint32 = 23
	TagKindHostHandle              uint32 = 24
	TagKindBoundMethod             uint32 = 25
	TagKindNativeBoundMethod       uint32 = 26
	TagKindImplementationNamespace uint32 = 27
	TagKindFuture                  uint32 = 28
	TagKindIterator                uint32 = 29
	TagKindIteratorEnd             uint32 = 30
	TagKindPartialFunction         uint32 = 31
)

const (
	OpDeclareFunction  uint16 = 1
	OpParameter        uint16 = 2
	OpBlock            uint16 = 3
	OpConstant         uint16 = 4
	OpLoadName         uint16 = 5
	OpTypeRef          uint16 = 6
	OpAssign           uint16 = 7
	OpUnary            uint16 = 8
	OpBinary           uint16 = 9
	OpCast             uint16 = 10
	OpCall             uint16 = 11
	OpMember           uint16 = 12
	OpIf               uint16 = 13
	OpLoop             uint16 = 14
	OpBreak            uint16 = 15
	OpReturn           uint16 = 16
	OpMatch            uint16 = 17
	OpMatchClause      uint16 = 18
	OpPattern          uint16 = 19
	OpRaise            uint16 = 20
	OpArray            uint16 = 21
	OpInterpolate      uint16 = 22
	OpHostEffect       uint16 = 23
	OpLoadConst        uint16 = 24
	OpLoadGlobal       uint16 = 25
	OpMoveValue        uint16 = 26
	OpUnaryValue       uint16 = 27
	OpBinaryValue      uint16 = 28
	OpCastValue        uint16 = 29
	OpGetMemberValue   uint16 = 30
	OpInvoke           uint16 = 31
	OpTypeTest         uint16 = 32
	OpJump             uint16 = 33
	OpBranch           uint16 = 34
	OpReturnValue      uint16 = 35
	OpRaiseValue       uint16 = 36
	OpMatchFail        uint16 = 37
	OpHostEffectResume uint16 = 38
)

var ManifestIdentity = [32]byte{0x79, 0xe6, 0x0c, 0x72, 0x51, 0x76, 0xe3, 0x14, 0xb2, 0xd0, 0x84, 0x0f, 0xc9, 0x9b, 0x66, 0x75, 0x31, 0xf6, 0xf5, 0x86, 0x6c, 0x52, 0x85, 0xde, 0x69, 0x5e, 0x96, 0xb7, 0x14, 0x4b, 0x9c, 0x7e}

var KindManifest = [...]KindDescriptor{
	{Name: "KindString", RuntimeOrdinal: 0, Tag: TagKindString, Class: KindSharedHeap},
	{Name: "KindBool", RuntimeOrdinal: 1, Tag: TagKindBool, Class: KindImmediate},
	{Name: "KindChar", RuntimeOrdinal: 2, Tag: TagKindChar, Class: KindImmediate},
	{Name: "KindNil", RuntimeOrdinal: 3, Tag: TagKindNil, Class: KindImmediate},
	{Name: "KindVoid", RuntimeOrdinal: 4, Tag: TagKindVoid, Class: KindImmediate},
	{Name: "KindInteger", RuntimeOrdinal: 5, Tag: TagKindInteger, Class: KindImmediate},
	{Name: "KindFloat", RuntimeOrdinal: 6, Tag: TagKindFloat, Class: KindImmediate},
	{Name: "KindArray", RuntimeOrdinal: 7, Tag: TagKindArray, Class: KindSharedHeap},
	{Name: "KindHashMap", RuntimeOrdinal: 8, Tag: TagKindHashMap, Class: KindSharedHeap},
	{Name: "KindHasher", RuntimeOrdinal: 9, Tag: TagKindHasher, Class: KindSharedHeap},
	{Name: "KindFunction", RuntimeOrdinal: 10, Tag: TagKindFunction, Class: KindSharedHeap},
	{Name: "KindNativeFunction", RuntimeOrdinal: 11, Tag: TagKindNativeFunction, Class: KindHostRegistry},
	{Name: "KindFunctionOverload", RuntimeOrdinal: 12, Tag: TagKindFunctionOverload, Class: KindSharedHeap},
	{Name: "KindStructDefinition", RuntimeOrdinal: 13, Tag: TagKindStructDefinition, Class: KindSharedHeap},
	{Name: "KindTypeRef", RuntimeOrdinal: 14, Tag: TagKindTypeRef, Class: KindSharedHeap},
	{Name: "KindStructInstance", RuntimeOrdinal: 15, Tag: TagKindStructInstance, Class: KindSharedHeap},
	{Name: "KindInterfaceDefinition", RuntimeOrdinal: 16, Tag: TagKindInterfaceDefinition, Class: KindSharedHeap},
	{Name: "KindInterfaceValue", RuntimeOrdinal: 17, Tag: TagKindInterfaceValue, Class: KindSharedHeap},
	{Name: "KindUnionDefinition", RuntimeOrdinal: 18, Tag: TagKindUnionDefinition, Class: KindSharedHeap},
	{Name: "KindPackage", RuntimeOrdinal: 19, Tag: TagKindPackage, Class: KindSharedHeap},
	{Name: "KindDynPackage", RuntimeOrdinal: 20, Tag: TagKindDynPackage, Class: KindSharedHeap},
	{Name: "KindDynRef", RuntimeOrdinal: 21, Tag: TagKindDynRef, Class: KindSharedHeap},
	{Name: "KindError", RuntimeOrdinal: 22, Tag: TagKindError, Class: KindSharedHeap},
	{Name: "KindHostHandle", RuntimeOrdinal: 23, Tag: TagKindHostHandle, Class: KindHostRegistry},
	{Name: "KindBoundMethod", RuntimeOrdinal: 24, Tag: TagKindBoundMethod, Class: KindSharedHeap},
	{Name: "KindNativeBoundMethod", RuntimeOrdinal: 25, Tag: TagKindNativeBoundMethod, Class: KindHostRegistry},
	{Name: "KindImplementationNamespace", RuntimeOrdinal: 26, Tag: TagKindImplementationNamespace, Class: KindSharedHeap},
	{Name: "KindFuture", RuntimeOrdinal: 27, Tag: TagKindFuture, Class: KindHostRegistry},
	{Name: "KindIterator", RuntimeOrdinal: 28, Tag: TagKindIterator, Class: KindSharedHeap},
	{Name: "KindIteratorEnd", RuntimeOrdinal: 29, Tag: TagKindIteratorEnd, Class: KindImmediate},
	{Name: "KindPartialFunction", RuntimeOrdinal: 30, Tag: TagKindPartialFunction, Class: KindSharedHeap},
}

var OpManifest = [...]OpDescriptor{
	{Name: "DeclareFunction", Opcode: OpDeclareFunction, Operands: []OperandKind{OperandSymbol, OperandImmediate}},
	{Name: "Parameter", Opcode: OpParameter, Operands: []OperandKind{OperandSymbol}},
	{Name: "Block", Opcode: OpBlock},
	{Name: "Constant", Opcode: OpConstant, Operands: []OperandKind{OperandConstant}},
	{Name: "LoadName", Opcode: OpLoadName, Operands: []OperandKind{OperandSymbol}},
	{Name: "TypeRef", Opcode: OpTypeRef, Operands: []OperandKind{OperandType}},
	{Name: "Assign", Opcode: OpAssign, Operands: []OperandKind{OperandSymbol}},
	{Name: "Unary", Opcode: OpUnary, Operands: []OperandKind{OperandSymbol}},
	{Name: "Binary", Opcode: OpBinary, Operands: []OperandKind{OperandSymbol}},
	{Name: "Cast", Opcode: OpCast},
	{Name: "Call", Opcode: OpCall, Operands: []OperandKind{OperandImmediate}},
	{Name: "Member", Opcode: OpMember, Operands: []OperandKind{OperandSymbol}},
	{Name: "If", Opcode: OpIf, Operands: []OperandKind{OperandBlock}},
	{Name: "Loop", Opcode: OpLoop, Operands: []OperandKind{OperandBlock}},
	{Name: "Break", Opcode: OpBreak, Operands: []OperandKind{OperandBlock}},
	{Name: "Return", Opcode: OpReturn},
	{Name: "Match", Opcode: OpMatch, Operands: []OperandKind{OperandImmediate}},
	{Name: "MatchClause", Opcode: OpMatchClause, Operands: []OperandKind{OperandImmediate}},
	{Name: "Pattern", Opcode: OpPattern, Operands: []OperandKind{OperandSymbol}},
	{Name: "Raise", Opcode: OpRaise},
	{Name: "Array", Opcode: OpArray, Operands: []OperandKind{OperandImmediate}},
	{Name: "Interpolate", Opcode: OpInterpolate, Operands: []OperandKind{OperandImmediate}},
	{Name: "HostEffect", Opcode: OpHostEffect, Operands: []OperandKind{OperandCapability, OperandImmediate}},
	{Name: "LoadConst", Opcode: OpLoadConst, Operands: []OperandKind{OperandRegister, OperandConstant}, Writes: []uint8{0}},
	{Name: "LoadGlobal", Opcode: OpLoadGlobal, Operands: []OperandKind{OperandRegister, OperandType, OperandSymbol}, Writes: []uint8{0}},
	{Name: "MoveValue", Opcode: OpMoveValue, Operands: []OperandKind{OperandRegister, OperandRegister}, Writes: []uint8{0}},
	{Name: "UnaryValue", Opcode: OpUnaryValue, Operands: []OperandKind{OperandRegister, OperandType, OperandSymbol, OperandRegister}, Writes: []uint8{0}},
	{Name: "BinaryValue", Opcode: OpBinaryValue, Operands: []OperandKind{OperandRegister, OperandType, OperandSymbol, OperandRegister, OperandRegister}, Writes: []uint8{0}},
	{Name: "CastValue", Opcode: OpCastValue, Operands: []OperandKind{OperandRegister, OperandType, OperandRegister}, Writes: []uint8{0}},
	{Name: "GetMemberValue", Opcode: OpGetMemberValue, Operands: []OperandKind{OperandRegister, OperandType, OperandRegister, OperandSymbol}, Writes: []uint8{0}},
	{Name: "Invoke", Opcode: OpInvoke, Operands: []OperandKind{OperandRegister, OperandCallTarget, OperandType}, Variadic: OperandRegister, Writes: []uint8{0}},
	{Name: "TypeTest", Opcode: OpTypeTest, Operands: []OperandKind{OperandRegister, OperandRegister, OperandType}, Writes: []uint8{0}},
	{Name: "Jump", Opcode: OpJump, Operands: []OperandKind{OperandBlock}, Terminator: true},
	{Name: "Branch", Opcode: OpBranch, Operands: []OperandKind{OperandRegister, OperandBlock, OperandBlock}, Terminator: true},
	{Name: "ReturnValue", Opcode: OpReturnValue, Operands: []OperandKind{OperandRegister}, Terminator: true},
	{Name: "RaiseValue", Opcode: OpRaiseValue, Operands: []OperandKind{OperandRegister}, Terminator: true},
	{Name: "MatchFail", Opcode: OpMatchFail, Terminator: true},
	{Name: "HostEffectResume", Opcode: OpHostEffectResume, Operands: []OperandKind{OperandRegister, OperandCapability, OperandType, OperandBlock}, Variadic: OperandRegister, Writes: []uint8{0}, Terminator: true},
}

const (
	LayoutString                  uint16 = 1
	LayoutArray                   uint16 = 2
	LayoutHashMap                 uint16 = 3
	LayoutHasher                  uint16 = 4
	LayoutFunction                uint16 = 5
	LayoutFunctionOverload        uint16 = 6
	LayoutStructDefinition        uint16 = 7
	LayoutTypeRef                 uint16 = 8
	LayoutStructInstance          uint16 = 9
	LayoutInterfaceDefinition     uint16 = 10
	LayoutInterfaceValue          uint16 = 11
	LayoutUnionDefinition         uint16 = 12
	LayoutPackage                 uint16 = 13
	LayoutDynPackage              uint16 = 14
	LayoutDynRef                  uint16 = 15
	LayoutError                   uint16 = 16
	LayoutBoundMethod             uint16 = 17
	LayoutImplementationNamespace uint16 = 18
	LayoutIterator                uint16 = 19
	LayoutPartialFunction         uint16 = 20
	LayoutEnvironment             uint16 = 21
	LayoutBindingCell             uint16 = 22
	LayoutSequenceStorage         uint16 = 23
	LayoutMapStorage              uint16 = 24
	LayoutIteratorState           uint16 = 25
	LayoutErrorContext            uint16 = 26
	LayoutWideScalar              uint16 = 27
)

var ObjectLayoutManifest = [...]ObjectLayoutDescriptor{
	{Name: "String", LayoutID: LayoutString, RuntimeTag: TagKindString, Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "utf8", Storage: FieldBytes}}},
	{Name: "Array", LayoutID: LayoutArray, RuntimeTag: TagKindArray, Mutability: LayoutMutable, Fields: []LayoutFieldDescriptor{{Name: "elements", Storage: FieldCells}, {Name: "element_type", Storage: FieldScalar}, {Name: "revision", Storage: FieldScalar}}},
	{Name: "HashMap", LayoutID: LayoutHashMap, RuntimeTag: TagKindHashMap, Mutability: LayoutMutable, Fields: []LayoutFieldDescriptor{{Name: "entries", Storage: FieldCells}, {Name: "hashes", Storage: FieldScalar}, {Name: "revision", Storage: FieldScalar}}},
	{Name: "Hasher", LayoutID: LayoutHasher, RuntimeTag: TagKindHasher, Mutability: LayoutMutable, Fields: []LayoutFieldDescriptor{{Name: "state", Storage: FieldScalar}}},
	{Name: "Function", LayoutID: LayoutFunction, RuntimeTag: TagKindFunction, Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "declaration", Storage: FieldScalar}, {Name: "environment", Storage: FieldObject}, {Name: "method_set", Storage: FieldObject}}},
	{Name: "FunctionOverload", LayoutID: LayoutFunctionOverload, RuntimeTag: TagKindFunctionOverload, Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "functions", Storage: FieldObjects}}},
	{Name: "StructDefinition", LayoutID: LayoutStructDefinition, RuntimeTag: TagKindStructDefinition, Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "definition", Storage: FieldScalar}, {Name: "field_names", Storage: FieldBytes}}},
	{Name: "TypeRef", LayoutID: LayoutTypeRef, RuntimeTag: TagKindTypeRef, Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "name", Storage: FieldBytes}, {Name: "type_arguments", Storage: FieldScalar}}},
	{Name: "StructInstance", LayoutID: LayoutStructInstance, RuntimeTag: TagKindStructInstance, Mutability: LayoutMutable, Fields: []LayoutFieldDescriptor{{Name: "definition", Storage: FieldObject}, {Name: "fields", Storage: FieldCells}, {Name: "type_arguments", Storage: FieldScalar}}},
	{Name: "InterfaceDefinition", LayoutID: LayoutInterfaceDefinition, RuntimeTag: TagKindInterfaceDefinition, Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "definition", Storage: FieldScalar}, {Name: "environment", Storage: FieldObject}, {Name: "qualified_name", Storage: FieldBytes}}},
	{Name: "InterfaceValue", LayoutID: LayoutInterfaceValue, RuntimeTag: TagKindInterfaceValue, Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "interface", Storage: FieldObject}, {Name: "underlying", Storage: FieldCell}, {Name: "methods", Storage: FieldCells}, {Name: "type_arguments", Storage: FieldScalar}}},
	{Name: "UnionDefinition", LayoutID: LayoutUnionDefinition, RuntimeTag: TagKindUnionDefinition, Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "definition", Storage: FieldScalar}}},
	{Name: "Package", LayoutID: LayoutPackage, RuntimeTag: TagKindPackage, Mutability: LayoutMutable, Fields: []LayoutFieldDescriptor{{Name: "name", Storage: FieldBytes}, {Name: "name_path", Storage: FieldBytes}, {Name: "identity", Storage: FieldBytes}, {Name: "flags", Storage: FieldScalar}, {Name: "public_names", Storage: FieldBytes}, {Name: "public_bindings", Storage: FieldCells}}},
	{Name: "DynPackage", LayoutID: LayoutDynPackage, RuntimeTag: TagKindDynPackage, Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "name", Storage: FieldBytes}, {Name: "name_path", Storage: FieldBytes}, {Name: "identity", Storage: FieldBytes}, {Name: "flags", Storage: FieldScalar}}},
	{Name: "DynRef", LayoutID: LayoutDynRef, RuntimeTag: TagKindDynRef, Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "package", Storage: FieldBytes}, {Name: "name", Storage: FieldBytes}}},
	{Name: "Error", LayoutID: LayoutError, RuntimeTag: TagKindError, Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "type", Storage: FieldScalar}, {Name: "payload", Storage: FieldCells}, {Name: "message", Storage: FieldBytes}, {Name: "context", Storage: FieldObject}}},
	{Name: "BoundMethod", LayoutID: LayoutBoundMethod, RuntimeTag: TagKindBoundMethod, Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "receiver", Storage: FieldCell}, {Name: "method", Storage: FieldCell}}},
	{Name: "ImplementationNamespace", LayoutID: LayoutImplementationNamespace, RuntimeTag: TagKindImplementationNamespace, Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "definition", Storage: FieldScalar}, {Name: "methods", Storage: FieldCells}}},
	{Name: "Iterator", LayoutID: LayoutIterator, RuntimeTag: TagKindIterator, Mutability: LayoutMutable, Fields: []LayoutFieldDescriptor{{Name: "driver", Storage: FieldCell}, {Name: "state", Storage: FieldObject}, {Name: "retained", Storage: FieldCells}, {Name: "closed", Storage: FieldScalar}}},
	{Name: "PartialFunction", LayoutID: LayoutPartialFunction, RuntimeTag: TagKindPartialFunction, Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "target", Storage: FieldCell}, {Name: "bound_arguments", Storage: FieldCells}, {Name: "call", Storage: FieldScalar}}},
	{Name: "Environment", LayoutID: LayoutEnvironment, RuntimeTag: uint32(0), Mutability: LayoutMutable, Fields: []LayoutFieldDescriptor{{Name: "parent", Storage: FieldObject}, {Name: "bindings", Storage: FieldObjects}}},
	{Name: "BindingCell", LayoutID: LayoutBindingCell, RuntimeTag: uint32(0), Mutability: LayoutMutable, Fields: []LayoutFieldDescriptor{{Name: "name", Storage: FieldBytes}, {Name: "value", Storage: FieldCell}}},
	{Name: "SequenceStorage", LayoutID: LayoutSequenceStorage, RuntimeTag: uint32(0), Mutability: LayoutMutable, Fields: []LayoutFieldDescriptor{{Name: "values", Storage: FieldCells}, {Name: "revision", Storage: FieldScalar}}},
	{Name: "MapStorage", LayoutID: LayoutMapStorage, RuntimeTag: uint32(0), Mutability: LayoutMutable, Fields: []LayoutFieldDescriptor{{Name: "entries", Storage: FieldCells}, {Name: "hashes", Storage: FieldScalar}, {Name: "revision", Storage: FieldScalar}}},
	{Name: "IteratorState", LayoutID: LayoutIteratorState, RuntimeTag: uint32(0), Mutability: LayoutMutable, Fields: []LayoutFieldDescriptor{{Name: "values", Storage: FieldCells}, {Name: "references", Storage: FieldObjects}, {Name: "position", Storage: FieldScalar}}},
	{Name: "ErrorContext", LayoutID: LayoutErrorContext, RuntimeTag: uint32(0), Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "values", Storage: FieldCells}, {Name: "causes", Storage: FieldObjects}, {Name: "source", Storage: FieldBytes}}},
	{Name: "WideScalar", LayoutID: LayoutWideScalar, RuntimeTag: uint32(0), Mutability: LayoutImmutable, Fields: []LayoutFieldDescriptor{{Name: "format", Storage: FieldScalar}, {Name: "payload", Storage: FieldBytes}}},
}

var HostLayoutManifest = [...]HostLayoutDescriptor{
	{Name: "NativeFunction", RuntimeTag: TagKindNativeFunction, Mutable: false, Cancelable: false, RetainsCells: true},
	{Name: "HostHandle", RuntimeTag: TagKindHostHandle, Mutable: true, Cancelable: false, RetainsCells: true},
	{Name: "NativeBoundMethod", RuntimeTag: TagKindNativeBoundMethod, Mutable: false, Cancelable: false, RetainsCells: true},
	{Name: "Future", RuntimeTag: TagKindFuture, Mutable: true, Cancelable: true, RetainsCells: true},
}
