package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderControlHelpers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "type __ableControlKind uint8\n\n")
	fmt.Fprintf(buf, "const (\n")
	fmt.Fprintf(buf, "\t__ableControlRaise __ableControlKind = iota + 1\n")
	fmt.Fprintf(buf, ")\n\n")
	fmt.Fprintf(buf, "type __ableControl struct {\n")
	fmt.Fprintf(buf, "\tKind  __ableControlKind\n")
	fmt.Fprintf(buf, "\tValue runtime.Value\n")
	fmt.Fprintf(buf, "\tErr   error\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_raise_control(node ast.Node, value runtime.Value) *__ableControl {\n")
	fmt.Fprintf(buf, "\tif value == nil {\n")
	fmt.Fprintf(buf, "\t\tvalue = runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_runtime != nil {\n")
	fmt.Fprintf(buf, "\t\tvalue = bridge.ErrorValue(__able_runtime, value)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn &__ableControl{Kind: __ableControlRaise, Value: value, Err: bridge.RaisedError(__able_runtime, node, value)}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_runtime_error_control(node ast.Node, err error) *__ableControl {\n")
	fmt.Fprintf(buf, "\tif err == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvalue := runtime.ErrorValue{Message: err.Error()}\n")
	fmt.Fprintf(buf, "\treturn &__ableControl{Kind: __ableControlRaise, Value: value, Err: bridge.RuntimeErrorWithContext(__able_runtime, node, err)}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_control_from_error(err error) *__ableControl {\n")
	fmt.Fprintf(buf, "\treturn __able_control_from_error_with_node(nil, err)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_control_from_error_with_node(node ast.Node, err error) *__ableControl {\n")
	fmt.Fprintf(buf, "\tif err == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch v := err.(type) {\n")
	fmt.Fprintf(buf, "\tcase __able_value_error:\n")
	fmt.Fprintf(buf, "\t\treturn __able_raise_control(node, v.value)\n")
	fmt.Fprintf(buf, "\tcase *__able_value_error:\n")
	fmt.Fprintf(buf, "\t\tif v == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_raise_control(node, v.value)\n")
	if g != nil && g.needsIterator {
		fmt.Fprintf(buf, "\tcase __able_generator_stop:\n")
		fmt.Fprintf(buf, "\t\treturn &__ableControl{Err: v}\n")
		fmt.Fprintf(buf, "\tcase *__able_generator_stop:\n")
		fmt.Fprintf(buf, "\t\tif v == nil {\n")
		fmt.Fprintf(buf, "\t\t\treturn nil\n")
		fmt.Fprintf(buf, "\t\t}\n")
		fmt.Fprintf(buf, "\t\treturn &__ableControl{Err: *v}\n")
	}
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn __able_runtime_error_control(node, err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_control_value(control *__ableControl) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif control == nil || control.Value == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn control.Value\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_control_to_error(rt *bridge.Runtime, ctx *runtime.NativeCallContext, control *__ableControl) error {\n")
	fmt.Fprintf(buf, "\tif control == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif control.Kind == __ableControlRaise {\n")
	fmt.Fprintf(buf, "\t\tif control.Err != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif _, ok := interpreter.ExitCodeFromError(control.Err); ok {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn control.Err\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_value_error{value: __able_control_value(control)}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif control.Err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn control.Err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.RaisedErrorIn(rt, ctx, __able_control_value(control))\n")
	fmt.Fprintf(buf, "}\n\n")
}
