package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderAlternativeIntegerArithmeticHelpers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "func __able_signed_bounds(bits int) (int64, int64) {\n")
	fmt.Fprintf(buf, "\tif bits >= 64 {\n")
	fmt.Fprintf(buf, "\t\tmax := int64(^uint64(0) >> 1)\n")
	fmt.Fprintf(buf, "\t\treturn -max - 1, max\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tmax := int64(1<<(bits-1)) - 1\n")
	fmt.Fprintf(buf, "\tmin := -int64(1 << (bits - 1))\n")
	fmt.Fprintf(buf, "\treturn min, max\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_unsigned_max(bits int) uint64 {\n")
	fmt.Fprintf(buf, "\tif bits >= 64 {\n")
	fmt.Fprintf(buf, "\t\treturn ^uint64(0)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn (uint64(1) << uint(bits)) - 1\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_abs_u64(value int64) uint64 {\n")
	fmt.Fprintf(buf, "\tif value >= 0 {\n")
	fmt.Fprintf(buf, "\t\treturn uint64(value)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn uint64(^value) + 1\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_try_add_signed(a int64, b int64, width int) (int64, bool) {\n")
	fmt.Fprintf(buf, "\tif width >= 64 {\n")
	fmt.Fprintf(buf, "\t\tresult := int64(uint64(a) + uint64(b))\n")
	fmt.Fprintf(buf, "\t\tif (a > 0 && b > 0 && result < 0) || (a < 0 && b < 0 && result >= 0) {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn result, true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tresult := a + b\n")
	fmt.Fprintf(buf, "\tmin, max := __able_signed_bounds(width)\n")
	fmt.Fprintf(buf, "\treturn result, result >= min && result <= max\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_try_sub_signed(a int64, b int64, width int) (int64, bool) {\n")
	fmt.Fprintf(buf, "\tif width >= 64 {\n")
	fmt.Fprintf(buf, "\t\tresult := int64(uint64(a) - uint64(b))\n")
	fmt.Fprintf(buf, "\t\tif (a >= 0 && b < 0 && result < 0) || (a < 0 && b > 0 && result >= 0) {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn result, true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tresult := a - b\n")
	fmt.Fprintf(buf, "\tmin, max := __able_signed_bounds(width)\n")
	fmt.Fprintf(buf, "\treturn result, result >= min && result <= max\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_try_mul_signed(a int64, b int64, width int) (int64, bool) {\n")
	fmt.Fprintf(buf, "\tif width < 64 {\n")
	fmt.Fprintf(buf, "\t\tresult := a * b\n")
	fmt.Fprintf(buf, "\t\tmin, max := __able_signed_bounds(width)\n")
	fmt.Fprintf(buf, "\t\treturn result, result >= min && result <= max\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tabsA := __able_abs_u64(a)\n")
	fmt.Fprintf(buf, "\tabsB := __able_abs_u64(b)\n")
	fmt.Fprintf(buf, "\tupper, lower := bits.Mul64(absA, absB)\n")
	fmt.Fprintf(buf, "\tif upper != 0 {\n")
	fmt.Fprintf(buf, "\t\treturn 0, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tnegative := (a < 0) != (b < 0)\n")
	fmt.Fprintf(buf, "\tif !negative {\n")
	fmt.Fprintf(buf, "\t\tif lower > uint64(^uint64(0)>>1) {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn int64(lower), true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tlimit := uint64(1) << 63\n")
	fmt.Fprintf(buf, "\tif lower > limit {\n")
	fmt.Fprintf(buf, "\t\treturn 0, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif lower == limit {\n")
	fmt.Fprintf(buf, "\t\treturn int64(lower), true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn -int64(lower), true\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_try_add_unsigned(a uint64, b uint64, width int) (uint64, bool) {\n")
	fmt.Fprintf(buf, "\tif width >= 64 {\n")
	fmt.Fprintf(buf, "\t\tresult, carry := bits.Add64(a, b, 0)\n")
	fmt.Fprintf(buf, "\t\treturn result, carry == 0\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tresult := a + b\n")
	fmt.Fprintf(buf, "\treturn result, result <= __able_unsigned_max(width)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_try_sub_unsigned(a uint64, b uint64, width int) (uint64, bool) {\n")
	fmt.Fprintf(buf, "\tif a < b {\n")
	fmt.Fprintf(buf, "\t\treturn 0, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tresult := a - b\n")
	fmt.Fprintf(buf, "\treturn result, width >= 64 || result <= __able_unsigned_max(width)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_try_mul_unsigned(a uint64, b uint64, width int) (uint64, bool) {\n")
	fmt.Fprintf(buf, "\tif width >= 64 {\n")
	fmt.Fprintf(buf, "\t\tupper, lower := bits.Mul64(a, b)\n")
	fmt.Fprintf(buf, "\t\treturn lower, upper == 0\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tresult := a * b\n")
	fmt.Fprintf(buf, "\treturn result, result <= __able_unsigned_max(width)\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_saturating_add_signed(a int64, b int64, width int) int64 {\n")
	fmt.Fprintf(buf, "\tif result, ok := __able_try_add_signed(a, b, width); ok { return result }\n")
	fmt.Fprintf(buf, "\tmin, max := __able_signed_bounds(width)\n")
	fmt.Fprintf(buf, "\tif b < 0 { return min }\n")
	fmt.Fprintf(buf, "\treturn max\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_saturating_sub_signed(a int64, b int64, width int) int64 {\n")
	fmt.Fprintf(buf, "\tif result, ok := __able_try_sub_signed(a, b, width); ok { return result }\n")
	fmt.Fprintf(buf, "\tmin, max := __able_signed_bounds(width)\n")
	fmt.Fprintf(buf, "\tif b > 0 { return min }\n")
	fmt.Fprintf(buf, "\treturn max\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_saturating_mul_signed(a int64, b int64, width int) int64 {\n")
	fmt.Fprintf(buf, "\tif result, ok := __able_try_mul_signed(a, b, width); ok { return result }\n")
	fmt.Fprintf(buf, "\tmin, max := __able_signed_bounds(width)\n")
	fmt.Fprintf(buf, "\tif (a < 0) != (b < 0) { return min }\n")
	fmt.Fprintf(buf, "\treturn max\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_saturating_add_unsigned(a uint64, b uint64, width int) uint64 {\n")
	fmt.Fprintf(buf, "\tif result, ok := __able_try_add_unsigned(a, b, width); ok { return result }\n")
	fmt.Fprintf(buf, "\treturn __able_unsigned_max(width)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_saturating_sub_unsigned(a uint64, b uint64, width int) uint64 {\n")
	fmt.Fprintf(buf, "\tif result, ok := __able_try_sub_unsigned(a, b, width); ok { return result }\n")
	fmt.Fprintf(buf, "\treturn 0\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_saturating_mul_unsigned(a uint64, b uint64, width int) uint64 {\n")
	fmt.Fprintf(buf, "\tif result, ok := __able_try_mul_unsigned(a, b, width); ok { return result }\n")
	fmt.Fprintf(buf, "\treturn __able_unsigned_max(width)\n")
	fmt.Fprintf(buf, "}\n\n")
}
