package compiler

import (
	"bytes"
	"fmt"
	"sort"
)

func (g *generator) renderRuntimeInterfaceDispatch(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "type __able_interface_constraint_spec struct {\n")
	fmt.Fprintf(buf, "\tsubject ast.TypeExpression\n")
	fmt.Fprintf(buf, "\tiface   ast.TypeExpression\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_interface_dispatch_entry struct {\n")
	fmt.Fprintf(buf, "\ttargetType     ast.TypeExpression\n")
	fmt.Fprintf(buf, "\tinterfaceArgs  []ast.TypeExpression\n")
	fmt.Fprintf(buf, "\tgenericNames   map[string]struct{}\n")
	fmt.Fprintf(buf, "\tconstraints    []__able_interface_constraint_spec\n")
	fmt.Fprintf(buf, "\tconstraintKeys map[string]struct{}\n")
	fmt.Fprintf(buf, "\tunionVariants  []string\n")
	fmt.Fprintf(buf, "\ttargetScore    int\n")
	fmt.Fprintf(buf, "\tisConcrete     bool\n")
	fmt.Fprintf(buf, "\tfn             *runtime.NativeFunctionValue\n")
	fmt.Fprintf(buf, "\tisPrivate      bool\n")
	fmt.Fprintf(buf, "\tisBuiltin      bool\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_interface_dispatch_match struct {\n")
	fmt.Fprintf(buf, "\tentry    __able_interface_dispatch_entry\n")
	fmt.Fprintf(buf, "\treceiver runtime.Value\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "var __able_interface_dispatch map[string]map[string][]__able_interface_dispatch_entry\n")
	fmt.Fprintf(buf, "var __able_interface_dispatch_strict bool\n\n")

	search := g.interfaceSearchMap()
	if len(search) > 0 {
		fmt.Fprintf(buf, "var __able_interface_search_names = map[string][]string{\n")
		names := make([]string, 0, len(search))
		for name := range search {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			list := search[name]
			fmt.Fprintf(buf, "\t%q: {", name)
			for idx, entry := range list {
				if idx > 0 {
					fmt.Fprintf(buf, ", ")
				}
				fmt.Fprintf(buf, "%q", entry)
			}
			fmt.Fprintf(buf, "},\n")
		}
		fmt.Fprintf(buf, "}\n\n")
	} else {
		fmt.Fprintf(buf, "var __able_interface_search_names map[string][]string\n\n")
	}

	baseTypes := g.interfaceBaseTypesMap()
	if len(baseTypes) > 0 {
		fmt.Fprintf(buf, "var __able_interface_base_types = map[string][]ast.TypeExpression{\n")
		names := make([]string, 0, len(baseTypes))
		for name := range baseTypes {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			bases := baseTypes[name]
			if len(bases) == 0 {
				continue
			}
			fmt.Fprintf(buf, "\t%q: {", name)
			wrote := false
			for _, base := range bases {
				baseExpr, ok := g.renderTypeExpression(base)
				if !ok {
					continue
				}
				if wrote {
					fmt.Fprintf(buf, ", ")
				}
				wrote = true
				fmt.Fprintf(buf, "%s", baseExpr)
			}
			fmt.Fprintf(buf, "},\n")
		}
		fmt.Fprintf(buf, "}\n\n")
	} else {
		fmt.Fprintf(buf, "var __able_interface_base_types map[string][]ast.TypeExpression\n\n")
	}

	fmt.Fprintf(buf, "func __able_type_expr_equal(a ast.TypeExpression, b ast.TypeExpression) bool {\n")
	fmt.Fprintf(buf, "\tif a == nil && b == nil {\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif a == nil || b == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch ta := a.(type) {\n")
	fmt.Fprintf(buf, "\tcase *ast.SimpleTypeExpression:\n")
	fmt.Fprintf(buf, "\t\ttb, ok := b.(*ast.SimpleTypeExpression)\n")
	fmt.Fprintf(buf, "\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif ta.Name == nil || tb.Name == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn ta.Name == nil && tb.Name == nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn ta.Name.Name == tb.Name.Name\n")
	fmt.Fprintf(buf, "\tcase *ast.GenericTypeExpression:\n")
	fmt.Fprintf(buf, "\t\ttb, ok := b.(*ast.GenericTypeExpression)\n")
	fmt.Fprintf(buf, "\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !__able_type_expr_equal(ta.Base, tb.Base) {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif len(ta.Arguments) != len(tb.Arguments) {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tfor idx := range ta.Arguments {\n")
	fmt.Fprintf(buf, "\t\t\tif !__able_type_expr_equal(ta.Arguments[idx], tb.Arguments[idx]) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\tcase *ast.NullableTypeExpression:\n")
	fmt.Fprintf(buf, "\t\ttb, ok := b.(*ast.NullableTypeExpression)\n")
	fmt.Fprintf(buf, "\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_type_expr_equal(ta.InnerType, tb.InnerType)\n")
	fmt.Fprintf(buf, "\tcase *ast.ResultTypeExpression:\n")
	fmt.Fprintf(buf, "\t\ttb, ok := b.(*ast.ResultTypeExpression)\n")
	fmt.Fprintf(buf, "\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_type_expr_equal(ta.InnerType, tb.InnerType)\n")
	fmt.Fprintf(buf, "\tcase *ast.FunctionTypeExpression:\n")
	fmt.Fprintf(buf, "\t\ttb, ok := b.(*ast.FunctionTypeExpression)\n")
	fmt.Fprintf(buf, "\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif len(ta.ParamTypes) != len(tb.ParamTypes) {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tfor idx := range ta.ParamTypes {\n")
	fmt.Fprintf(buf, "\t\t\tif !__able_type_expr_equal(ta.ParamTypes[idx], tb.ParamTypes[idx]) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_type_expr_equal(ta.ReturnType, tb.ReturnType)\n")
	fmt.Fprintf(buf, "\tcase *ast.UnionTypeExpression:\n")
	fmt.Fprintf(buf, "\t\ttb, ok := b.(*ast.UnionTypeExpression)\n")
	fmt.Fprintf(buf, "\t\tif !ok || len(ta.Members) != len(tb.Members) {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tfor idx := range ta.Members {\n")
	fmt.Fprintf(buf, "\t\t\tif !__able_type_expr_equal(ta.Members[idx], tb.Members[idx]) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\tcase *ast.WildcardTypeExpression:\n")
	fmt.Fprintf(buf, "\t\t_, ok := b.(*ast.WildcardTypeExpression)\n")
	fmt.Fprintf(buf, "\t\treturn ok\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_type_expr_list_equal(a []ast.TypeExpression, b []ast.TypeExpression) bool {\n")
	fmt.Fprintf(buf, "\tif len(a) != len(b) {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfor idx := range a {\n")
	fmt.Fprintf(buf, "\t\tif !__able_type_expr_equal(a[idx], b[idx]) {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn true\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_type_expr_string(expr ast.TypeExpression) string {\n")
	fmt.Fprintf(buf, "\tswitch t := expr.(type) {\n")
	fmt.Fprintf(buf, "\tcase *ast.SimpleTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tif t.Name == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn \"<?>\"\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn t.Name.Name\n")
	fmt.Fprintf(buf, "\tcase *ast.GenericTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tbase := __able_type_expr_string(t.Base)\n")
	fmt.Fprintf(buf, "\t\targs := make([]string, 0, len(t.Arguments))\n")
	fmt.Fprintf(buf, "\t\tfor _, arg := range t.Arguments {\n")
	fmt.Fprintf(buf, "\t\t\targs = append(args, __able_type_expr_string(arg))\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn fmt.Sprintf(\"%%s<%%s>\", base, strings.Join(args, \", \"))\n")
	fmt.Fprintf(buf, "\tcase *ast.NullableTypeExpression:\n")
	fmt.Fprintf(buf, "\t\treturn __able_type_expr_string(t.InnerType) + \"?\"\n")
	fmt.Fprintf(buf, "\tcase *ast.FunctionTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tparts := make([]string, 0, len(t.ParamTypes))\n")
	fmt.Fprintf(buf, "\t\tfor _, param := range t.ParamTypes {\n")
	fmt.Fprintf(buf, "\t\t\tparts = append(parts, __able_type_expr_string(param))\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn fmt.Sprintf(\"fn(%%s) -> %%s\", strings.Join(parts, \", \"), __able_type_expr_string(t.ReturnType))\n")
	fmt.Fprintf(buf, "\tcase *ast.UnionTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tparts := make([]string, 0, len(t.Members))\n")
	fmt.Fprintf(buf, "\t\tfor _, member := range t.Members {\n")
	fmt.Fprintf(buf, "\t\t\tparts = append(parts, __able_type_expr_string(member))\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn strings.Join(parts, \" | \")\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn \"<?>\"\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_type_expr_uses_generics(expr ast.TypeExpression, generics map[string]struct{}) bool {\n")
	fmt.Fprintf(buf, "\tif expr == nil || len(generics) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch t := expr.(type) {\n")
	fmt.Fprintf(buf, "\tcase *ast.SimpleTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tif t.Name == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\t_, ok := generics[t.Name.Name]\n")
	fmt.Fprintf(buf, "\t\treturn ok\n")
	fmt.Fprintf(buf, "\tcase *ast.GenericTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tif __able_type_expr_uses_generics(t.Base, generics) {\n")
	fmt.Fprintf(buf, "\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tfor _, arg := range t.Arguments {\n")
	fmt.Fprintf(buf, "\t\t\tif __able_type_expr_uses_generics(arg, generics) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\tcase *ast.NullableTypeExpression:\n")
	fmt.Fprintf(buf, "\t\treturn __able_type_expr_uses_generics(t.InnerType, generics)\n")
	fmt.Fprintf(buf, "\tcase *ast.ResultTypeExpression:\n")
	fmt.Fprintf(buf, "\t\treturn __able_type_expr_uses_generics(t.InnerType, generics)\n")
	fmt.Fprintf(buf, "\tcase *ast.UnionTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tfor _, member := range t.Members {\n")
	fmt.Fprintf(buf, "\t\t\tif __able_type_expr_uses_generics(member, generics) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\tcase *ast.FunctionTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tif __able_type_expr_uses_generics(t.ReturnType, generics) {\n")
	fmt.Fprintf(buf, "\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tfor _, param := range t.ParamTypes {\n")
	fmt.Fprintf(buf, "\t\t\tif __able_type_expr_uses_generics(param, generics) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_template_specificity(expr ast.TypeExpression, generics map[string]struct{}) int {\n")
	fmt.Fprintf(buf, "\tif expr == nil {\n")
	fmt.Fprintf(buf, "\t\treturn 0\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch t := expr.(type) {\n")
	fmt.Fprintf(buf, "\tcase *ast.SimpleTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tif t.Name == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif _, ok := generics[t.Name.Name]; ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn 1\n")
	fmt.Fprintf(buf, "\tcase *ast.GenericTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tscore := __able_template_specificity(t.Base, generics)\n")
	fmt.Fprintf(buf, "\t\tfor _, arg := range t.Arguments {\n")
	fmt.Fprintf(buf, "\t\t\tscore += __able_template_specificity(arg, generics)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn score\n")
	fmt.Fprintf(buf, "\tcase *ast.NullableTypeExpression:\n")
	fmt.Fprintf(buf, "\t\treturn __able_template_specificity(t.InnerType, generics)\n")
	fmt.Fprintf(buf, "\tcase *ast.ResultTypeExpression:\n")
	fmt.Fprintf(buf, "\t\treturn __able_template_specificity(t.InnerType, generics)\n")
	fmt.Fprintf(buf, "\tcase *ast.UnionTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tscore := 0\n")
	fmt.Fprintf(buf, "\t\tfor _, member := range t.Members {\n")
	fmt.Fprintf(buf, "\t\t\tscore += __able_template_specificity(member, generics)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn score\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn 0\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_is_primitive_type_name(name string) bool {\n")
	fmt.Fprintf(buf, "\tswitch name {\n")
	fmt.Fprintf(buf, "\tcase \"bool\", \"String\", \"string\", \"IoHandle\", \"ProcHandle\", \"char\", \"nil\", \"void\":\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch name {\n")
	fmt.Fprintf(buf, "\tcase \"i8\", \"i16\", \"i32\", \"i64\", \"i128\", \"u8\", \"u16\", \"u32\", \"u64\", \"u128\", \"isize\", \"usize\":\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\tcase \"f32\", \"f64\":\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn false\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_is_known_type_name(name string) bool {\n")
	fmt.Fprintf(buf, "\tif name == \"\" || name == \"_\" || name == \"Self\" {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_is_primitive_type_name(name) {\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.IsKnownConstraintTypeName(__able_runtime, name)\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_type_expr_has_unknown_names(expr ast.TypeExpression) bool {\n")
	fmt.Fprintf(buf, "\tswitch t := expr.(type) {\n")
	fmt.Fprintf(buf, "\tcase *ast.SimpleTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tif t.Name == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn !__able_is_known_type_name(t.Name.Name)\n")
	fmt.Fprintf(buf, "\tcase *ast.GenericTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tif __able_type_expr_has_unknown_names(t.Base) {\n")
	fmt.Fprintf(buf, "\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tfor _, arg := range t.Arguments {\n")
	fmt.Fprintf(buf, "\t\t\tif __able_type_expr_has_unknown_names(arg) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\tcase *ast.FunctionTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tif __able_type_expr_has_unknown_names(t.ReturnType) {\n")
	fmt.Fprintf(buf, "\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tfor _, param := range t.ParamTypes {\n")
	fmt.Fprintf(buf, "\t\t\tif __able_type_expr_has_unknown_names(param) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\tcase *ast.NullableTypeExpression:\n")
	fmt.Fprintf(buf, "\t\treturn __able_type_expr_has_unknown_names(t.InnerType)\n")
	fmt.Fprintf(buf, "\tcase *ast.ResultTypeExpression:\n")
	fmt.Fprintf(buf, "\t\treturn __able_type_expr_has_unknown_names(t.InnerType)\n")
	fmt.Fprintf(buf, "\tcase *ast.UnionTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tfor _, member := range t.Members {\n")
	fmt.Fprintf(buf, "\t\t\tif __able_type_expr_has_unknown_names(member) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_substitute_type_params(expr ast.TypeExpression, bindings map[string]ast.TypeExpression) ast.TypeExpression {\n")
	fmt.Fprintf(buf, "\tif expr == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch t := expr.(type) {\n")
	fmt.Fprintf(buf, "\tcase *ast.SimpleTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tif t.Name != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif replacement, ok := bindings[t.Name.Name]; ok {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn replacement\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn t\n")
	fmt.Fprintf(buf, "\tcase *ast.GenericTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tbase := __able_substitute_type_params(t.Base, bindings)\n")
	fmt.Fprintf(buf, "\t\targs := make([]ast.TypeExpression, len(t.Arguments))\n")
	fmt.Fprintf(buf, "\t\tfor idx, arg := range t.Arguments {\n")
	fmt.Fprintf(buf, "\t\t\targs[idx] = __able_substitute_type_params(arg, bindings)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn ast.NewGenericTypeExpression(base, args)\n")
	fmt.Fprintf(buf, "\tcase *ast.FunctionTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tparams := make([]ast.TypeExpression, len(t.ParamTypes))\n")
	fmt.Fprintf(buf, "\t\tfor idx, param := range t.ParamTypes {\n")
	fmt.Fprintf(buf, "\t\t\tparams[idx] = __able_substitute_type_params(param, bindings)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn ast.NewFunctionTypeExpression(params, __able_substitute_type_params(t.ReturnType, bindings))\n")
	fmt.Fprintf(buf, "\tcase *ast.NullableTypeExpression:\n")
	fmt.Fprintf(buf, "\t\treturn ast.NewNullableTypeExpression(__able_substitute_type_params(t.InnerType, bindings))\n")
	fmt.Fprintf(buf, "\tcase *ast.ResultTypeExpression:\n")
	fmt.Fprintf(buf, "\t\treturn ast.NewResultTypeExpression(__able_substitute_type_params(t.InnerType, bindings))\n")
	fmt.Fprintf(buf, "\tcase *ast.UnionTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tmembers := make([]ast.TypeExpression, len(t.Members))\n")
	fmt.Fprintf(buf, "\t\tfor idx, member := range t.Members {\n")
	fmt.Fprintf(buf, "\t\t\tmembers[idx] = __able_substitute_type_params(member, bindings)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn ast.NewUnionTypeExpression(members)\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn expr\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_collect_interface_constraint_strings(typeExpr ast.TypeExpression, memo map[string]struct{}) []string {\n")
	fmt.Fprintf(buf, "\tif typeExpr == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tkey := __able_type_expr_string(typeExpr)\n")
	fmt.Fprintf(buf, "\tif _, seen := memo[key]; seen {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tmemo[key] = struct{}{}\n")
	fmt.Fprintf(buf, "\tresults := []string{key}\n")
	fmt.Fprintf(buf, "\tif simple, ok := typeExpr.(*ast.SimpleTypeExpression); ok && simple.Name != nil {\n")
	fmt.Fprintf(buf, "\t\tif bases := __able_interface_base_types[simple.Name.Name]; len(bases) > 0 {\n")
	fmt.Fprintf(buf, "\t\t\tfor _, base := range bases {\n")
	fmt.Fprintf(buf, "\t\t\t\tresults = append(results, __able_collect_interface_constraint_strings(base, memo)...)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn results\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_constraint_key_set(constraints []__able_interface_constraint_spec) map[string]struct{} {\n")
	fmt.Fprintf(buf, "\tif len(constraints) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tset := make(map[string]struct{})\n")
	fmt.Fprintf(buf, "\tfor _, c := range constraints {\n")
	fmt.Fprintf(buf, "\t\tif c.iface == nil {\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\texpressions := __able_collect_interface_constraint_strings(c.iface, make(map[string]struct{}))\n")
	fmt.Fprintf(buf, "\t\tfor _, expr := range expressions {\n")
	fmt.Fprintf(buf, "\t\t\tkey := fmt.Sprintf(\"%%s->%%s\", __able_type_expr_string(c.subject), expr)\n")
	fmt.Fprintf(buf, "\t\t\tset[key] = struct{}{}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn set\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_is_constraint_superset(a, b map[string]struct{}) bool {\n")
	fmt.Fprintf(buf, "\tif len(a) <= len(b) {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfor key := range b {\n")
	fmt.Fprintf(buf, "\t\tif _, ok := a[key]; !ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn true\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_is_proper_subset(a, b []string) bool {\n")
	fmt.Fprintf(buf, "\tif len(a) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn len(b) > 0\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tsetA := make(map[string]struct{}, len(a))\n")
	fmt.Fprintf(buf, "\tfor _, val := range a {\n")
	fmt.Fprintf(buf, "\t\tsetA[val] = struct{}{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tsetB := make(map[string]struct{}, len(b))\n")
	fmt.Fprintf(buf, "\tfor _, val := range b {\n")
	fmt.Fprintf(buf, "\t\tsetB[val] = struct{}{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(setA) >= len(setB) {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfor val := range setA {\n")
	fmt.Fprintf(buf, "\t\tif _, ok := setB[val]; !ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn true\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_compare_interface_entries(a, b __able_interface_dispatch_entry) int {\n")
	fmt.Fprintf(buf, "\tif a.isConcrete && !b.isConcrete {\n")
	fmt.Fprintf(buf, "\t\treturn 1\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif b.isConcrete && !a.isConcrete {\n")
	fmt.Fprintf(buf, "\t\treturn -1\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_is_constraint_superset(a.constraintKeys, b.constraintKeys) {\n")
	fmt.Fprintf(buf, "\t\treturn 1\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_is_constraint_superset(b.constraintKeys, a.constraintKeys) {\n")
	fmt.Fprintf(buf, "\t\treturn -1\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\taUnion := a.unionVariants\n")
	fmt.Fprintf(buf, "\tbUnion := b.unionVariants\n")
	fmt.Fprintf(buf, "\tif len(aUnion) > 0 && len(bUnion) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn -1\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(aUnion) == 0 && len(bUnion) > 0 {\n")
	fmt.Fprintf(buf, "\t\treturn 1\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(aUnion) > 0 && len(bUnion) > 0 {\n")
	fmt.Fprintf(buf, "\t\tif __able_is_proper_subset(aUnion, bUnion) {\n")
	fmt.Fprintf(buf, "\t\t\treturn 1\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif __able_is_proper_subset(bUnion, aUnion) {\n")
	fmt.Fprintf(buf, "\t\t\treturn -1\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif len(aUnion) != len(bUnion) {\n")
	fmt.Fprintf(buf, "\t\t\tif len(aUnion) < len(bUnion) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn 1\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn -1\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif a.targetScore > b.targetScore {\n")
	fmt.Fprintf(buf, "\t\treturn 1\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif a.targetScore < b.targetScore {\n")
	fmt.Fprintf(buf, "\t\treturn -1\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif a.isBuiltin != b.isBuiltin {\n")
	fmt.Fprintf(buf, "\t\tif a.isBuiltin {\n")
	fmt.Fprintf(buf, "\t\t\treturn -1\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn 1\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn 0\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_expand_union_targets(expr ast.TypeExpression) ([]ast.TypeExpression, []string) {\n")
	fmt.Fprintf(buf, "\tif expr == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch t := expr.(type) {\n")
	fmt.Fprintf(buf, "\tcase *ast.UnionTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tvariants := make([]ast.TypeExpression, 0)\n")
	fmt.Fprintf(buf, "\t\tvariantSet := make(map[string]struct{})\n")
	fmt.Fprintf(buf, "\t\tsigSet := make(map[string]struct{})\n")
	fmt.Fprintf(buf, "\t\tfor _, member := range t.Members {\n")
	fmt.Fprintf(buf, "\t\t\tchildVariants, childSigs := __able_expand_union_targets(member)\n")
	fmt.Fprintf(buf, "\t\t\tfor _, sig := range childSigs {\n")
	fmt.Fprintf(buf, "\t\t\t\tsigSet[sig] = struct{}{}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tfor _, variant := range childVariants {\n")
	fmt.Fprintf(buf, "\t\t\t\tsig := __able_type_expr_string(variant)\n")
	fmt.Fprintf(buf, "\t\t\t\tif _, seen := variantSet[sig]; seen {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tvariantSet[sig] = struct{}{}\n")
	fmt.Fprintf(buf, "\t\t\t\tvariants = append(variants, variant)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif len(variants) == 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tunionSigs := make([]string, 0, len(sigSet))\n")
	fmt.Fprintf(buf, "\t\tfor sig := range sigSet {\n")
	fmt.Fprintf(buf, "\t\t\tunionSigs = append(unionSigs, sig)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tsort.Strings(unionSigs)\n")
	fmt.Fprintf(buf, "\t\treturn variants, unionSigs\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn []ast.TypeExpression{expr}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_match_type_template(template ast.TypeExpression, actual ast.TypeExpression, generics map[string]struct{}, bindings map[string]ast.TypeExpression) bool {\n")
	fmt.Fprintf(buf, "\tif template == nil {\n")
	fmt.Fprintf(buf, "\t\treturn actual == nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch t := template.(type) {\n")
	fmt.Fprintf(buf, "\tcase *ast.SimpleTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tif t.Name == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn actual == nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tname := t.Name.Name\n")
	fmt.Fprintf(buf, "\t\tif _, isGeneric := generics[name]; isGeneric {\n")
	fmt.Fprintf(buf, "\t\t\tif existing, ok := bindings[name]; ok {\n")
	fmt.Fprintf(buf, "\t\t\t\tif _, ok := existing.(*ast.WildcardTypeExpression); ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif actual != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif _, ok := actual.(*ast.WildcardTypeExpression); !ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\tbindings[name] = actual\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif _, ok := actual.(*ast.WildcardTypeExpression); ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\treturn __able_type_expr_equal(existing, actual)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tbindings[name] = actual\n")
	fmt.Fprintf(buf, "\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_type_expr_equal(template, actual)\n")
	fmt.Fprintf(buf, "\tcase *ast.GenericTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tswitch other := actual.(type) {\n")
	fmt.Fprintf(buf, "\t\tcase *ast.GenericTypeExpression:\n")
	fmt.Fprintf(buf, "\t\t\tif !__able_match_type_template(t.Base, other.Base, generics, bindings) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\totherArgs := other.Arguments\n")
	fmt.Fprintf(buf, "\t\t\tif len(otherArgs) == 0 && len(t.Arguments) > 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\totherArgs = make([]ast.TypeExpression, len(t.Arguments))\n")
	fmt.Fprintf(buf, "\t\t\t\tfor idx := range otherArgs {\n")
	fmt.Fprintf(buf, "\t\t\t\t\totherArgs[idx] = ast.NewWildcardTypeExpression()\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif len(t.Arguments) != len(otherArgs) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tfor idx := range t.Arguments {\n")
	fmt.Fprintf(buf, "\t\t\t\tif !__able_match_type_template(t.Arguments[idx], otherArgs[idx], generics, bindings) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\tcase *ast.SimpleTypeExpression:\n")
	fmt.Fprintf(buf, "\t\t\tif !__able_match_type_template(t.Base, other, generics, bindings) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tfor idx := range t.Arguments {\n")
	fmt.Fprintf(buf, "\t\t\t\tif !__able_match_type_template(t.Arguments[idx], ast.NewWildcardTypeExpression(), generics, bindings) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\tcase *ast.NullableTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tother, ok := actual.(*ast.NullableTypeExpression)\n")
	fmt.Fprintf(buf, "\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_match_type_template(t.InnerType, other.InnerType, generics, bindings)\n")
	fmt.Fprintf(buf, "\tcase *ast.ResultTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tother, ok := actual.(*ast.ResultTypeExpression)\n")
	fmt.Fprintf(buf, "\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_match_type_template(t.InnerType, other.InnerType, generics, bindings)\n")
	fmt.Fprintf(buf, "\tcase *ast.UnionTypeExpression:\n")
	fmt.Fprintf(buf, "\t\tother, ok := actual.(*ast.UnionTypeExpression)\n")
	fmt.Fprintf(buf, "\t\tif !ok || len(t.Members) != len(other.Members) {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tfor idx := range t.Members {\n")
	fmt.Fprintf(buf, "\t\t\tif !__able_match_type_template(t.Members[idx], other.Members[idx], generics, bindings) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn __able_type_expr_equal(template, actual)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_enforce_constraints(constraints []__able_interface_constraint_spec, bindings map[string]ast.TypeExpression) bool {\n")
	fmt.Fprintf(buf, "\tif len(constraints) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif bindings == nil {\n")
	fmt.Fprintf(buf, "\t\tbindings = map[string]ast.TypeExpression{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfor _, spec := range constraints {\n")
	fmt.Fprintf(buf, "\t\tsubject := __able_substitute_type_params(spec.subject, bindings)\n")
	fmt.Fprintf(buf, "\t\tif __able_type_expr_has_unknown_names(subject) {\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tctx := __able_type_expr_string(subject)\n")
	fmt.Fprintf(buf, "\t\tif err := bridge.EnsureTypeSatisfiesInterface(__able_runtime, subject, spec.iface, ctx); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn true\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_is_interface_type(expr ast.TypeExpression) bool {\n")
	fmt.Fprintf(buf, "\tif expr == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tsimple, ok := expr.(*ast.SimpleTypeExpression)\n")
	fmt.Fprintf(buf, "\tif !ok || simple.Name == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_interface_search_names != nil {\n")
	fmt.Fprintf(buf, "\t\tif _, ok := __able_interface_search_names[simple.Name.Name]; ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn false\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_interface_method_receiver(val *runtime.InterfaceValue, method runtime.Value) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treceiver := __able_unwrap_interface(val.Underlying)\n")
	fmt.Fprintf(buf, "\tif receiver == nil {\n")
	fmt.Fprintf(buf, "\t\treceiver = runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcandidate := method\n")
	fmt.Fprintf(buf, "\tswitch fn := method.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.BoundMethodValue:\n")
	fmt.Fprintf(buf, "\t\tcandidate = fn.Method\n")
	fmt.Fprintf(buf, "\tcase *runtime.BoundMethodValue:\n")
	fmt.Fprintf(buf, "\t\tif fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\tcandidate = fn.Method\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfor _, fn := range runtime.FlattenFunctionOverloads(candidate) {\n")
	fmt.Fprintf(buf, "\t\tif fn == nil || fn.MethodSet == nil || fn.MethodSet.TargetType == nil {\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif __able_is_interface_type(fn.MethodSet.TargetType) {\n")
	fmt.Fprintf(buf, "\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn receiver\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_interface_bind_method(val *runtime.InterfaceValue, method runtime.Value) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif val == nil || method == nil {\n")
	fmt.Fprintf(buf, "\t\treturn method\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treceiver := __able_interface_method_receiver(val, method)\n")
	fmt.Fprintf(buf, "\tswitch fn := method.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.NativeFunctionValue:\n")
	fmt.Fprintf(buf, "\t\treturn &runtime.NativeBoundMethodValue{Receiver: receiver, Method: fn}\n")
	fmt.Fprintf(buf, "\tcase *runtime.NativeFunctionValue:\n")
	fmt.Fprintf(buf, "\t\tif fn == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn &runtime.NativeBoundMethodValue{Receiver: receiver, Method: *fn}\n")
	fmt.Fprintf(buf, "\tcase runtime.NativeBoundMethodValue:\n")
	fmt.Fprintf(buf, "\t\treturn &runtime.NativeBoundMethodValue{Receiver: receiver, Method: fn.Method}\n")
	fmt.Fprintf(buf, "\tcase *runtime.NativeBoundMethodValue:\n")
	fmt.Fprintf(buf, "\t\tif fn == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn &runtime.NativeBoundMethodValue{Receiver: receiver, Method: fn.Method}\n")
	fmt.Fprintf(buf, "\tcase runtime.BoundMethodValue:\n")
	fmt.Fprintf(buf, "\t\treturn &runtime.BoundMethodValue{Receiver: receiver, Method: fn.Method}\n")
	fmt.Fprintf(buf, "\tcase *runtime.BoundMethodValue:\n")
	fmt.Fprintf(buf, "\t\tif fn == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn &runtime.BoundMethodValue{Receiver: receiver, Method: fn.Method}\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn &runtime.BoundMethodValue{Receiver: receiver, Method: method}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_generic_name_set(names []string) map[string]struct{} {\n")
	fmt.Fprintf(buf, "\tif len(names) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tset := make(map[string]struct{}, len(names))\n")
	fmt.Fprintf(buf, "\tfor _, name := range names {\n")
	fmt.Fprintf(buf, "\t\tif name == \"\" {\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tset[name] = struct{}{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn set\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_register_interface_dispatch(ifaceName string, methodName string, targetType ast.TypeExpression, ifaceArgs []ast.TypeExpression, genericNames []string, constraints []__able_interface_constraint_spec, fn *runtime.NativeFunctionValue, isPrivate bool, isBuiltin bool) {\n")
	fmt.Fprintf(buf, "\tif ifaceName == \"\" || methodName == \"\" || targetType == nil || fn == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_interface_dispatch == nil {\n")
	fmt.Fprintf(buf, "\t\t__able_interface_dispatch = make(map[string]map[string][]__able_interface_dispatch_entry)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tperIface := __able_interface_dispatch[ifaceName]\n")
	fmt.Fprintf(buf, "\tif perIface == nil {\n")
	fmt.Fprintf(buf, "\t\tperIface = make(map[string][]__able_interface_dispatch_entry)\n")
	fmt.Fprintf(buf, "\t\t__able_interface_dispatch[ifaceName] = perIface\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tgenericSet := __able_generic_name_set(genericNames)\n")
	fmt.Fprintf(buf, "\texpanded := targetType\n")
	fmt.Fprintf(buf, "\tif __able_runtime != nil {\n")
	fmt.Fprintf(buf, "\t\tif next, err := bridge.ExpandTypeAliases(__able_runtime, targetType); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\treturn\n")
	fmt.Fprintf(buf, "\t\t} else if next != nil {\n")
	fmt.Fprintf(buf, "\t\t\texpanded = next\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvariants, unionSigs := __able_expand_union_targets(expanded)\n")
	fmt.Fprintf(buf, "\tif len(variants) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tisConcrete := !__able_type_expr_uses_generics(expanded, genericSet)\n")
	fmt.Fprintf(buf, "\ttargetScore := __able_template_specificity(expanded, genericSet)\n")
	fmt.Fprintf(buf, "\tconstraintKeys := __able_constraint_key_set(constraints)\n")
	fmt.Fprintf(buf, "\tfor _, variant := range variants {\n")
	fmt.Fprintf(buf, "\t\tperIface[methodName] = append(perIface[methodName], __able_interface_dispatch_entry{\n")
	fmt.Fprintf(buf, "\t\t\ttargetType:     variant,\n")
	fmt.Fprintf(buf, "\t\t\tinterfaceArgs:  ifaceArgs,\n")
	fmt.Fprintf(buf, "\t\t\tgenericNames:   genericSet,\n")
	fmt.Fprintf(buf, "\t\t\tconstraints:    constraints,\n")
	fmt.Fprintf(buf, "\t\t\tconstraintKeys: constraintKeys,\n")
	fmt.Fprintf(buf, "\t\t\tunionVariants:  unionSigs,\n")
	fmt.Fprintf(buf, "\t\t\ttargetScore:    targetScore,\n")
	fmt.Fprintf(buf, "\t\t\tisConcrete:     isConcrete,\n")
	fmt.Fprintf(buf, "\t\t\tfn:             fn,\n")
	fmt.Fprintf(buf, "\t\t\tisPrivate:      isPrivate,\n")
	fmt.Fprintf(buf, "\t\t\tisBuiltin:      isBuiltin,\n")
	fmt.Fprintf(buf, "\t\t})\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_interface_search(ifaceName string) []string {\n")
	fmt.Fprintf(buf, "\tif ifaceName == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_interface_search_names != nil {\n")
	fmt.Fprintf(buf, "\t\tif names, ok := __able_interface_search_names[ifaceName]; ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn names\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn []string{ifaceName}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_interface_dispatch_has_entries(ifaceName string, methodName string) bool {\n")
	fmt.Fprintf(buf, "\tif ifaceName == \"\" || methodName == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_interface_dispatch == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif perIface := __able_interface_dispatch[ifaceName]; perIface != nil {\n")
	fmt.Fprintf(buf, "\t\tif len(perIface[methodName]) > 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tnames := __able_interface_search(ifaceName)\n")
	fmt.Fprintf(buf, "\tif len(names) > 1 {\n")
	fmt.Fprintf(buf, "\t\tfor _, base := range names[1:] {\n")
	fmt.Fprintf(buf, "\t\t\tif perIface := __able_interface_dispatch[base]; perIface != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tif len(perIface[methodName]) > 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn true\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn false\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_interface_dispatch_method(val *runtime.InterfaceValue, name string) (runtime.Value, bool) {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil || val == nil || name == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val.Methods != nil {\n")
	fmt.Fprintf(buf, "\t\tif cached, ok := val.Methods[name]; ok && cached != nil {\n")
	fmt.Fprintf(buf, "\t\t\tbound := __able_interface_bind_method(val, cached)\n")
	fmt.Fprintf(buf, "\t\t\tif bound != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tval.Methods[name] = bound\n")
	fmt.Fprintf(buf, "\t\t\t\treturn bound, true\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tifaceName := \"\"\n")
	fmt.Fprintf(buf, "\tif val.Interface != nil && val.Interface.Node != nil && val.Interface.Node.ID != nil {\n")
	fmt.Fprintf(buf, "\t\tifaceName = val.Interface.Node.ID.Name\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif ifaceName == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvar entries []__able_interface_dispatch_entry\n")
	fmt.Fprintf(buf, "\tif perIface := __able_interface_dispatch[ifaceName]; perIface != nil {\n")
	fmt.Fprintf(buf, "\t\tentries = perIface[name]\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(entries) == 0 {\n")
	fmt.Fprintf(buf, "\t\tnames := __able_interface_search(ifaceName)\n")
	fmt.Fprintf(buf, "\t\tif len(names) > 1 {\n")
	fmt.Fprintf(buf, "\t\t\tfor _, base := range names[1:] {\n")
	fmt.Fprintf(buf, "\t\t\t\tif perIface := __able_interface_dispatch[base]; perIface != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tentries = append(entries, perIface[name]...)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(entries) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treceiver := __able_unwrap_interface(val.Underlying)\n")
	fmt.Fprintf(buf, "\tif receiver == nil {\n")
	fmt.Fprintf(buf, "\t\treceiver = runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tmatches := make([]__able_interface_dispatch_match, 0, 1)\n")
	fmt.Fprintf(buf, "\tfor _, entry := range entries {\n")
	fmt.Fprintf(buf, "\t\tif len(entry.genericNames) > 0 {\n")
	fmt.Fprintf(buf, "\t\t\tactual, err := bridge.TypeExpressionFromValue(__able_runtime, receiver)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif actual == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\ttemplate, err := bridge.ExpandTypeAliases(__able_runtime, entry.targetType)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tactual, err = bridge.ExpandTypeAliases(__able_runtime, actual)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tbindings := make(map[string]ast.TypeExpression)\n")
	fmt.Fprintf(buf, "\t\t\tif !__able_match_type_template(template, actual, entry.genericNames, bindings) {\n")
	fmt.Fprintf(buf, "\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif len(val.InterfaceArgs) > 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\tif len(entry.interfaceArgs) == 0 || len(entry.interfaceArgs) != len(val.InterfaceArgs) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tifaceOk := true\n")
	fmt.Fprintf(buf, "\t\t\t\tfor idx := range entry.interfaceArgs {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tleft, err := bridge.ExpandTypeAliases(__able_runtime, entry.interfaceArgs[idx])\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tright, err := bridge.ExpandTypeAliases(__able_runtime, val.InterfaceArgs[idx])\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif !__able_match_type_template(left, right, entry.genericNames, bindings) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tifaceOk = false\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif !ifaceOk {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif !__able_enforce_constraints(entry.constraints, bindings) {\n")
	fmt.Fprintf(buf, "\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tmatches = append(matches, __able_interface_dispatch_match{entry: entry, receiver: receiver})\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif len(val.InterfaceArgs) > 0 {\n")
	fmt.Fprintf(buf, "\t\t\tif len(entry.interfaceArgs) == 0 || !__able_type_expr_list_equal(entry.interfaceArgs, val.InterfaceArgs) {\n")
	fmt.Fprintf(buf, "\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tcoerced, ok, err := bridge.MatchType(__able_runtime, entry.targetType, receiver)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !__able_enforce_constraints(entry.constraints, nil) {\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tmatches = append(matches, __able_interface_dispatch_match{entry: entry, receiver: coerced})\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(matches) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbestIdx := 0\n")
	fmt.Fprintf(buf, "\tcontenders := []int{0}\n")
	fmt.Fprintf(buf, "\tfor idx := 1; idx < len(matches); idx++ {\n")
	fmt.Fprintf(buf, "\t\tcmp := __able_compare_interface_entries(matches[idx].entry, matches[bestIdx].entry)\n")
	fmt.Fprintf(buf, "\t\tif cmp > 0 {\n")
	fmt.Fprintf(buf, "\t\t\tbestIdx = idx\n")
	fmt.Fprintf(buf, "\t\t\tcontenders = []int{idx}\n")
	fmt.Fprintf(buf, "\t\t} else if cmp == 0 {\n")
	fmt.Fprintf(buf, "\t\t\treverse := __able_compare_interface_entries(matches[bestIdx].entry, matches[idx].entry)\n")
	fmt.Fprintf(buf, "\t\t\tif reverse < 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\tbestIdx = idx\n")
	fmt.Fprintf(buf, "\t\t\t\tcontenders = []int{idx}\n")
	fmt.Fprintf(buf, "\t\t\t} else if reverse == 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\tcontenders = append(contenders, idx)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(contenders) > 1 {\n")
	fmt.Fprintf(buf, "\t\t__able_panic_on_error(fmt.Errorf(\"ambiguous implementations of %%s\", ifaceName))\n")
	fmt.Fprintf(buf, "\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tmatch := matches[bestIdx]\n")
	fmt.Fprintf(buf, "\tif match.entry.isPrivate {\n")
	fmt.Fprintf(buf, "\t\t__able_panic_on_error(fmt.Errorf(\"Method '%%s' on %%s is private\", name, ifaceName))\n")
	fmt.Fprintf(buf, "\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbound := &runtime.NativeBoundMethodValue{Receiver: match.receiver, Method: *match.entry.fn}\n")
	fmt.Fprintf(buf, "\tif val.Methods == nil {\n")
	fmt.Fprintf(buf, "\t\tval.Methods = map[string]runtime.Value{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval.Methods[name] = bound\n")
	fmt.Fprintf(buf, "\treturn bound, true\n")
	fmt.Fprintf(buf, "}\n\n")
}
