package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderRuntimeCallHelpers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "func __able_try_member_set(obj runtime.Value, member runtime.Value, value runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, fmt.Errorf(\"compiler: missing runtime\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbase := __able_unwrap_interface(obj)\n")
	fmt.Fprintf(buf, "\tif name, ok := __able_member_name(member); ok {\n")
	fmt.Fprintf(buf, "\t\tif arr, ok, _ := __able_runtime_array_value(base); ok {\n")
	fmt.Fprintf(buf, "\t\t\tswitch name {\n")
	fmt.Fprintf(buf, "\t\t\tcase \"storage_handle\":\n")
	fmt.Fprintf(buf, "\t\t\t\thandle, err := __able_array_handle_from_value(value)\n")
	fmt.Fprintf(buf, "\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif handle <= 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.NilValue{}, fmt.Errorf(\"array storage_handle must be positive\")\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tstate, err := runtime.ArrayStoreEnsureHandle(handle, 0, 0)\n")
	fmt.Fprintf(buf, "\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tarr.Handle = handle\n")
	fmt.Fprintf(buf, "\t\t\t\tarr.Elements = state.Values\n")
	fmt.Fprintf(buf, "\t\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\t\tcase \"length\":\n")
	fmt.Fprintf(buf, "\t\t\t\tlength, err := __able_array_index_from_value(value)\n")
	fmt.Fprintf(buf, "\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.NilValue{}, fmt.Errorf(\"array length must be a non-negative integer\")\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif arr.Handle != 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err := runtime.ArrayStoreSetLength(arr.Handle, length); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif length < 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif length <= len(arr.Elements) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tarr.Elements = arr.Elements[:length]\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tfor len(arr.Elements) < length {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tarr.Elements = append(arr.Elements, runtime.NilValue{})\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\t\tcase \"capacity\":\n")
	fmt.Fprintf(buf, "\t\t\t\tcapacity, err := __able_array_index_from_value(value)\n")
	fmt.Fprintf(buf, "\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.NilValue{}, fmt.Errorf(\"array capacity must be a non-negative integer\")\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif arr.Handle != 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err := runtime.ArrayStoreReserve(arr.Handle, capacity); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif capacity < len(arr.Elements) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcapacity = len(arr.Elements)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif cap(arr.Elements) < capacity {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tnewValues := make([]runtime.Value, len(arr.Elements), capacity)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcopy(newValues, arr.Elements)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tarr.Elements = newValues\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif inst := __able_struct_instance(base); inst != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil && inst.Definition.Node.ID.Name == \"Array\" {\n")
	fmt.Fprintf(buf, "\t\t\t\tswitch name {\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"storage_handle\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\thandle, err := __able_array_handle_from_value(value)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif handle <= 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, fmt.Errorf(\"array storage_handle must be positive\")\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t_, err = runtime.ArrayStoreEnsureHandle(handle, 0, 0)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif inst.Fields == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tinst.Fields = map[string]runtime.Value{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tinst.Fields[\"storage_handle\"] = value\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"length\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\tlength, err := __able_array_index_from_value(value)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, fmt.Errorf(\"array length must be a non-negative integer\")\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif handleVal, ok := inst.Fields[\"storage_handle\"]; ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\thandle, err := __able_array_handle_from_value(handleVal)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif err := runtime.ArrayStoreSetLength(handle, length); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif inst.Fields == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tinst.Fields = map[string]runtime.Value{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tinst.Fields[\"length\"] = bridge.ToInt(int64(length), runtime.IntegerI32)\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"capacity\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcapacity, err := __able_array_index_from_value(value)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, fmt.Errorf(\"array capacity must be a non-negative integer\")\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif handleVal, ok := inst.Fields[\"storage_handle\"]; ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\thandle, err := __able_array_handle_from_value(handleVal)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif err := runtime.ArrayStoreReserve(handle, capacity); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif inst.Fields == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tinst.Fields = map[string]runtime.Value{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tinst.Fields[\"capacity\"] = bridge.ToInt(int64(capacity), runtime.IntegerI32)\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil && inst.Definition.Node.ID.Name == \"HashMap\" {\n")
	fmt.Fprintf(buf, "\t\t\t\tswitch name {\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"handle\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\thandle, err := __able_hash_map_handle_from_value(value)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif handle <= 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, fmt.Errorf(\"hash map handle must be positive\")\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t_, err = runtime.HashMapStoreEnsureHandle(handle, 0)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif inst.Fields == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tinst.Fields = map[string]runtime.Value{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tinst.Fields[\"handle\"] = value\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := bridge.MemberAssign(__able_runtime, obj, member, value)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_member_set(obj runtime.Value, member runtime.Value, value runtime.Value) (runtime.Value, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tval, err := __able_try_member_set(obj, member, value)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_try_member_get(obj runtime.Value, member runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, fmt.Errorf(\"compiler: missing runtime\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbase := __able_unwrap_interface(obj)\n")
	fmt.Fprintf(buf, "\tif name, ok := __able_member_name(member); ok {\n")
	fmt.Fprintf(buf, "\t\tif arr, ok, _ := __able_runtime_array_value(base); ok {\n")
	fmt.Fprintf(buf, "\t\t\tswitch name {\n")
	fmt.Fprintf(buf, "\t\t\tcase \"storage_handle\":\n")
	fmt.Fprintf(buf, "\t\t\t\treturn bridge.ToInt(arr.Handle, runtime.IntegerI64), nil\n")
	fmt.Fprintf(buf, "\t\t\tcase \"length\":\n")
	fmt.Fprintf(buf, "\t\t\t\tlength := len(arr.Elements)\n")
	fmt.Fprintf(buf, "\t\t\t\tif arr.Handle != 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tvalue, err := runtime.ArrayStoreSize(arr.Handle)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tlength = value\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\treturn bridge.ToInt(int64(length), runtime.IntegerI32), nil\n")
	fmt.Fprintf(buf, "\t\t\tcase \"capacity\":\n")
	fmt.Fprintf(buf, "\t\t\t\tcapacity := cap(arr.Elements)\n")
	fmt.Fprintf(buf, "\t\t\t\tif arr.Handle != 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tvalue, err := runtime.ArrayStoreCapacity(arr.Handle)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcapacity = value\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\treturn bridge.ToInt(int64(capacity), runtime.IntegerI32), nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif inst := __able_struct_instance(base); inst != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil && inst.Definition.Node.ID.Name == \"Array\" {\n")
	fmt.Fprintf(buf, "\t\t\t\thandleVal, ok := inst.Fields[\"storage_handle\"]\n")
	fmt.Fprintf(buf, "\t\t\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.NilValue{}, fmt.Errorf(\"array value missing storage_handle\")\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\thandle, err := __able_array_handle_from_value(handleVal)\n")
	fmt.Fprintf(buf, "\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tswitch name {\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"storage_handle\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn handleVal, nil\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"length\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\tlength, err := runtime.ArrayStoreSize(handle)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tval := bridge.ToInt(int64(length), runtime.IntegerI32)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif inst.Fields == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tinst.Fields = map[string]runtime.Value{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tinst.Fields[\"length\"] = val\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn val, nil\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"capacity\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcapacity, err := runtime.ArrayStoreCapacity(handle)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tval := bridge.ToInt(int64(capacity), runtime.IntegerI32)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif inst.Fields == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tinst.Fields = map[string]runtime.Value{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tinst.Fields[\"capacity\"] = val\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn val, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := bridge.MemberGet(__able_runtime, obj, member)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_member_get(obj runtime.Value, member runtime.Value) (runtime.Value, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tval, err := __able_try_member_get(obj, member)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_try_member_get_method(obj runtime.Value, member runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, fmt.Errorf(\"compiler: missing runtime\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbase := __able_unwrap_interface(obj)\n")
	fmt.Fprintf(buf, "\tif name, ok := __able_member_name(member); ok {\n")
	fmt.Fprintf(buf, "\t\tif iface, ok, nilPtr := __able_callable_interface_value(obj); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\tif ok {\n")
	fmt.Fprintf(buf, "\t\t\t\tif method, ok := __able_interface_dispatch_method(&iface, name); ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn method, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif __able_interface_dispatch_strict {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tifaceName := \"\"\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif iface.Interface != nil && iface.Interface.Node != nil && iface.Interface.Node.ID != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tifaceName = iface.Interface.Node.ID.Name\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif ifaceName != \"\" && __able_interface_dispatch[ifaceName] != nil {\n")
						fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}, fmt.Errorf(\"No matching implementation of %%s.%%s\", ifaceName, name)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t} else {\n")
	fmt.Fprintf(buf, "\t\t\tswitch typed := base.(type) {\n")
	fmt.Fprintf(buf, "\t\t\tcase runtime.PackageValue:\n")
	fmt.Fprintf(buf, "\t\t\t\tif typed.Public != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif val, ok := typed.Public[name]; ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn val, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tswitch typed := base.(type) {\n")
	fmt.Fprintf(buf, "\t\t\tcase runtime.DynPackageValue:\n")
	fmt.Fprintf(buf, "\t\t\t\tpkgName := strings.TrimSpace(typed.Name)\n")
	fmt.Fprintf(buf, "\t\t\t\tif pkgName == \"\" && len(typed.NamePath) > 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tpkgName = strings.Join(typed.NamePath, \".\")\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif pkgName != \"\" && name != \"def\" && name != \"eval\" {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.DynRefValue{Package: pkgName, Name: name}, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif inst := __able_struct_instance(base); inst != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tif inst.Fields != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif val, ok := inst.Fields[name]; ok && __able_is_callable_value(val) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn val, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\ttypeName := inst.Definition.Node.ID.Name\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif entry := __able_lookup_compiled_method(typeName, name, true); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NativeBoundMethodValue{Receiver: inst, Method: *entry.fn}, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tisSingleton := len(inst.Definition.Node.GenericParams) == 0 && (inst.Definition.Node.Kind == ast.StructKindSingleton || (inst.Definition.Node.Kind == ast.StructKindNamed && len(inst.Definition.Node.Fields) == 0))\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif isSingleton {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif entry := __able_lookup_compiled_method(typeName, name, false); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\treturn *entry.fn, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tswitch typed := base.(type) {\n")
	fmt.Fprintf(buf, "\t\t\tcase runtime.ImplementationNamespaceValue:\n")
	fmt.Fprintf(buf, "\t\t\t\tif typed.Methods != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif method, ok := typed.Methods[name]; ok && method != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn method, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif _, ok, nilPtr := __able_runtime_error_value(base); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\t\tif ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif entry := __able_lookup_compiled_method(\"Error\", name, true); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NativeBoundMethodValue{Receiver: base, Method: *entry.fn}, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif typeName := __able_runtime_value_type_name(base); typeName != \"\" {\n")
	fmt.Fprintf(buf, "\t\t\t\tif __able_interface_dispatch_static_receiver(base) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif entry := __able_lookup_compiled_method(typeName, name, false); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn *entry.fn, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t} else {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif entry := __able_lookup_compiled_method(typeName, name, true); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NativeBoundMethodValue{Receiver: base, Method: *entry.fn}, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif method, ok, err := __able_interface_dispatch_member(base, name); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t\t\t} else if ok {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn method, nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif !__able_interface_dispatch_static_receiver(base) {\n")
	fmt.Fprintf(buf, "\t\t\t\treceiverTypeName := __able_runtime_value_type_name(base)\n")
	fmt.Fprintf(buf, "\t\t\t\tif receiverTypeName != \"\" && __able_compiled_ufcs_target_exists(name, receiverTypeName) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif env := __able_runtime.Env(); env != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif scoped, err := env.Get(name); err == nil && __able_is_callable_value(scoped) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\treturn runtime.PartialFunctionValue{Target: scoped, BoundArgs: []runtime.Value{base}}, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := bridge.MemberGetPreferMethods(__able_runtime, obj, member)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_member_get_method(obj runtime.Value, member runtime.Value) (runtime.Value, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tval, err := __able_try_member_get_method(obj, member)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_member(obj runtime.Value, member runtime.Value) (runtime.Value, *__ableControl) {\n")
	fmt.Fprintf(buf, "\treturn __able_member_get_method(obj, member)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_method_call(obj runtime.Value, methodName string, args []runtime.Value) (runtime.Value, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tmethod, err := __able_try_member_get_method(obj, runtime.StringValue{Val: methodName})\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := __able_call_value_fast(method, args)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_method_call_node(obj runtime.Value, methodName string, args []runtime.Value, call *ast.FunctionCall) (runtime.Value, *__ableControl) {\n")
	fmt.Fprintf(buf, "\t__able_pushed_call_frame := false\n")
	fmt.Fprintf(buf, "\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\tbridge.PushCallFrame(__able_runtime, call)\n")
	fmt.Fprintf(buf, "\t\t__able_pushed_call_frame = true\n")
	fmt.Fprintf(buf, "\t\tdefer func() {\n")
	fmt.Fprintf(buf, "\t\t\tif __able_pushed_call_frame {\n")
	fmt.Fprintf(buf, "\t\t\t\tbridge.PopCallFrame(__able_runtime)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}()\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tmethod, err := __able_try_member_get_method(obj, runtime.StringValue{Val: methodName})\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\tif __able_pushed_call_frame && __able_is_caller_frame_error(err) {\n")
	fmt.Fprintf(buf, "\t\t\tbridge.PopCallFrame(__able_runtime)\n")
	fmt.Fprintf(buf, "\t\t\t__able_pushed_call_frame = false\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error_with_node(call, err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := __able_call_value_fast(method, args)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\tif __able_pushed_call_frame && __able_is_caller_frame_error(err) {\n")
	fmt.Fprintf(buf, "\t\t\tbridge.PopCallFrame(__able_runtime)\n")
	fmt.Fprintf(buf, "\t\t\t__able_pushed_call_frame = false\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error_with_node(call, err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_compiled_thunk_value(bytecode any) (interpreter.CompiledThunk, bool, bool) {\n")
	fmt.Fprintf(buf, "\tif thunk, ok := bytecode.(interpreter.CompiledThunk); ok {\n")
	fmt.Fprintf(buf, "\t\tif thunk == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn thunk, true, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif thunk, ok := bytecode.(func(*runtime.Environment, []runtime.Value) (runtime.Value, error)); ok {\n")
	fmt.Fprintf(buf, "\t\tif thunk == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn interpreter.CompiledThunk(thunk), true, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil, false, false\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_call_compiled_thunk(bytecode any, env *runtime.Environment, args []runtime.Value) (runtime.Value, error, bool) {\n")
	fmt.Fprintf(buf, "\tthunk, ok, nilPtr := __able_compiled_thunk_value(bytecode)\n")
	fmt.Fprintf(buf, "\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\treturn nil, nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := thunk(env, args)\n")
	fmt.Fprintf(buf, "\treturn val, err, true\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_function_call_env(fn *runtime.FunctionValue) *runtime.Environment {\n")
	fmt.Fprintf(buf, "\tif fn != nil && fn.Closure != nil {\n")
	fmt.Fprintf(buf, "\t\treturn fn.Closure\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_runtime != nil {\n")
	fmt.Fprintf(buf, "\t\treturn __able_runtime.Env()\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_call_native_function(fn runtime.NativeFunctionValue, partialTarget runtime.Value, providedArgs []runtime.Value, invokeArgs []runtime.Value, call *ast.FunctionCall, ctx *runtime.NativeCallContext) (runtime.Value, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif fn.Arity >= 0 {\n")
	fmt.Fprintf(buf, "\t\tif len(providedArgs) > fn.Arity {\n")
	fmt.Fprintf(buf, "\t\t\tname := fn.Name\n")
	fmt.Fprintf(buf, "\t\t\tif name == \"\" {\n")
	fmt.Fprintf(buf, "\t\t\t\tname = \"(native)\"\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\terr := fmt.Errorf(\"Arity mismatch calling %%s: expected %%d, got %%d\", name, fn.Arity, len(providedArgs))\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_runtime_error_control(call, err)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif len(providedArgs) < fn.Arity {\n")
	fmt.Fprintf(buf, "\t\t\targsCopy := append([]runtime.Value{}, providedArgs...)\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.PartialFunctionValue{Target: partialTarget, BoundArgs: argsCopy, Call: call}, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := fn.Impl(ctx, invokeArgs)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error_with_node(call, err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_callable_native_function_value(val runtime.Value) (runtime.NativeFunctionValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := val.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.NativeFunctionValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tcase *runtime.NativeFunctionValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NativeFunctionValue{}, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn *typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NativeFunctionValue{}, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_callable_native_bound_method_value(val runtime.Value) (runtime.NativeBoundMethodValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := val.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.NativeBoundMethodValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tcase *runtime.NativeBoundMethodValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NativeBoundMethodValue{}, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn *typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NativeBoundMethodValue{}, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_callable_function_value(val runtime.Value) (*runtime.FunctionValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := val.(type) {\n")
	fmt.Fprintf(buf, "\tcase *runtime.FunctionValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_callable_function_overload_value(val runtime.Value) (*runtime.FunctionOverloadValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := val.(type) {\n")
	fmt.Fprintf(buf, "\tcase *runtime.FunctionOverloadValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_callable_bound_method_value(val runtime.Value) (runtime.BoundMethodValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := val.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.BoundMethodValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tcase *runtime.BoundMethodValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.BoundMethodValue{}, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn *typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.BoundMethodValue{}, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_callable_interface_value(val runtime.Value) (runtime.InterfaceValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := val.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.InterfaceValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tcase *runtime.InterfaceValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.InterfaceValue{}, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn *typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.InterfaceValue{}, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_callable_partial_value(val runtime.Value) (runtime.PartialFunctionValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := val.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.PartialFunctionValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tcase *runtime.PartialFunctionValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.PartialFunctionValue{}, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn *typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.PartialFunctionValue{}, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_merge_bound_args(bound []runtime.Value, args []runtime.Value) []runtime.Value {\n")
	fmt.Fprintf(buf, "\tmerged := make([]runtime.Value, 0, len(bound)+len(args))\n")
	fmt.Fprintf(buf, "\tmerged = append(merged, bound...)\n")
	fmt.Fprintf(buf, "\tmerged = append(merged, args...)\n")
	fmt.Fprintf(buf, "\treturn merged\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_optional_last_param(params []*ast.FunctionParameter) bool {\n")
	fmt.Fprintf(buf, "\tif len(params) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tlast := params[len(params)-1]\n")
	fmt.Fprintf(buf, "\tif last == nil || last.ParamType == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t_, ok := last.ParamType.(*ast.NullableTypeExpression)\n")
	fmt.Fprintf(buf, "\treturn ok\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_overload_arity_matches(expected int, actual int, optionalLast bool) bool {\n")
	fmt.Fprintf(buf, "\treturn actual == expected || (optionalLast && actual == expected-1)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_overload_name(call *ast.FunctionCall) string {\n")
	fmt.Fprintf(buf, "\tif call == nil {\n")
	fmt.Fprintf(buf, "\t\treturn \"(function)\"\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch callee := call.Callee.(type) {\n")
	fmt.Fprintf(buf, "\tcase *ast.Identifier:\n")
	fmt.Fprintf(buf, "\t\treturn callee.Name\n")
	fmt.Fprintf(buf, "\tcase *ast.MemberAccessExpression:\n")
	fmt.Fprintf(buf, "\t\tif id, ok := callee.Member.(*ast.Identifier); ok && id != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn id.Name\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn \"(function)\"\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_function_generic_name_set(fn *runtime.FunctionValue, declGenerics []*ast.GenericParameter) map[string]struct{} {\n")
	fmt.Fprintf(buf, "\tset := map[string]struct{}{}\n")
	fmt.Fprintf(buf, "\tadd := func(params []*ast.GenericParameter) {\n")
	fmt.Fprintf(buf, "\t\tfor _, gp := range params {\n")
	fmt.Fprintf(buf, "\t\t\tif gp == nil || gp.Name == nil || gp.Name.Name == \"\" {\n")
	fmt.Fprintf(buf, "\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tset[gp.Name.Name] = struct{}{}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tadd(declGenerics)\n")
	fmt.Fprintf(buf, "\tif fn != nil && fn.MethodSet != nil {\n")
	fmt.Fprintf(buf, "\t\tadd(fn.MethodSet.GenericParams)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(set) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn set\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_min_args_for_function_overload(fn *runtime.FunctionValue) int {\n")
	fmt.Fprintf(buf, "\tif fn == nil || fn.Declaration == nil {\n")
	fmt.Fprintf(buf, "\t\treturn 0\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch decl := fn.Declaration.(type) {\n")
	fmt.Fprintf(buf, "\tcase *ast.FunctionDefinition:\n")
	fmt.Fprintf(buf, "\t\texpected := len(decl.Params)\n")
	fmt.Fprintf(buf, "\t\tif decl.IsMethodShorthand {\n")
	fmt.Fprintf(buf, "\t\t\texpected++\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif __able_optional_last_param(decl.Params) {\n")
	fmt.Fprintf(buf, "\t\t\texpected--\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif expected < 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn expected\n")
	fmt.Fprintf(buf, "\tcase *ast.LambdaExpression:\n")
	fmt.Fprintf(buf, "\t\texpected := len(decl.Params)\n")
	fmt.Fprintf(buf, "\t\tif __able_optional_last_param(decl.Params) {\n")
	fmt.Fprintf(buf, "\t\t\texpected--\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif expected < 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn expected\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn 0\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_min_args_for_overload_set(overloads []*runtime.FunctionValue) int {\n")
	fmt.Fprintf(buf, "\tmin := -1\n")
	fmt.Fprintf(buf, "\tfor _, fn := range overloads {\n")
	fmt.Fprintf(buf, "\t\tif fn == nil {\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treq := __able_min_args_for_function_overload(fn)\n")
	fmt.Fprintf(buf, "\t\tif min < 0 || req < min {\n")
	fmt.Fprintf(buf, "\t\t\tmin = req\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif min < 0 {\n")
	fmt.Fprintf(buf, "\t\treturn 0\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn min\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_overload_candidate struct {\n")
	fmt.Fprintf(buf, "\tfn       *runtime.FunctionValue\n")
	fmt.Fprintf(buf, "\tscore    float64\n")
	fmt.Fprintf(buf, "\tpriority float64\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_select_function_overload(overloads []*runtime.FunctionValue, args []runtime.Value, call *ast.FunctionCall) (*runtime.FunctionValue, error) {\n")
	fmt.Fprintf(buf, "\tcandidates := make([]__able_overload_candidate, 0, len(overloads))\n")
	fmt.Fprintf(buf, "\tfor _, fn := range overloads {\n")
	fmt.Fprintf(buf, "\t\tif fn == nil || fn.Declaration == nil {\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tswitch decl := fn.Declaration.(type) {\n")
	fmt.Fprintf(buf, "\t\tcase *ast.FunctionDefinition:\n")
	fmt.Fprintf(buf, "\t\t\tparams := decl.Params\n")
	fmt.Fprintf(buf, "\t\t\toptionalLast := __able_optional_last_param(params)\n")
	fmt.Fprintf(buf, "\t\t\texpectedArgs := len(params)\n")
	fmt.Fprintf(buf, "\t\t\tif decl.IsMethodShorthand {\n")
	fmt.Fprintf(buf, "\t\t\t\texpectedArgs++\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif !__able_overload_arity_matches(expectedArgs, len(args), optionalLast) {\n")
	fmt.Fprintf(buf, "\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tparamsForCheck := params\n")
	fmt.Fprintf(buf, "\t\t\targsForCheck := args\n")
	fmt.Fprintf(buf, "\t\t\tif optionalLast && len(args) == expectedArgs-1 && len(paramsForCheck) > 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\tparamsForCheck = paramsForCheck[:len(paramsForCheck)-1]\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif decl.IsMethodShorthand && len(argsForCheck) > 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\targsForCheck = argsForCheck[1:]\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif len(argsForCheck) != len(paramsForCheck) {\n")
	fmt.Fprintf(buf, "\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tgenerics := __able_function_generic_name_set(fn, decl.GenericParams)\n")
	fmt.Fprintf(buf, "\t\t\tscore := 0.0\n")
	fmt.Fprintf(buf, "\t\t\tif optionalLast && len(args) == expectedArgs-1 {\n")
	fmt.Fprintf(buf, "\t\t\t\tscore -= 0.5\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tcompatible := true\n")
	fmt.Fprintf(buf, "\t\t\tfor idx, param := range paramsForCheck {\n")
	fmt.Fprintf(buf, "\t\t\t\tif param == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcompatible = false\n")
	fmt.Fprintf(buf, "\t\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif param.ParamType == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif __able_type_expr_uses_generics(param.ParamType, generics) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif _, ok, err := bridge.MatchType(__able_runtime, param.ParamType, argsForCheck[idx]); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t\t\t\t} else if !ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcompatible = false\n")
	fmt.Fprintf(buf, "\t\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tscore += float64(__able_template_specificity(param.ParamType, generics))\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif compatible {\n")
	fmt.Fprintf(buf, "\t\t\t\tcandidates = append(candidates, __able_overload_candidate{fn: fn, score: score, priority: fn.MethodPriority})\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\tcase *ast.LambdaExpression:\n")
	fmt.Fprintf(buf, "\t\t\tparams := decl.Params\n")
	fmt.Fprintf(buf, "\t\t\toptionalLast := __able_optional_last_param(params)\n")
	fmt.Fprintf(buf, "\t\t\texpectedArgs := len(params)\n")
	fmt.Fprintf(buf, "\t\t\tif !__able_overload_arity_matches(expectedArgs, len(args), optionalLast) {\n")
	fmt.Fprintf(buf, "\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tparamsForCheck := params\n")
	fmt.Fprintf(buf, "\t\t\targsForCheck := args\n")
	fmt.Fprintf(buf, "\t\t\tif optionalLast && len(args) == expectedArgs-1 && len(paramsForCheck) > 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\tparamsForCheck = paramsForCheck[:len(paramsForCheck)-1]\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif len(argsForCheck) != len(paramsForCheck) {\n")
	fmt.Fprintf(buf, "\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tgenerics := __able_function_generic_name_set(fn, decl.GenericParams)\n")
	fmt.Fprintf(buf, "\t\t\tscore := 0.0\n")
	fmt.Fprintf(buf, "\t\t\tif optionalLast && len(args) == expectedArgs-1 {\n")
	fmt.Fprintf(buf, "\t\t\t\tscore -= 0.5\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tcompatible := true\n")
	fmt.Fprintf(buf, "\t\t\tfor idx, param := range paramsForCheck {\n")
	fmt.Fprintf(buf, "\t\t\t\tif param == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcompatible = false\n")
	fmt.Fprintf(buf, "\t\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif param.ParamType == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif __able_type_expr_uses_generics(param.ParamType, generics) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif _, ok, err := bridge.MatchType(__able_runtime, param.ParamType, argsForCheck[idx]); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t\t\t\t} else if !ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcompatible = false\n")
	fmt.Fprintf(buf, "\t\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tscore += float64(__able_template_specificity(param.ParamType, generics))\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif compatible {\n")
	fmt.Fprintf(buf, "\t\t\t\tcandidates = append(candidates, __able_overload_candidate{fn: fn, score: score, priority: fn.MethodPriority})\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\tcandidates = append(candidates, __able_overload_candidate{fn: fn, score: 0, priority: fn.MethodPriority})\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(candidates) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbest := candidates[0]\n")
	fmt.Fprintf(buf, "\tties := []__able_overload_candidate{best}\n")
	fmt.Fprintf(buf, "\tfor _, cand := range candidates[1:] {\n")
	fmt.Fprintf(buf, "\t\tif cand.score > best.score || (cand.score == best.score && cand.priority > best.priority) {\n")
	fmt.Fprintf(buf, "\t\t\tbest = cand\n")
	fmt.Fprintf(buf, "\t\t\tties = []__able_overload_candidate{cand}\n")
	fmt.Fprintf(buf, "\t\t} else if cand.score == best.score && cand.priority == best.priority {\n")
	fmt.Fprintf(buf, "\t\t\tties = append(ties, cand)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(ties) > 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"Ambiguous overload for %%s\", __able_overload_name(call))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn best.fn, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_call_function_overload(value runtime.Value, args []runtime.Value, call *ast.FunctionCall) (runtime.Value, *__ableControl, bool) {\n")
	fmt.Fprintf(buf, "\toverload, ok, nilPtr := __able_callable_function_overload_value(value)\n")
	fmt.Fprintf(buf, "\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\treturn nil, nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(args) < __able_min_args_for_overload_set(overload.Overloads) {\n")
	fmt.Fprintf(buf, "\t\targsCopy := append([]runtime.Value{}, args...)\n")
	fmt.Fprintf(buf, "\t\treturn runtime.PartialFunctionValue{Target: value, BoundArgs: argsCopy, Call: call}, nil, true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tselected, err := __able_select_function_overload(overload.Overloads, args, call)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_runtime_error_control(call, err), true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif selected == nil {\n")
	fmt.Fprintf(buf, "\t\terr := fmt.Errorf(\"No overloads of %%s match provided arguments\", __able_overload_name(call))\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_runtime_error_control(call, err), true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val, control, handled := __able_call_function_thunk(selected, args, call); handled {\n")
	fmt.Fprintf(buf, "\t\treturn val, control, true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil, nil, false\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_call_native_function_value(value runtime.Value, args []runtime.Value, call *ast.FunctionCall, ctx *runtime.NativeCallContext) (runtime.Value, *__ableControl, bool) {\n")
	fmt.Fprintf(buf, "\tpartialTarget := value\n")
	fmt.Fprintf(buf, "\tnative, ok, nilPtr := __able_callable_native_function_value(value)\n")
	fmt.Fprintf(buf, "\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\treturn nil, nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, control := __able_call_native_function(native, partialTarget, args, args, call, ctx)\n")
	fmt.Fprintf(buf, "\treturn val, control, true\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_call_native_bound_method(bound runtime.NativeBoundMethodValue, partialTarget runtime.Value, args []runtime.Value, call *ast.FunctionCall, ctx *runtime.NativeCallContext) (runtime.Value, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tinjected := append([]runtime.Value{bound.Receiver}, args...)\n")
	fmt.Fprintf(buf, "\treturn __able_call_native_function(bound.Method, partialTarget, args, injected, call, ctx)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_call_function_thunk(value runtime.Value, args []runtime.Value, call *ast.FunctionCall) (runtime.Value, *__ableControl, bool) {\n")
	fmt.Fprintf(buf, "\tfn, ok, nilPtr := __able_callable_function_value(value)\n")
	fmt.Fprintf(buf, "\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\treturn nil, nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val, err, ok := __able_call_compiled_thunk(fn.Bytecode, __able_function_call_env(fn), args); ok {\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_control_from_error_with_node(call, err), true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, nil, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn val, nil, true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_runtime != nil {\n")
	fmt.Fprintf(buf, "\t\t__able_call_env := __able_function_call_env(fn)\n")
	fmt.Fprintf(buf, "\t\tif __able_prev_env, __able_swapped_env := bridge.SwapEnvIfNeeded(__able_runtime, __able_call_env); true {\n")
	fmt.Fprintf(buf, "\t\t\tif __able_swapped_env {\n")
	fmt.Fprintf(buf, "\t\t\t\tdefer bridge.RestoreEnvIfNeeded(__able_runtime, __able_prev_env, __able_swapped_env)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tval, err := bridge.CallValueWithNode(__able_runtime, fn, args, call)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error_with_node(call, err), true\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, nil, true\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn val, nil, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil, nil, false\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_call_bound_method(bound runtime.BoundMethodValue, partialTarget runtime.Value, args []runtime.Value, call *ast.FunctionCall, ctx *runtime.NativeCallContext) (runtime.Value, *__ableControl, bool) {\n")
	fmt.Fprintf(buf, "\tinjected := append([]runtime.Value{bound.Receiver}, args...)\n")
	fmt.Fprintf(buf, "\tmethod := bound.Method\n")
	fmt.Fprintf(buf, "\tfor {\n")
	fmt.Fprintf(buf, "\t\tif iface, ok, nilPtr := __able_callable_interface_value(method); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn nil, nil, false\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tmethod = iface.Underlying\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbreak\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val, control, handled := __able_call_function_thunk(method, injected, call); handled {\n")
	fmt.Fprintf(buf, "\t\treturn val, control, true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif native, ok, nilPtr := __able_callable_native_function_value(method); ok && !nilPtr {\n")
	fmt.Fprintf(buf, "\t\tval, control := __able_call_native_function(native, partialTarget, args, injected, call, ctx)\n")
	fmt.Fprintf(buf, "\t\treturn val, control, true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val, control, handled := __able_call_function_overload(method, injected, call); handled {\n")
	fmt.Fprintf(buf, "\t\treturn val, control, true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil, nil, false\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_resolve_apply_callable(fn runtime.Value) (runtime.Value, bool, error) {\n")
	fmt.Fprintf(buf, "\treceiver := __able_unwrap_interface(fn)\n")
	fmt.Fprintf(buf, "\tif receiver == nil {\n")
	fmt.Fprintf(buf, "\t\treceiver = runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif method, ok, err := __able_interface_dispatch_member(receiver, \"apply\"); err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, err\n")
	fmt.Fprintf(buf, "\t} else if ok && method != nil {\n")
	fmt.Fprintf(buf, "\t\tif __able_is_callable_value(method) {\n")
	fmt.Fprintf(buf, "\t\t\treturn method, true, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif typeName := __able_runtime_value_type_name(receiver); typeName != \"\" {\n")
	fmt.Fprintf(buf, "\t\tif entry := __able_lookup_compiled_method(typeName, \"apply\", true); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NativeBoundMethodValue{Receiver: receiver, Method: *entry.fn}, true, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_call_value(fn runtime.Value, args []runtime.Value, call *ast.FunctionCall) (runtime.Value, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_runtime_error_control(call, fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfor {\n")
	fmt.Fprintf(buf, "\t\tif iface, ok, nilPtr := __able_callable_interface_value(fn); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\t\tfn = runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tfn = iface.Underlying\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif partial, ok, nilPtr := __able_callable_partial_value(fn); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\t\tfn = runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\targs = __able_merge_bound_args(partial.BoundArgs, args)\n")
	fmt.Fprintf(buf, "\t\t\tfn = partial.Target\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbreak\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_pushed_call_frame := false\n")
	fmt.Fprintf(buf, "\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\tbridge.PushCallFrame(__able_runtime, call)\n")
	fmt.Fprintf(buf, "\t\t__able_pushed_call_frame = true\n")
	fmt.Fprintf(buf, "\t\tdefer func() {\n")
	fmt.Fprintf(buf, "\t\t\tif __able_pushed_call_frame {\n")
	fmt.Fprintf(buf, "\t\t\t\tbridge.PopCallFrame(__able_runtime)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}()\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif fn != nil {\n")
	fmt.Fprintf(buf, "\t\tenv := __able_runtime.Env()\n")
	fmt.Fprintf(buf, "\t\tvar state any\n")
	fmt.Fprintf(buf, "\t\tif env != nil {\n")
	fmt.Fprintf(buf, "\t\t\tstate = env.RuntimeData()\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tctx := &runtime.NativeCallContext{Env: env, State: state}\n")
	fmt.Fprintf(buf, "\t\tif val, control, handled := __able_call_native_function_value(fn, args, call, ctx); handled {\n")
	fmt.Fprintf(buf, "\t\t\treturn val, control\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif nativeBound, ok, _ := __able_callable_native_bound_method_value(fn); ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_call_native_bound_method(nativeBound, fn, args, call, ctx)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif bound, ok, _ := __able_callable_bound_method_value(fn); ok {\n")
	fmt.Fprintf(buf, "\t\t\tif val, control, handled := __able_call_bound_method(bound, fn, args, call, ctx); handled {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn val, control\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif val, control, handled := __able_call_function_thunk(fn, args, call); handled {\n")
	fmt.Fprintf(buf, "\t\t\treturn val, control\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif val, control, handled := __able_call_function_overload(fn, args, call); handled {\n")
	fmt.Fprintf(buf, "\t\t\treturn val, control\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif apply, ok, err := __able_resolve_apply_callable(fn); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif __able_pushed_call_frame && __able_is_caller_frame_error(err) {\n")
	fmt.Fprintf(buf, "\t\t\t\tbridge.PopCallFrame(__able_runtime)\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_pushed_call_frame = false\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_control_from_error_with_node(call, err)\n")
	fmt.Fprintf(buf, "\t\t} else if ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_call_value(apply, args, call)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_boundary_name := __able_callable_name(fn)\n")
	fmt.Fprintf(buf, "\tif !__able_allow_dynamic_bridge {\n")
	fmt.Fprintf(buf, "\t\terr := fmt.Errorf(\"compiler: unresolved static call value %%s\", __able_boundary_name)\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_runtime_error_control(call, err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_mark_boundary_fallback(__able_boundary_name)\n")
	fmt.Fprintf(buf, "\t__able_mark_boundary_explicit(\"call_value\", __able_boundary_name)\n")
	fmt.Fprintf(buf, "\tval, err := bridge.CallValueWithNode(__able_runtime, fn, args, call)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error_with_node(call, err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_compiled_call_entry struct {\n")
	fmt.Fprintf(buf, "\tfn      *runtime.NativeFunctionValue\n")
	fmt.Fprintf(buf, "\tarity   int\n")
	fmt.Fprintf(buf, "\tminArgs int\n")
	fmt.Fprintf(buf, "\tufcsTarget string\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "const __able_allow_dynamic_bridge = %t\n\n", g.hasDynamicFeature)
	fmt.Fprintf(buf, "var __able_compiled_calls map[*runtime.Environment]map[string]*__able_compiled_call_entry\n\n")
	fmt.Fprintf(buf, "var __able_compiled_ufcs_targets map[string]map[string]struct{}\n\n")
	fmt.Fprintf(buf, "var __able_compiled_callable_names map[string]struct{}\n")
	fmt.Fprintf(buf, "var __able_boundary_fallback_count int64\n\n")
	fmt.Fprintf(buf, "var __able_boundary_fallback_mu sync.Mutex\n")
	fmt.Fprintf(buf, "var __able_boundary_fallback_names map[string]int64\n\n")
	fmt.Fprintf(buf, "var __able_boundary_explicit_count int64\n\n")
	fmt.Fprintf(buf, "var __able_boundary_explicit_mu sync.Mutex\n")
	fmt.Fprintf(buf, "var __able_boundary_explicit_names map[string]int64\n\n")
	g.renderRuntimeCallHelpersTail(buf)
}
