package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderRuntimeNumericHelpers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "var __able_ratio_def *runtime.StructDefinitionValue\n")
	fmt.Fprintf(buf, "var __able_ratio_i64_min = big.NewInt(math.MinInt64)\n")
	fmt.Fprintf(buf, "var __able_ratio_i64_max = big.NewInt(math.MaxInt64)\n\n")
	fmt.Fprintf(buf, "type __able_ratio_parts struct {\n")
	fmt.Fprintf(buf, "\tnum *big.Int\n")
	fmt.Fprintf(buf, "\tden *big.Int\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_ratio_struct() *runtime.StructDefinitionValue {\n")
	fmt.Fprintf(buf, "\tif __able_ratio_def != nil {\n")
	fmt.Fprintf(buf, "\t\treturn __able_ratio_def\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_runtime != nil {\n")
	fmt.Fprintf(buf, "\t\tif def, err := __able_runtime.StructDefinition(\"Ratio\"); err == nil && def != nil {\n")
	fmt.Fprintf(buf, "\t\t\t__able_ratio_def = def\n")
	fmt.Fprintf(buf, "\t\t\treturn def\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tnumField := ast.NewStructFieldDefinition(ast.NewSimpleTypeExpression(ast.NewIdentifier(\"i64\")), ast.NewIdentifier(\"num\"))\n")
	fmt.Fprintf(buf, "\tdenField := ast.NewStructFieldDefinition(ast.NewSimpleTypeExpression(ast.NewIdentifier(\"i64\")), ast.NewIdentifier(\"den\"))\n")
	fmt.Fprintf(buf, "\tdefinition := ast.NewStructDefinition(ast.NewIdentifier(\"Ratio\"), []*ast.StructFieldDefinition{numField, denField}, ast.StructKindNamed, nil, nil, false)\n")
	fmt.Fprintf(buf, "\tdef := &runtime.StructDefinitionValue{Node: definition}\n")
	fmt.Fprintf(buf, "\t__able_ratio_def = def\n")
	fmt.Fprintf(buf, "\treturn def\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_ratio_abs(val *big.Int) *big.Int {\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn big.NewInt(0)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn new(big.Int).Abs(val)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_ratio_normalize(num *big.Int, den *big.Int) (__able_ratio_parts, error) {\n")
	fmt.Fprintf(buf, "\tif den == nil || den.Sign() == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn __able_ratio_parts{}, __able_value_error{value: bridge.DivisionByZeroError(__able_runtime)}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tn := runtime.CloneBigInt(num)\n")
	fmt.Fprintf(buf, "\td := runtime.CloneBigInt(den)\n")
	fmt.Fprintf(buf, "\tif d.Sign() < 0 {\n")
	fmt.Fprintf(buf, "\t\tn.Neg(n)\n")
	fmt.Fprintf(buf, "\t\td.Neg(d)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif n.Sign() != 0 {\n")
	fmt.Fprintf(buf, "\t\tgcd := new(big.Int).GCD(nil, nil, __able_ratio_abs(n), __able_ratio_abs(d))\n")
	fmt.Fprintf(buf, "\t\tif gcd.Sign() != 0 {\n")
	fmt.Fprintf(buf, "\t\t\tn.Div(n, gcd)\n")
	fmt.Fprintf(buf, "\t\t\td.Div(d, gcd)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t} else {\n")
	fmt.Fprintf(buf, "\t\td.SetInt64(1)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif n.Cmp(__able_ratio_i64_min) < 0 || n.Cmp(__able_ratio_i64_max) > 0 || d.Cmp(__able_ratio_i64_max) > 0 || d.Sign() <= 0 {\n")
	fmt.Fprintf(buf, "\t\treturn __able_ratio_parts{}, __able_value_error{value: bridge.OverflowError(__able_runtime, \"ratio overflow\")}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn __able_ratio_parts{num: n, den: d}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_ratio_from_float_value(val runtime.FloatValue) (__able_ratio_parts, error) {\n")
	fmt.Fprintf(buf, "\tr := new(big.Rat).SetFloat64(val.Val)\n")
	fmt.Fprintf(buf, "\tif r == nil {\n")
	fmt.Fprintf(buf, "\t\treturn __able_ratio_parts{}, fmt.Errorf(\"cannot convert non-finite float to Ratio\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn __able_ratio_normalize(runtime.CloneBigInt(r.Num()), runtime.CloneBigInt(r.Denom()))\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_ratio_parts_from_struct(val runtime.Value) (__able_ratio_parts, bool, error) {\n")
	fmt.Fprintf(buf, "\tbase := __able_unwrap_interface(val)\n")
	fmt.Fprintf(buf, "\tinst, ok := base.(*runtime.StructInstanceValue)\n")
	fmt.Fprintf(buf, "\tif !ok || inst == nil {\n")
	fmt.Fprintf(buf, "\t\treturn __able_ratio_parts{}, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif inst.Definition == nil || inst.Definition.Node == nil || inst.Definition.Node.ID == nil || inst.Definition.Node.ID.Name != \"Ratio\" {\n")
	fmt.Fprintf(buf, "\t\treturn __able_ratio_parts{}, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tnumVal, ok := inst.Fields[\"num\"].(runtime.IntegerValue)\n")
	fmt.Fprintf(buf, "\tif !ok {\n")
	fmt.Fprintf(buf, "\t\tif ptr, okPtr := inst.Fields[\"num\"].(*runtime.IntegerValue); okPtr && ptr != nil {\n")
	fmt.Fprintf(buf, "\t\t\tnumVal = *ptr\n")
	fmt.Fprintf(buf, "\t\t\tok = true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif !ok {\n")
	fmt.Fprintf(buf, "\t\treturn __able_ratio_parts{}, true, fmt.Errorf(\"ratio value missing num\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tdenVal, ok := inst.Fields[\"den\"].(runtime.IntegerValue)\n")
	fmt.Fprintf(buf, "\tif !ok {\n")
	fmt.Fprintf(buf, "\t\tif ptr, okPtr := inst.Fields[\"den\"].(*runtime.IntegerValue); okPtr && ptr != nil {\n")
	fmt.Fprintf(buf, "\t\t\tdenVal = *ptr\n")
	fmt.Fprintf(buf, "\t\t\tok = true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif !ok {\n")
	fmt.Fprintf(buf, "\t\treturn __able_ratio_parts{}, true, fmt.Errorf(\"ratio value missing den\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvar numBig, denBig *big.Int\n")
	fmt.Fprintf(buf, "\tif n, ok := numVal.ToInt64(); ok {\n")
	fmt.Fprintf(buf, "\t\tnumBig = big.NewInt(n)\n")
	fmt.Fprintf(buf, "\t} else {\n")
	fmt.Fprintf(buf, "\t\tnumBig = runtime.CloneBigInt(numVal.BigInt())\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif n, ok := denVal.ToInt64(); ok {\n")
	fmt.Fprintf(buf, "\t\tdenBig = big.NewInt(n)\n")
	fmt.Fprintf(buf, "\t} else {\n")
	fmt.Fprintf(buf, "\t\tdenBig = runtime.CloneBigInt(denVal.BigInt())\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn __able_ratio_parts{num: numBig, den: denBig}, true, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_ratio_parts_from_numeric(val runtime.Value) (__able_ratio_parts, bool, error) {\n")
	fmt.Fprintf(buf, "\tbase := __able_unwrap_interface(val)\n")
	fmt.Fprintf(buf, "\tswitch v := base.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tvar num *big.Int\n")
	fmt.Fprintf(buf, "\t\tif n, ok := v.ToInt64(); ok {\n")
	fmt.Fprintf(buf, "\t\t\tnum = big.NewInt(n)\n")
	fmt.Fprintf(buf, "\t\t} else {\n")
	fmt.Fprintf(buf, "\t\t\tnum = runtime.CloneBigInt(v.BigInt())\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tparts, err := __able_ratio_normalize(num, big.NewInt(1))\n")
	fmt.Fprintf(buf, "\t\treturn parts, true, err\n")
	fmt.Fprintf(buf, "\tcase *runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tif v == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_ratio_parts{}, true, fmt.Errorf(\"Arithmetic requires numeric operands\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tvar num *big.Int\n")
	fmt.Fprintf(buf, "\t\tif n, ok := v.ToInt64(); ok {\n")
	fmt.Fprintf(buf, "\t\t\tnum = big.NewInt(n)\n")
	fmt.Fprintf(buf, "\t\t} else {\n")
	fmt.Fprintf(buf, "\t\t\tnum = runtime.CloneBigInt(v.BigInt())\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tparts, err := __able_ratio_normalize(num, big.NewInt(1))\n")
	fmt.Fprintf(buf, "\t\treturn parts, true, err\n")
	fmt.Fprintf(buf, "\tcase runtime.FloatValue:\n")
	fmt.Fprintf(buf, "\t\tparts, err := __able_ratio_from_float_value(v)\n")
	fmt.Fprintf(buf, "\t\treturn parts, true, err\n")
	fmt.Fprintf(buf, "\tcase *runtime.FloatValue:\n")
	fmt.Fprintf(buf, "\t\tif v == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_ratio_parts{}, true, fmt.Errorf(\"Arithmetic requires numeric operands\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tparts, err := __able_ratio_from_float_value(*v)\n")
	fmt.Fprintf(buf, "\t\treturn parts, true, err\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn __able_ratio_parts{}, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_ratio_coerce(left runtime.Value, right runtime.Value) (__able_ratio_parts, __able_ratio_parts, bool, error) {\n")
	fmt.Fprintf(buf, "\tleftRatio, leftIsRatio, err := __able_ratio_parts_from_struct(left)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn __able_ratio_parts{}, __able_ratio_parts{}, true, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\trightRatio, rightIsRatio, err := __able_ratio_parts_from_struct(right)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn __able_ratio_parts{}, __able_ratio_parts{}, true, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif !leftIsRatio && !rightIsRatio {\n")
	fmt.Fprintf(buf, "\t\treturn __able_ratio_parts{}, __able_ratio_parts{}, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif !leftIsRatio {\n")
	fmt.Fprintf(buf, "\t\tparts, ok, err := __able_ratio_parts_from_numeric(left)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_ratio_parts{}, __able_ratio_parts{}, true, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_ratio_parts{}, __able_ratio_parts{}, true, fmt.Errorf(\"Arithmetic requires numeric operands\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tleftRatio = parts\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif !rightIsRatio {\n")
	fmt.Fprintf(buf, "\t\tparts, ok, err := __able_ratio_parts_from_numeric(right)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_ratio_parts{}, __able_ratio_parts{}, true, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_ratio_parts{}, __able_ratio_parts{}, true, fmt.Errorf(\"Arithmetic requires numeric operands\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\trightRatio = parts\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn leftRatio, rightRatio, true, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_ratio_compare(op string, cmp int) bool {\n")
	fmt.Fprintf(buf, "\tswitch op {\n")
	fmt.Fprintf(buf, "\tcase \"==\":\n")
	fmt.Fprintf(buf, "\t\treturn cmp == 0\n")
	fmt.Fprintf(buf, "\tcase \"!=\":\n")
	fmt.Fprintf(buf, "\t\treturn cmp != 0\n")
	fmt.Fprintf(buf, "\tcase \"<\":\n")
	fmt.Fprintf(buf, "\t\treturn cmp < 0\n")
	fmt.Fprintf(buf, "\tcase \"<=\":\n")
	fmt.Fprintf(buf, "\t\treturn cmp <= 0\n")
	fmt.Fprintf(buf, "\tcase \">\":\n")
	fmt.Fprintf(buf, "\t\treturn cmp > 0\n")
	fmt.Fprintf(buf, "\tcase \">=\":\n")
	fmt.Fprintf(buf, "\t\treturn cmp >= 0\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_ratio_binary_op(op string, left runtime.Value, right runtime.Value) (runtime.Value, bool, error) {\n")
	fmt.Fprintf(buf, "\tleftRatio, rightRatio, ok, err := __able_ratio_coerce(left, right)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, true, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif !ok {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch op {\n")
	fmt.Fprintf(buf, "\tcase \"+\", \"-\", \"*\", \"/\":\n")
	fmt.Fprintf(buf, "\t\tvar num *big.Int\n")
	fmt.Fprintf(buf, "\t\tvar den *big.Int\n")
	fmt.Fprintf(buf, "\t\tswitch op {\n")
	fmt.Fprintf(buf, "\t\tcase \"+\":\n")
	fmt.Fprintf(buf, "\t\t\tnum = new(big.Int).Add(new(big.Int).Mul(leftRatio.num, rightRatio.den), new(big.Int).Mul(rightRatio.num, leftRatio.den))\n")
	fmt.Fprintf(buf, "\t\t\tden = new(big.Int).Mul(leftRatio.den, rightRatio.den)\n")
	fmt.Fprintf(buf, "\t\tcase \"-\":\n")
	fmt.Fprintf(buf, "\t\t\tnum = new(big.Int).Sub(new(big.Int).Mul(leftRatio.num, rightRatio.den), new(big.Int).Mul(rightRatio.num, leftRatio.den))\n")
	fmt.Fprintf(buf, "\t\t\tden = new(big.Int).Mul(leftRatio.den, rightRatio.den)\n")
	fmt.Fprintf(buf, "\t\tcase \"*\":\n")
	fmt.Fprintf(buf, "\t\t\tnum = new(big.Int).Mul(leftRatio.num, rightRatio.num)\n")
	fmt.Fprintf(buf, "\t\t\tden = new(big.Int).Mul(leftRatio.den, rightRatio.den)\n")
	fmt.Fprintf(buf, "\t\tcase \"/\":\n")
	fmt.Fprintf(buf, "\t\t\tnum = new(big.Int).Mul(leftRatio.num, rightRatio.den)\n")
	fmt.Fprintf(buf, "\t\t\tden = new(big.Int).Mul(leftRatio.den, rightRatio.num)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tnormalized, err := __able_ratio_normalize(num, den)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, true, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tval, err := __able_make_ratio_value(normalized)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, true, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn val, true, nil\n")
	fmt.Fprintf(buf, "\tcase \"==\", \"!=\", \"<\", \"<=\", \">\", \">=\":\n")
	fmt.Fprintf(buf, "\t\tleftCross := new(big.Int).Mul(leftRatio.num, rightRatio.den)\n")
	fmt.Fprintf(buf, "\t\trightCross := new(big.Int).Mul(rightRatio.num, leftRatio.den)\n")
	fmt.Fprintf(buf, "\t\tcmp := leftCross.Cmp(rightCross)\n")
	fmt.Fprintf(buf, "\t\treturn runtime.BoolValue{Val: __able_ratio_compare(op, cmp)}, true, nil\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn nil, true, fmt.Errorf(\"unsupported arithmetic operator %%s\", op)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_make_ratio_value(parts __able_ratio_parts) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tdef := __able_ratio_struct()\n")
	fmt.Fprintf(buf, "\tfields := map[string]runtime.Value{\n")
	fmt.Fprintf(buf, "\t\t\"num\": runtime.NewBigIntValue(parts.num, runtime.IntegerI64),\n")
	fmt.Fprintf(buf, "\t\t\"den\": runtime.NewBigIntValue(parts.den, runtime.IntegerI64),\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn &runtime.StructInstanceValue{Definition: def, Fields: fields}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_ratio_from_float_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_ratio_from_float expects one argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval := __able_unwrap_interface(args[0])\n")
	fmt.Fprintf(buf, "\tswitch v := val.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.FloatValue:\n")
	fmt.Fprintf(buf, "\t\tparts, err := __able_ratio_from_float_value(v)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_make_ratio_value(parts)\n")
	fmt.Fprintf(buf, "\tcase *runtime.FloatValue:\n")
	fmt.Fprintf(buf, "\t\tif v == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"__able_ratio_from_float expects float input\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tparts, err := __able_ratio_from_float_value(*v)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_make_ratio_value(parts)\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_ratio_from_float expects float input\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_f32_bits_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_f32_bits expects one argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval := __able_unwrap_interface(args[0])\n")
	fmt.Fprintf(buf, "\tswitch v := val.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.FloatValue:\n")
	fmt.Fprintf(buf, "\t\tif v.TypeSuffix != runtime.FloatF32 {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"__able_f32_bits expects f32 input\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbits := math.Float32bits(float32(v.Val))\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NewBigIntValue(new(big.Int).SetUint64(uint64(bits)), runtime.IntegerU32), nil\n")
	fmt.Fprintf(buf, "\tcase *runtime.FloatValue:\n")
	fmt.Fprintf(buf, "\t\tif v == nil || v.TypeSuffix != runtime.FloatF32 {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"__able_f32_bits expects f32 input\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbits := math.Float32bits(float32(v.Val))\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NewBigIntValue(new(big.Int).SetUint64(uint64(bits)), runtime.IntegerU32), nil\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_f32_bits expects f32 input\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_f64_bits_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_f64_bits expects one argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval := __able_unwrap_interface(args[0])\n")
	fmt.Fprintf(buf, "\tswitch v := val.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.FloatValue:\n")
	fmt.Fprintf(buf, "\t\tif v.TypeSuffix != runtime.FloatF64 {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"__able_f64_bits expects f64 input\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbits := math.Float64bits(v.Val)\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NewBigIntValue(new(big.Int).SetUint64(bits), runtime.IntegerU64), nil\n")
	fmt.Fprintf(buf, "\tcase *runtime.FloatValue:\n")
	fmt.Fprintf(buf, "\t\tif v == nil || v.TypeSuffix != runtime.FloatF64 {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"__able_f64_bits expects f64 input\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbits := math.Float64bits(v.Val)\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NewBigIntValue(new(big.Int).SetUint64(bits), runtime.IntegerU64), nil\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_f64_bits expects f64 input\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_expect_u64(value runtime.Value) (uint64, error) {\n")
	fmt.Fprintf(buf, "\tval := __able_unwrap_interface(value)\n")
	fmt.Fprintf(buf, "\tswitch v := val.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tif v.TypeSuffix != runtime.IntegerU64 {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"__able_u64_mul expects u64 inputs\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif n, ok := v.ToInt64(); ok && n >= 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn uint64(n), nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !v.BigInt().IsUint64() {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"__able_u64_mul expects u64 inputs\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn v.BigInt().Uint64(), nil\n")
	fmt.Fprintf(buf, "\tcase *runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tif v == nil || v.TypeSuffix != runtime.IntegerU64 {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"__able_u64_mul expects u64 inputs\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif n, ok := v.ToInt64(); ok && n >= 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn uint64(n), nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !v.BigInt().IsUint64() {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"__able_u64_mul expects u64 inputs\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn v.BigInt().Uint64(), nil\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn 0, fmt.Errorf(\"__able_u64_mul expects u64 inputs\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_u64_mul_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 2 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_u64_mul expects two arguments\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tlhs, err := __able_expect_u64(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\trhs, err := __able_expect_u64(args[1])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tproduct := lhs * rhs\n")
	fmt.Fprintf(buf, "\treturn runtime.NewBigIntValue(new(big.Int).SetUint64(product), runtime.IntegerU64), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_ratio_from_float(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_ratio_from_float_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_f32_bits(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_f32_bits_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_f64_bits(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_f64_bits_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_u64_mul(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_u64_mul_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
}
