package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderMain() ([]byte, error) {
	if g.opts.PackageName != "main" {
		return nil, fmt.Errorf("compiler: EmitMain requires package name 'main'")
	}
	if g.opts.EntryPath == "" {
		return nil, fmt.Errorf("compiler: EmitMain requires EntryPath")
	}
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "package main\n\n")
	fmt.Fprintf(&buf, "import (\n")
	fmt.Fprintf(&buf, "\t%q\n", "fmt")
	fmt.Fprintf(&buf, "\t%q\n", "os")
	fmt.Fprintf(&buf, "\t%q\n", "path/filepath")
	fmt.Fprintf(&buf, "\t%q\n", "sort")
	fmt.Fprintf(&buf, "\t%q\n", "strings")
	fmt.Fprintf(&buf, "\t%q\n", "able/interpreter-go/pkg/driver")
	fmt.Fprintf(&buf, "\t%q\n", "able/interpreter-go/pkg/interpreter")
	fmt.Fprintf(&buf, "\t%q\n", "able/interpreter-go/pkg/runtime")
	fmt.Fprintf(&buf, "\t%q\n", "able/interpreter-go/pkg/stdlibpath")
	fmt.Fprintf(&buf, ")\n\n")
	fmt.Fprintf(&buf, "func collectSearchPaths(base string) []driver.SearchPath {\n")
	fmt.Fprintf(&buf, "\tseen := make(map[string]struct{})\n")
	fmt.Fprintf(&buf, "\tpaths := make([]driver.SearchPath, 0)\n")
	fmt.Fprintf(&buf, "\tadd := func(path string, kind driver.RootKind, source driver.StdlibSourceClass) {\n")
	fmt.Fprintf(&buf, "\t\tif path == \"\" {\n\t\t\treturn\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tabs, err := filepath.Abs(path)\n\t\tif err != nil {\n\t\t\treturn\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tif kind != driver.RootStdlib && looksLikeStdlibPath(abs) {\n\t\t\tkind = driver.RootStdlib\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tif kind != driver.RootStdlib && looksLikeKernelPath(abs) {\n\t\t\tkind = driver.RootStdlib\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tinfo, err := os.Stat(abs)\n\t\tif err != nil || !info.IsDir() {\n\t\t\treturn\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tif _, ok := seen[abs]; ok {\n\t\t\treturn\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tseen[abs] = struct{}{}\n")
	fmt.Fprintf(&buf, "\t\tpaths = append(paths, driver.SearchPath{Path: abs, Kind: kind, StdlibSource: source})\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tif base != \"\" {\n\t\tadd(base, driver.RootUser, driver.StdlibSourceWorkspace)\n\t}\n")
	fmt.Fprintf(&buf, "\tif cwd, err := os.Getwd(); err == nil {\n\t\tadd(cwd, driver.RootUser, driver.StdlibSourceWorkspace)\n\t}\n")
	fmt.Fprintf(&buf, "\tfor _, part := range splitPathListEnv(os.Getenv(\"ABLE_PATH\")) {\n\t\tadd(part, driver.RootUser, driver.StdlibSourceEnv)\n\t}\n")
	fmt.Fprintf(&buf, "\tfor _, part := range splitPathListEnv(os.Getenv(\"ABLE_MODULE_PATHS\")) {\n\t\tadd(part, driver.RootUser, driver.StdlibSourceEnv)\n\t}\n")
	fmt.Fprintf(&buf, "\tfor _, path := range collectKernelPaths(base) {\n\t\tadd(path, driver.RootStdlib, driver.StdlibSourceUnknown)\n\t}\n")
	fmt.Fprintf(&buf, "\tfor _, path := range collectStdlibPaths(base) {\n\t\tsource := driver.StdlibSourceUnknown\n\t\tif installed := stdlibpath.ResolveInstalledSrc(); installed != \"\" {\n\t\t\tif absInstalled, err := filepath.Abs(installed); err == nil && absInstalled == path {\n\t\t\t\tsource = driver.StdlibSourceCache\n\t\t\t}\n\t\t}\n\t\tadd(path, driver.RootStdlib, source)\n\t}\n")
	fmt.Fprintf(&buf, "\treturn paths\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "func finalizeSearchPaths(searchPaths []driver.SearchPath) ([]driver.SearchPath, error) {\n")
	fmt.Fprintf(&buf, "\treturn driver.ResolveCanonicalStdlibSearchPaths(searchPaths, false)\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "func splitPathListEnv(value string) []string {\n")
	fmt.Fprintf(&buf, "\tif value == \"\" {\n\t\treturn nil\n\t}\n")
	fmt.Fprintf(&buf, "\traw := strings.Split(value, string(os.PathListSeparator))\n")
	fmt.Fprintf(&buf, "\tout := make([]string, 0, len(raw))\n")
	fmt.Fprintf(&buf, "\tfor _, part := range raw {\n")
	fmt.Fprintf(&buf, "\t\tif trimmed := strings.TrimSpace(part); trimmed != \"\" {\n")
	fmt.Fprintf(&buf, "\t\t\tout = append(out, trimmed)\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\treturn out\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "func looksLikeStdlibPath(path string) bool {\n")
	fmt.Fprintf(&buf, "\tclean := filepath.Clean(path)\n")
	fmt.Fprintf(&buf, "\tparts := strings.Split(clean, string(os.PathSeparator))\n")
	fmt.Fprintf(&buf, "\tfor _, part := range parts {\n")
	fmt.Fprintf(&buf, "\t\tlower := strings.ToLower(part)\n")
	fmt.Fprintf(&buf, "\t\tif lower == \"stdlib\" || strings.HasPrefix(lower, \"stdlib_\") || lower == \"able-stdlib\" || lower == \"able_stdlib\" {\n")
	fmt.Fprintf(&buf, "\t\t\treturn true\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\treturn false\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "func looksLikeKernelPath(path string) bool {\n")
	fmt.Fprintf(&buf, "\tclean := filepath.Clean(path)\n")
	fmt.Fprintf(&buf, "\tparts := strings.Split(clean, string(os.PathSeparator))\n")
	fmt.Fprintf(&buf, "\tfor _, part := range parts {\n")
	fmt.Fprintf(&buf, "\t\tswitch strings.ToLower(part) {\n")
	fmt.Fprintf(&buf, "\t\tcase \"kernel\", \"ablekernel\", \"able_kernel\":\n")
	fmt.Fprintf(&buf, "\t\t\treturn true\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\treturn false\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "func collectKernelPaths(base string) []string {\n")
	fmt.Fprintf(&buf, "\tpaths := make([]string, 0)\n")
	fmt.Fprintf(&buf, "\tadd := func(candidate string) {\n")
	fmt.Fprintf(&buf, "\t\tif candidate == \"\" {\n\t\t\treturn\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tabs, err := filepath.Abs(candidate)\n\t\tif err != nil {\n\t\t\treturn\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tfor _, existing := range paths {\n\t\t\tif existing == abs {\n\t\t\t\treturn\n\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t\tpaths = append(paths, abs)\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tif base != \"\" {\n")
	fmt.Fprintf(&buf, "\t\tfor _, found := range findKernelRoots(base) {\n\t\t\tadd(found)\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tif len(paths) > 0 {\n\t\t\treturn paths\n\t\t}\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tfor _, entry := range splitPathListEnv(os.Getenv(\"ABLE_MODULE_PATHS\")) {\n\t\tadd(entry)\n\t}\n")
	fmt.Fprintf(&buf, "\tfor _, entry := range splitPathListEnv(os.Getenv(\"ABLE_PATH\")) {\n\t\tadd(entry)\n\t}\n")
	fmt.Fprintf(&buf, "\tif installed := stdlibpath.ResolveInstalledSrc(); installed != \"\" {\n\t\tadd(installed)\n\t\tif len(paths) > 0 {\n\t\t\treturn paths\n\t\t}\n\t}\n")
	fmt.Fprintf(&buf, "\tif len(paths) > 0 {\n\t\treturn paths\n\t}\n")
	fmt.Fprintf(&buf, "\tif cwd, err := os.Getwd(); err == nil {\n")
	fmt.Fprintf(&buf, "\t\tfor _, found := range findKernelRoots(cwd) {\n\t\t\tadd(found)\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tif len(paths) > 0 {\n\t\t\treturn paths\n\t\t}\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tif exe, err := os.Executable(); err == nil {\n")
	fmt.Fprintf(&buf, "\t\tfor _, found := range findKernelRoots(filepath.Dir(exe)) {\n\t\t\tadd(found)\n\t\t}\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\treturn paths\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "func collectStdlibPaths(base string) []string {\n")
	fmt.Fprintf(&buf, "\tpaths := make([]string, 0)\n")
	fmt.Fprintf(&buf, "\tadd := func(candidate string) {\n")
	fmt.Fprintf(&buf, "\t\tif candidate == \"\" {\n\t\t\treturn\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tabs, err := filepath.Abs(candidate)\n\t\tif err != nil {\n\t\t\treturn\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tfor _, existing := range paths {\n\t\t\tif existing == abs {\n\t\t\t\treturn\n\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t\tpaths = append(paths, abs)\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tif base != \"\" {\n")
	fmt.Fprintf(&buf, "\t\tfor _, found := range findStdlibRoots(base) {\n\t\t\tadd(found)\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tif len(paths) > 0 {\n\t\t\treturn paths\n\t\t}\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tfor _, entry := range splitPathListEnv(os.Getenv(\"ABLE_MODULE_PATHS\")) {\n\t\tadd(entry)\n\t}\n")
	fmt.Fprintf(&buf, "\tfor _, entry := range splitPathListEnv(os.Getenv(\"ABLE_PATH\")) {\n\t\tadd(entry)\n\t}\n")
	fmt.Fprintf(&buf, "\tif len(paths) > 0 {\n\t\treturn paths\n\t}\n")
	fmt.Fprintf(&buf, "\tif cwd, err := os.Getwd(); err == nil {\n")
	fmt.Fprintf(&buf, "\t\tfor _, found := range findStdlibRoots(cwd) {\n\t\t\tadd(found)\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tif len(paths) > 0 {\n\t\t\treturn paths\n\t\t}\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tif exe, err := os.Executable(); err == nil {\n")
	fmt.Fprintf(&buf, "\t\tfor _, found := range findStdlibRoots(filepath.Dir(exe)) {\n\t\t\tadd(found)\n\t\t}\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\treturn paths\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "func findKernelRoots(start string) []string {\n")
	fmt.Fprintf(&buf, "\troots := make([]string, 0)\n")
	fmt.Fprintf(&buf, "\tadd := func(candidate string) {\n")
	fmt.Fprintf(&buf, "\t\tif candidate == \"\" {\n\t\t\treturn\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tif info, err := os.Stat(candidate); err == nil && info.IsDir() {\n\t\t\troots = append(roots, candidate)\n\t\t}\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tdir := start\n")
	fmt.Fprintf(&buf, "\tfor {\n")
	fmt.Fprintf(&buf, "\t\tfor _, candidate := range []string{\n")
	fmt.Fprintf(&buf, "\t\t\tfilepath.Join(dir, \"kernel\", \"src\"),\n")
	fmt.Fprintf(&buf, "\t\t\tfilepath.Join(dir, \"v12\", \"kernel\", \"src\"),\n")
	fmt.Fprintf(&buf, "\t\t\tfilepath.Join(dir, \"ablekernel\", \"src\"),\n")
	fmt.Fprintf(&buf, "\t\t\tfilepath.Join(dir, \"able_kernel\", \"src\"),\n")
	fmt.Fprintf(&buf, "\t\t} {\n")
	fmt.Fprintf(&buf, "\t\t\tadd(candidate)\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t\tif len(roots) > 0 {\n\t\t\treturn roots\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tparent := filepath.Dir(dir)\n")
	fmt.Fprintf(&buf, "\t\tif parent == dir {\n\t\t\tbreak\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tdir = parent\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\treturn roots\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "func findStdlibRoots(start string) []string {\n")
	fmt.Fprintf(&buf, "\troots := make([]string, 0)\n")
	fmt.Fprintf(&buf, "\tadd := func(candidate string) {\n")
	fmt.Fprintf(&buf, "\t\tif candidate == \"\" {\n\t\t\treturn\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tif info, err := os.Stat(candidate); err == nil && info.IsDir() {\n\t\t\troots = append(roots, candidate)\n\t\t}\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tdir := start\n")
	fmt.Fprintf(&buf, "\tfor {\n")
	fmt.Fprintf(&buf, "\t\tfor _, candidate := range []string{\n")
	fmt.Fprintf(&buf, "\t\t\tfilepath.Join(dir, \"stdlib\", \"src\"),\n")
	fmt.Fprintf(&buf, "\t\t\tfilepath.Join(dir, \"able-stdlib\", \"src\"),\n")
	fmt.Fprintf(&buf, "\t\t\tfilepath.Join(dir, \"able_stdlib\", \"src\"),\n")
	fmt.Fprintf(&buf, "\t\t} {\n")
	fmt.Fprintf(&buf, "\t\t\tadd(candidate)\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t\tif len(roots) > 0 {\n\t\t\treturn roots\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tparent := filepath.Dir(dir)\n")
	fmt.Fprintf(&buf, "\t\tif parent == dir {\n\t\t\tbreak\n\t\t}\n")
	fmt.Fprintf(&buf, "\t\tdir = parent\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\treturn roots\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "func registerPrintInEnv(env *runtime.Environment, interp *interpreter.Interpreter) {\n")
	fmt.Fprintf(&buf, "\tif env == nil {\n")
	fmt.Fprintf(&buf, "\t\treturn\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tprintFn := runtime.NativeFunctionValue{\n")
	fmt.Fprintf(&buf, "\t\tName:  \"print\",\n")
	fmt.Fprintf(&buf, "\t\tArity: 1,\n")
	fmt.Fprintf(&buf, "\t\tImpl: func(_ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(&buf, "\t\t\tparts := make([]string, 0, len(args))\n")
	fmt.Fprintf(&buf, "\t\t\tfor _, arg := range args {\n")
	fmt.Fprintf(&buf, "\t\t\t\tparts = append(parts, formatRuntimeValue(interp, arg))\n")
	fmt.Fprintf(&buf, "\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t\tfmt.Fprintln(os.Stdout, strings.Join(parts, \" \"))\n")
	fmt.Fprintf(&buf, "\t\t\treturn runtime.VoidValue{}, nil\n")
	fmt.Fprintf(&buf, "\t\t},\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tenv.Define(\"print\", printFn)\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "func registerPrint(interp *interpreter.Interpreter) {\n")
	fmt.Fprintf(&buf, "\tif interp == nil {\n")
	fmt.Fprintf(&buf, "\t\treturn\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tregisterPrintInEnv(interp.GlobalEnvironment(), interp)\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "func registerOSBuiltinsInEnv(env *runtime.Environment, osArgs []string) {\n")
	fmt.Fprintf(&buf, "\tif env == nil {\n")
	fmt.Fprintf(&buf, "\t\treturn\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tif _, err := env.Get(\"__able_os_args\"); err != nil {\n")
	fmt.Fprintf(&buf, "\t\tenv.Define(\"__able_os_args\", runtime.NativeFunctionValue{\n")
	fmt.Fprintf(&buf, "\t\t\tName:  \"__able_os_args\",\n")
	fmt.Fprintf(&buf, "\t\t\tArity: 0,\n")
	fmt.Fprintf(&buf, "\t\t\tImpl: func(_ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(&buf, "\t\t\t\tif len(args) != 0 {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\treturn nil, fmt.Errorf(\"__able_os_args expects no arguments\")\n")
	fmt.Fprintf(&buf, "\t\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t\t\tvalues := make([]runtime.Value, 0, len(osArgs))\n")
	fmt.Fprintf(&buf, "\t\t\t\tfor _, arg := range osArgs {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\tvalues = append(values, runtime.StringValue{Val: arg})\n")
	fmt.Fprintf(&buf, "\t\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t\t\treturn &runtime.ArrayValue{Elements: values}, nil\n")
	fmt.Fprintf(&buf, "\t\t\t},\n")
	fmt.Fprintf(&buf, "\t\t})\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tif _, err := env.Get(\"__able_os_exit\"); err != nil {\n")
	fmt.Fprintf(&buf, "\t\tenv.Define(\"__able_os_exit\", runtime.NativeFunctionValue{\n")
	fmt.Fprintf(&buf, "\t\t\tName:  \"__able_os_exit\",\n")
	fmt.Fprintf(&buf, "\t\t\tArity: 1,\n")
	fmt.Fprintf(&buf, "\t\t\tImpl: func(_ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(&buf, "\t\t\t\tif len(args) != 1 {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\treturn nil, fmt.Errorf(\"__able_os_exit expects one argument\")\n")
	fmt.Fprintf(&buf, "\t\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t\t\tvar code int64\n")
	fmt.Fprintf(&buf, "\t\t\t\tswitch typed := args[0].(type) {\n")
	fmt.Fprintf(&buf, "\t\t\t\tcase runtime.IntegerValue:\n")
	fmt.Fprintf(&buf, "\t\t\t\t\tif n, ok := typed.ToInt64(); ok {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t\tcode = n\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t} else {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t\tcode = typed.BigInt().Int64()\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t\t\tcase *runtime.IntegerValue:\n")
	fmt.Fprintf(&buf, "\t\t\t\t\tif typed == nil {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t\treturn nil, fmt.Errorf(\"__able_os_exit expects integer argument\")\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t\t\t\tif n, ok := typed.ToInt64(); ok {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t\tcode = n\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t} else {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t\tcode = typed.BigInt().Int64()\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t\t\tdefault:\n")
	fmt.Fprintf(&buf, "\t\t\t\t\treturn nil, fmt.Errorf(\"__able_os_exit expects integer argument\")\n")
	fmt.Fprintf(&buf, "\t\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t\t\tif code < 0 {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\treturn nil, fmt.Errorf(\"exit code must be non-negative\")\n")
	fmt.Fprintf(&buf, "\t\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t\t\tif code > int64(^uint(0)>>1) {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\treturn nil, fmt.Errorf(\"exit code is out of range\")\n")
	fmt.Fprintf(&buf, "\t\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t\t\tos.Exit(int(code))\n")
	fmt.Fprintf(&buf, "\t\t\t\treturn runtime.VoidValue{}, nil\n")
	fmt.Fprintf(&buf, "\t\t\t},\n")
	fmt.Fprintf(&buf, "\t\t})\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "func isArrayStructInstance(v *runtime.StructInstanceValue) bool {\n")
	fmt.Fprintf(&buf, "\tif v == nil {\n")
	fmt.Fprintf(&buf, "\t\treturn false\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tif v.Definition != nil && v.Definition.Node != nil && v.Definition.Node.ID != nil {\n")
	fmt.Fprintf(&buf, "\t\tname := v.Definition.Node.ID.Name\n")
	fmt.Fprintf(&buf, "\t\tif name == \"Array\" || strings.HasSuffix(name, \".Array\") {\n")
	fmt.Fprintf(&buf, "\t\t\treturn true\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\t_, hasHandle := v.Fields[\"storage_handle\"]\n")
	fmt.Fprintf(&buf, "\t_, hasLength := v.Fields[\"length\"]\n")
	fmt.Fprintf(&buf, "\t_, hasCapacity := v.Fields[\"capacity\"]\n")
	fmt.Fprintf(&buf, "\treturn hasHandle && hasLength && hasCapacity\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "func isCallableRuntimeValue(val runtime.Value) bool {\n")
	fmt.Fprintf(&buf, "\tif runtime.IsFunctionLike(val) {\n")
	fmt.Fprintf(&buf, "\t\treturn true\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tswitch val.(type) {\n")
	fmt.Fprintf(&buf, "\tcase runtime.NativeFunctionValue, *runtime.NativeFunctionValue:\n")
	fmt.Fprintf(&buf, "\t\treturn true\n")
	fmt.Fprintf(&buf, "\tcase runtime.BoundMethodValue, *runtime.BoundMethodValue:\n")
	fmt.Fprintf(&buf, "\t\treturn true\n")
	fmt.Fprintf(&buf, "\tcase runtime.NativeBoundMethodValue, *runtime.NativeBoundMethodValue:\n")
	fmt.Fprintf(&buf, "\t\treturn true\n")
	fmt.Fprintf(&buf, "\tcase runtime.PartialFunctionValue, *runtime.PartialFunctionValue:\n")
	fmt.Fprintf(&buf, "\t\treturn true\n")
	fmt.Fprintf(&buf, "\tdefault:\n")
	fmt.Fprintf(&buf, "\t\treturn false\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "func formatRuntimeValue(interp *interpreter.Interpreter, val runtime.Value) string {\n")
	fmt.Fprintf(&buf, "\tif isCallableRuntimeValue(val) {\n")
	fmt.Fprintf(&buf, "\t\treturn \"<function>\"\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\tswitch v := val.(type) {\n")
	fmt.Fprintf(&buf, "\tcase runtime.StringValue:\n")
	fmt.Fprintf(&buf, "\t\treturn v.Val\n")
	fmt.Fprintf(&buf, "\tcase runtime.BoolValue:\n")
	fmt.Fprintf(&buf, "\t\tif v.Val {\n")
	fmt.Fprintf(&buf, "\t\t\treturn \"true\"\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t\treturn \"false\"\n")
	fmt.Fprintf(&buf, "\tcase runtime.IntegerValue:\n")
	fmt.Fprintf(&buf, "\t\treturn v.String()\n")
	fmt.Fprintf(&buf, "\tcase runtime.FloatValue:\n")
	fmt.Fprintf(&buf, "\t\treturn fmt.Sprintf(\"%%g\", v.Val)\n")
	fmt.Fprintf(&buf, "\tcase runtime.CharValue:\n")
	fmt.Fprintf(&buf, "\t\treturn string(v.Val)\n")
	fmt.Fprintf(&buf, "\tcase runtime.NilValue:\n")
	fmt.Fprintf(&buf, "\t\treturn \"nil\"\n")
	fmt.Fprintf(&buf, "\tcase *runtime.ArrayValue:\n")
	fmt.Fprintf(&buf, "\t\telems := make([]string, len(v.Elements))\n")
	fmt.Fprintf(&buf, "\t\tfor i, el := range v.Elements {\n")
	fmt.Fprintf(&buf, "\t\t\telems[i] = formatRuntimeValue(interp, el)\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t\treturn \"[\" + strings.Join(elems, \", \") + \"]\"\n")
	fmt.Fprintf(&buf, "\tcase *runtime.StructInstanceValue:\n")
	fmt.Fprintf(&buf, "\t\tif isArrayStructInstance(v) {\n")
	fmt.Fprintf(&buf, "\t\t\tif h, ok := v.Fields[\"storage_handle\"]; ok {\n")
	fmt.Fprintf(&buf, "\t\t\t\tif hv, ok := h.(runtime.IntegerValue); ok {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\tvar handle int64\n")
	fmt.Fprintf(&buf, "\t\t\t\t\tif n, ok := hv.ToInt64(); ok {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t\thandle = n\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t} else {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t\thandle = hv.BigInt().Int64()\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t\t\t\tstate, err := runtime.ArrayStoreState(handle)\n")
	fmt.Fprintf(&buf, "\t\t\t\t\tif err == nil {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t\telems := make([]string, len(state.Values))\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t\tfor i, el := range state.Values {\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t\t\telems[i] = formatRuntimeValue(interp, el)\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t\treturn \"[\" + strings.Join(elems, \", \") + \"]\"\n")
	fmt.Fprintf(&buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t\tif interp != nil {\n")
	fmt.Fprintf(&buf, "\t\t\tif rendered, err := interp.Stringify(v, nil); err == nil && rendered != \"\" {\n")
	fmt.Fprintf(&buf, "\t\t\t\treturn rendered\n")
	fmt.Fprintf(&buf, "\t\t\t}\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t\tname := \"Struct\"\n")
	fmt.Fprintf(&buf, "\t\tif v.Definition != nil && v.Definition.Node != nil && v.Definition.Node.ID != nil {\n")
	fmt.Fprintf(&buf, "\t\t\tname = v.Definition.Node.ID.Name\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t\tkeys := make([]string, 0, len(v.Fields))\n")
	fmt.Fprintf(&buf, "\t\tfor k := range v.Fields {\n")
	fmt.Fprintf(&buf, "\t\t\tkeys = append(keys, k)\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t\tsort.Strings(keys)\n")
	fmt.Fprintf(&buf, "\t\tfields := make([]string, len(keys))\n")
	fmt.Fprintf(&buf, "\t\tfor i, k := range keys {\n")
	fmt.Fprintf(&buf, "\t\t\tfields[i] = k + \": \" + formatRuntimeValue(interp, v.Fields[k])\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t\treturn name + \" { \" + strings.Join(fields, \", \") + \" }\"\n")
	fmt.Fprintf(&buf, "\tcase runtime.ErrorValue:\n")
	fmt.Fprintf(&buf, "\t\treturn v.Message\n")
	fmt.Fprintf(&buf, "\tcase *runtime.InterfaceValue:\n")
	fmt.Fprintf(&buf, "\t\tif v.Interface != nil && v.Interface.Node != nil && v.Interface.Node.ID != nil {\n")
	fmt.Fprintf(&buf, "\t\t\treturn \"<interface \" + v.Interface.Node.ID.Name + \">\"\n")
	fmt.Fprintf(&buf, "\t\t}\n")
	fmt.Fprintf(&buf, "\t\treturn \"<interface>\"\n")
	fmt.Fprintf(&buf, "\tdefault:\n")
	fmt.Fprintf(&buf, "\t\treturn fmt.Sprintf(\"<%%s>\", v.Kind())\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "}\n\n")
	onlyCompiledFunctions := true
	functionCount := 0
	for _, byName := range g.functions {
		for _, info := range byName {
			if info == nil {
				continue
			}
			functionCount++
			if !info.Compileable {
				onlyCompiledFunctions = false
			}
		}
	}
	if functionCount == 0 {
		onlyCompiledFunctions = false
	}
	onlyCompiledMethods := true
	for _, method := range g.methodList {
		if method == nil || method.Info == nil || !method.Info.Compileable {
			onlyCompiledMethods = false
			break
		}
	}
	onlyCompiledImpls := true
	for _, implMethod := range g.implMethodList {
		if implMethod == nil || implMethod.Info == nil || !implMethod.Info.Compileable {
			onlyCompiledImpls = false
			break
		}
	}
	importsSeedable := g.noBootstrapImportsSeedable()
	requiresBootstrap := g.hasDynamicFeature || len(g.collectFallbacks()) > 0 || !onlyCompiledFunctions || !onlyCompiledMethods || !onlyCompiledImpls || !importsSeedable
	fmt.Fprintf(&buf, "func main() {\n")
	if requiresBootstrap {
		fmt.Fprintf(&buf, "\tinterp := interpreter.New()\n")
		fmt.Fprintf(&buf, "\tinterp.SetArgs(os.Args[1:])\n")
		fmt.Fprintf(&buf, "\tregisterPrint(interp)\n")
		fmt.Fprintf(&buf, "\tentry := %q\n", g.opts.EntryPath)
		fmt.Fprintf(&buf, "\tsearchPaths := collectSearchPaths(filepath.Dir(entry))\n")
		fmt.Fprintf(&buf, "\tsearchPaths, err := finalizeSearchPaths(searchPaths)\n")
		fmt.Fprintf(&buf, "\tif err != nil {\n")
		fmt.Fprintf(&buf, "\t\tfmt.Fprintln(os.Stderr, err)\n")
		fmt.Fprintf(&buf, "\t\tos.Exit(1)\n")
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "\tloader, err := driver.NewLoader(searchPaths)\n")
		fmt.Fprintf(&buf, "\tif err != nil {\n")
		fmt.Fprintf(&buf, "\t\tfmt.Fprintln(os.Stderr, err)\n")
		fmt.Fprintf(&buf, "\t\tos.Exit(1)\n")
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "\tdefer loader.Close()\n")
		fmt.Fprintf(&buf, "\tprogram, err := loader.Load(entry)\n")
		fmt.Fprintf(&buf, "\tif err != nil {\n")
		fmt.Fprintf(&buf, "\t\tfmt.Fprintln(os.Stderr, err)\n")
		fmt.Fprintf(&buf, "\t\tos.Exit(1)\n")
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "\t_, entryEnv, _, err := interp.EvaluateProgram(program, interpreter.ProgramEvaluationOptions{SkipTypecheck: true})\n")
		fmt.Fprintf(&buf, "\tif err != nil {\n")
		fmt.Fprintf(&buf, "\t\tif code, ok := interpreter.ExitCodeFromError(err); ok {\n")
		fmt.Fprintf(&buf, "\t\t\tos.Exit(code)\n")
		fmt.Fprintf(&buf, "\t\t}\n")
		fmt.Fprintf(&buf, "\t\tfmt.Fprintln(os.Stderr, interpreter.DescribeRuntimeDiagnostic(interp.BuildRuntimeDiagnostic(err)))\n")
		fmt.Fprintf(&buf, "\t\tos.Exit(1)\n")
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "\trt, err := RegisterIn(interp, entryEnv)\n")
		fmt.Fprintf(&buf, "\tif err != nil {\n")
		fmt.Fprintf(&buf, "\t\tfmt.Fprintln(os.Stderr, err)\n")
		fmt.Fprintf(&buf, "\t\tos.Exit(1)\n")
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "\tif entryEnv == nil {\n")
		fmt.Fprintf(&buf, "\t\tentryEnv = interp.GlobalEnvironment()\n")
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "\tif err := RunRegisteredMain(rt, interp, entryEnv); err != nil {\n")
		fmt.Fprintf(&buf, "\t\tif err.Error() == \"entry module does not define a main function\" {\n")
		fmt.Fprintf(&buf, "\t\t\tfmt.Fprintln(os.Stderr, err.Error())\n")
		fmt.Fprintf(&buf, "\t\t\tos.Exit(1)\n")
		fmt.Fprintf(&buf, "\t\t}\n")
		fmt.Fprintf(&buf, "\t\tif code, ok := interpreter.ExitCodeFromError(err); ok {\n")
		fmt.Fprintf(&buf, "\t\t\tos.Exit(code)\n")
		fmt.Fprintf(&buf, "\t\t}\n")
		fmt.Fprintf(&buf, "\t\tfmt.Fprintln(os.Stderr, interpreter.DescribeRuntimeDiagnostic(interp.BuildRuntimeDiagnostic(err)))\n")
		fmt.Fprintf(&buf, "\t\tos.Exit(1)\n")
		fmt.Fprintf(&buf, "\t}\n")
	} else {
		fmt.Fprintf(&buf, "\tentryEnv := runtime.NewEnvironment(nil)\n")
		fmt.Fprintf(&buf, "\tregisterPrintInEnv(entryEnv, nil)\n")
		fmt.Fprintf(&buf, "\tregisterOSBuiltinsInEnv(entryEnv, os.Args[1:])\n")
		fmt.Fprintf(&buf, "\trt, err := RegisterIn(nil, entryEnv)\n")
		fmt.Fprintf(&buf, "\tif err != nil {\n")
		fmt.Fprintf(&buf, "\t\tfmt.Fprintln(os.Stderr, err)\n")
		fmt.Fprintf(&buf, "\t\tos.Exit(1)\n")
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "\tif err := RunRegisteredMain(rt, nil, entryEnv); err != nil {\n")
		fmt.Fprintf(&buf, "\t\tif err.Error() == \"entry module does not define a main function\" {\n")
		fmt.Fprintf(&buf, "\t\t\tfmt.Fprintln(os.Stderr, err.Error())\n")
		fmt.Fprintf(&buf, "\t\t\tos.Exit(1)\n")
		fmt.Fprintf(&buf, "\t\t}\n")
		fmt.Fprintf(&buf, "\t\tif code, ok := interpreter.ExitCodeFromError(err); ok {\n")
		fmt.Fprintf(&buf, "\t\t\tos.Exit(code)\n")
		fmt.Fprintf(&buf, "\t\t}\n")
		fmt.Fprintf(&buf, "\t\tfmt.Fprintln(os.Stderr, err)\n")
		fmt.Fprintf(&buf, "\t\tos.Exit(1)\n")
		fmt.Fprintf(&buf, "\t}\n")
	}
	fmt.Fprintf(&buf, "}\n")
	return formatSource(buf.Bytes())
}
