package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderRuntimeInterfaceCompiledResolver(buf *bytes.Buffer) {
	// __able_resolve_compiled_interface_method bridges the compiled interface dispatch
	// tables back to the interpreter. It is called by the interpreter's resolveInterfaceMethod
	// (via SetInterfaceMethodResolver) when the interpreter cannot find an impl method in its
	// own registry — which is always the case in no-bootstrap mode.
	fmt.Fprintf(buf, "func __able_resolve_compiled_interface_method(rt *bridge.Runtime, receiver runtime.Value, interfaceName string, methodName string) (runtime.Value, bool) {\n")
	fmt.Fprintf(buf, "\tif __able_interface_dispatch == nil || interfaceName == \"\" || methodName == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treceiver = __able_unwrap_interface(receiver)\n")
	fmt.Fprintf(buf, "\tif receiver == nil {\n")
	fmt.Fprintf(buf, "\t\treceiver = runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvar entries []__able_interface_dispatch_entry\n")
	fmt.Fprintf(buf, "\tif perIface := __able_interface_dispatch[interfaceName]; perIface != nil {\n")
	fmt.Fprintf(buf, "\t\tentries = perIface[methodName]\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(entries) == 0 {\n")
	fmt.Fprintf(buf, "\t\tnames := __able_interface_search(interfaceName)\n")
	fmt.Fprintf(buf, "\t\tif len(names) > 1 {\n")
	fmt.Fprintf(buf, "\t\t\tfor _, base := range names[1:] {\n")
	fmt.Fprintf(buf, "\t\t\t\tif perIface := __able_interface_dispatch[base]; perIface != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tentries = append(entries, perIface[methodName]...)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(entries) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tmatches := make([]__able_interface_dispatch_match, 0, 1)\n")
	fmt.Fprintf(buf, "\tfor _, entry := range entries {\n")
	fmt.Fprintf(buf, "\t\tif len(entry.genericNames) > 0 {\n")
	fmt.Fprintf(buf, "\t\t\tactual, err := bridge.TypeExpressionFromValue(rt, receiver)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil || actual == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\ttemplate := __able_expand_runtime_type_aliases(entry.targetType, make(map[string]struct{}))\n")
	fmt.Fprintf(buf, "\t\t\tactual = __able_expand_runtime_type_aliases(actual, make(map[string]struct{}))\n")
	fmt.Fprintf(buf, "\t\t\tbindings := make(map[string]ast.TypeExpression)\n")
	fmt.Fprintf(buf, "\t\t\tif !__able_match_type_template(template, actual, entry.genericNames, bindings) {\n")
	fmt.Fprintf(buf, "\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif !__able_enforce_constraints(entry.constraints, bindings) {\n")
	fmt.Fprintf(buf, "\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tmatches = append(matches, __able_interface_dispatch_match{entry: entry, receiver: receiver})\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tcoerced, ok, err := bridge.MatchType(rt, entry.targetType, receiver)\n")
	fmt.Fprintf(buf, "\t\tif err != nil || !ok {\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !__able_enforce_constraints(entry.constraints, nil) {\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tmatches = append(matches, __able_interface_dispatch_match{entry: entry, receiver: coerced})\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(matches) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbestIdx := 0\n")
	fmt.Fprintf(buf, "\tfor idx := 1; idx < len(matches); idx++ {\n")
	fmt.Fprintf(buf, "\t\tcmp := __able_compare_interface_entries(matches[idx].entry, matches[bestIdx].entry)\n")
	fmt.Fprintf(buf, "\t\tif cmp > 0 {\n")
	fmt.Fprintf(buf, "\t\t\tbestIdx = idx\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tmatch := matches[bestIdx]\n")
	fmt.Fprintf(buf, "\tif match.entry.fn == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	// Return a new NativeFunctionValue with arity adjusted for direct calling.
	// The dispatch entry's fn has arity N (excluding self for bound-method path),
	// but the interpreter calls with self as the first arg, so we need arity N+1.
	// Negative arity means variadic/overloaded - preserve it as-is.
	fmt.Fprintf(buf, "\tarity := match.entry.fn.Arity\n")
	fmt.Fprintf(buf, "\tif arity >= 0 {\n")
	fmt.Fprintf(buf, "\t\tarity = arity + 1\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\twrapped := &runtime.NativeFunctionValue{Name: match.entry.fn.Name, Arity: arity, Impl: match.entry.fn.Impl}\n")
	fmt.Fprintf(buf, "\treturn wrapped, true\n")
	fmt.Fprintf(buf, "}\n\n")
}
