package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderRuntimeInterfaceMemberDispatchHelpers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "func __able_interface_bind_receiver_method(receiver runtime.Value, method runtime.Value) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif method == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif native, ok, nilPtr := __able_callable_native_function_value(method); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn &runtime.NativeBoundMethodValue{Receiver: receiver, Method: native}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif nativeBound, ok, nilPtr := __able_callable_native_bound_method_value(method); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn &runtime.NativeBoundMethodValue{Receiver: receiver, Method: nativeBound.Method}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif bound, ok, nilPtr := __able_callable_bound_method_value(method); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn &runtime.BoundMethodValue{Receiver: receiver, Method: bound.Method}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn &runtime.BoundMethodValue{Receiver: receiver, Method: method}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_interface_dispatch_static_receiver(receiver runtime.Value) bool {\n")
	fmt.Fprintf(buf, "\tif _, ok, nilPtr := __able_runtime_struct_definition_value(receiver); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\treturn ok && !nilPtr\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif _, ok, nilPtr := __able_runtime_type_ref_value(receiver); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\treturn ok && !nilPtr\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn false\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_runtime_struct_definition_value(value runtime.Value) (runtime.StructDefinitionValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.StructDefinitionValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tcase *runtime.StructDefinitionValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.StructDefinitionValue{}, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn *typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.StructDefinitionValue{}, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_runtime_type_ref_value(value runtime.Value) (runtime.TypeRefValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.TypeRefValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tcase *runtime.TypeRefValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.TypeRefValue{}, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn *typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.TypeRefValue{}, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_runtime_integer_value(value runtime.Value) (runtime.IntegerValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tcase *runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.IntegerValue{}, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn *typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.IntegerValue{}, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_runtime_float_value(value runtime.Value) (runtime.FloatValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.FloatValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tcase *runtime.FloatValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.FloatValue{}, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn *typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.FloatValue{}, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_runtime_value_type_name(value runtime.Value) string {\n")
	fmt.Fprintf(buf, "\tfor value != nil {\n")
	fmt.Fprintf(buf, "\t\tif iface, ok, nilPtr := __able_callable_interface_value(value); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tvalue = iface.Underlying\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbreak\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif inst := __able_struct_instance(value); inst != nil && inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil {\n")
	fmt.Fprintf(buf, "\t\treturn inst.Definition.Node.ID.Name\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif structDef, ok, nilPtr := __able_runtime_struct_definition_value(value); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif structDef.Node != nil && structDef.Node.ID != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn structDef.Node.ID.Name\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif typeRef, ok, nilPtr := __able_runtime_type_ref_value(value); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn typeRef.TypeName\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif intVal, ok, nilPtr := __able_runtime_integer_value(value); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn string(intVal.TypeSuffix)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif floatVal, ok, nilPtr := __able_runtime_float_value(value); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn string(floatVal.TypeSuffix)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch value.(type) {\n")
	fmt.Fprintf(buf, "\tcase *runtime.ArrayValue:\n")
	fmt.Fprintf(buf, "\t\treturn \"Array\"\n")
	fmt.Fprintf(buf, "\tcase *runtime.HashMapValue:\n")
	fmt.Fprintf(buf, "\t\treturn \"HashMap\"\n")
	fmt.Fprintf(buf, "\tcase runtime.StringValue, *runtime.StringValue:\n")
	fmt.Fprintf(buf, "\t\treturn \"String\"\n")
	fmt.Fprintf(buf, "\tcase runtime.BoolValue, *runtime.BoolValue:\n")
	fmt.Fprintf(buf, "\t\treturn \"bool\"\n")
	fmt.Fprintf(buf, "\tcase runtime.CharValue, *runtime.CharValue:\n")
	fmt.Fprintf(buf, "\t\treturn \"char\"\n")
	fmt.Fprintf(buf, "\tcase runtime.NilValue, *runtime.NilValue:\n")
	fmt.Fprintf(buf, "\t\treturn \"nil\"\n")
	fmt.Fprintf(buf, "\tcase runtime.VoidValue, *runtime.VoidValue:\n")
	fmt.Fprintf(buf, "\t\treturn \"void\"\n")
	fmt.Fprintf(buf, "\tcase runtime.ErrorValue, *runtime.ErrorValue:\n")
	fmt.Fprintf(buf, "\t\treturn \"Error\"\n")
	fmt.Fprintf(buf, "\tcase runtime.DynPackageValue, *runtime.DynPackageValue:\n")
	fmt.Fprintf(buf, "\t\treturn \"DynPackage\"\n")
	fmt.Fprintf(buf, "\tcase *runtime.FutureValue:\n")
	fmt.Fprintf(buf, "\t\treturn \"Future\"\n")
	fmt.Fprintf(buf, "\tcase *runtime.IteratorValue:\n")
	fmt.Fprintf(buf, "\t\treturn \"Iterator\"\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn \"\"\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_interface_dispatch_match_equivalent(a, b __able_interface_dispatch_match) bool {\n")
	fmt.Fprintf(buf, "\taTarget := __able_type_expr_string(a.entry.targetType)\n")
	fmt.Fprintf(buf, "\tbTarget := __able_type_expr_string(b.entry.targetType)\n")
	fmt.Fprintf(buf, "\tif aTarget != bTarget {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif a.entry.targetScore != b.entry.targetScore || a.entry.isConcrete != b.entry.isConcrete || a.entry.isBuiltin != b.entry.isBuiltin || a.entry.isPrivate != b.entry.isPrivate {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(a.entry.constraintKeys) != len(b.entry.constraintKeys) {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfor key := range a.entry.constraintKeys {\n")
	fmt.Fprintf(buf, "\t\tif _, ok := b.entry.constraintKeys[key]; !ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(a.entry.unionVariants) != len(b.entry.unionVariants) {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfor idx := range a.entry.unionVariants {\n")
	fmt.Fprintf(buf, "\t\tif a.entry.unionVariants[idx] != b.entry.unionVariants[idx] {\n")
	fmt.Fprintf(buf, "\t\t\treturn false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif (a.entry.fn == nil) != (b.entry.fn == nil) {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif a.entry.fn != nil && b.entry.fn != nil && strings.TrimSpace(a.entry.fn.Name) != strings.TrimSpace(b.entry.fn.Name) {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn true\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_interface_dispatch_match_entry(receiver runtime.Value, receiverTypeName string, entry __able_interface_dispatch_entry) (runtime.Value, bool, error) {\n")
	fmt.Fprintf(buf, "\tif entry.fn == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif receiverTypeName != \"\" {\n")
	fmt.Fprintf(buf, "\t\tif simple, ok := entry.targetType.(*ast.SimpleTypeExpression); ok && simple != nil && simple.Name != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif simple.Name.Name == receiverTypeName {\n")
	fmt.Fprintf(buf, "\t\t\t\tif !__able_enforce_constraints(entry.constraints, nil) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\treturn receiver, true, nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif _, isGeneric := entry.genericNames[simple.Name.Name]; !isGeneric {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(entry.genericNames) > 0 {\n")
	fmt.Fprintf(buf, "\t\tactual, err := bridge.TypeExpressionFromValue(__able_runtime, receiver)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif actual == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\ttemplate, err := bridge.ExpandTypeAliases(__able_runtime, entry.targetType)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tactual, err = bridge.ExpandTypeAliases(__able_runtime, actual)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbindings := make(map[string]ast.TypeExpression)\n")
	fmt.Fprintf(buf, "\t\tif !__able_match_type_template(template, actual, entry.genericNames, bindings) {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !__able_enforce_constraints(entry.constraints, bindings) {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn receiver, true, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcoerced, ok, err := bridge.MatchType(__able_runtime, entry.targetType, receiver)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif !ok {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif !__able_enforce_constraints(entry.constraints, nil) {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn coerced, true, nil\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_interface_dispatch_member(receiver runtime.Value, name string) (runtime.Value, bool, error) {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil || strings.TrimSpace(name) == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_interface_dispatch == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treceiver = __able_unwrap_interface(receiver)\n")
	fmt.Fprintf(buf, "\tif receiver == nil {\n")
	fmt.Fprintf(buf, "\t\treceiver = runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treceiverTypeName := __able_runtime_value_type_name(receiver)\n")
	fmt.Fprintf(buf, "\tifaceNames := make([]string, 0, len(__able_interface_dispatch))\n")
	fmt.Fprintf(buf, "\tfor ifaceName, perIface := range __able_interface_dispatch {\n")
	fmt.Fprintf(buf, "\t\tif ifaceName == \"\" || perIface == nil || len(perIface[name]) == 0 {\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tifaceNames = append(ifaceNames, ifaceName)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(ifaceNames) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tsort.Strings(ifaceNames)\n")
	fmt.Fprintf(buf, "\tmatches := make([]__able_interface_dispatch_match, 0, 1)\n")
	fmt.Fprintf(buf, "\tfor _, ifaceName := range ifaceNames {\n")
	fmt.Fprintf(buf, "\t\tentries := __able_interface_dispatch[ifaceName][name]\n")
	fmt.Fprintf(buf, "\t\tfor _, entry := range entries {\n")
	fmt.Fprintf(buf, "\t\t\tif matchedReceiver, ok, err := __able_interface_dispatch_match_entry(receiver, receiverTypeName, entry); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn nil, false, err\n")
	fmt.Fprintf(buf, "\t\t\t} else if ok {\n")
	fmt.Fprintf(buf, "\t\t\t\tmatches = append(matches, __able_interface_dispatch_match{entry: entry, receiver: matchedReceiver})\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(matches) == 0 {\n")
	fmt.Fprintf(buf, "\t\tif len(ifaceNames) == 1 && name == \"show\" {\n")
	fmt.Fprintf(buf, "\t\t\ttypeName := strings.TrimSpace(receiverTypeName)\n")
	fmt.Fprintf(buf, "\t\t\tif typeName != \"\" {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn nil, false, __able_wrap_caller_frame_error(fmt.Errorf(\"Type '%%s' does not satisfy interface '%%s': missing method '%%s'\", typeName, ifaceNames[0], name))\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbestIdx := 0\n")
	fmt.Fprintf(buf, "\tcontenders := []int{0}\n")
	fmt.Fprintf(buf, "\tfor idx := 1; idx < len(matches); idx++ {\n")
	fmt.Fprintf(buf, "\t\tcmp := __able_compare_interface_entries(matches[idx].entry, matches[bestIdx].entry)\n")
	fmt.Fprintf(buf, "\t\tif cmp > 0 {\n")
	fmt.Fprintf(buf, "\t\t\tbestIdx = idx\n")
	fmt.Fprintf(buf, "\t\t\tcontenders = []int{idx}\n")
	fmt.Fprintf(buf, "\t\t} else if cmp == 0 {\n")
	fmt.Fprintf(buf, "\t\t\treverse := __able_compare_interface_entries(matches[bestIdx].entry, matches[idx].entry)\n")
	fmt.Fprintf(buf, "\t\t\tif reverse < 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\tbestIdx = idx\n")
	fmt.Fprintf(buf, "\t\t\t\tcontenders = []int{idx}\n")
	fmt.Fprintf(buf, "\t\t\t} else if reverse == 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\tcontenders = append(contenders, idx)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(contenders) > 1 {\n")
	fmt.Fprintf(buf, "\t\tfirst := matches[contenders[0]]\n")
	fmt.Fprintf(buf, "\t\tfor _, idx := range contenders[1:] {\n")
	fmt.Fprintf(buf, "\t\t\tif !__able_interface_dispatch_match_equivalent(first, matches[idx]) {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbestIdx = contenders[0]\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tmatch := matches[bestIdx]\n")
	fmt.Fprintf(buf, "\tif match.entry.isPrivate {\n")
	fmt.Fprintf(buf, "\t\ttargetName := __able_type_expr_string(match.entry.targetType)\n")
	fmt.Fprintf(buf, "\t\tif strings.TrimSpace(targetName) == \"\" {\n")
	fmt.Fprintf(buf, "\t\t\ttargetName = \"<unknown>\"\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, fmt.Errorf(\"Method '%%s' on %%s is private\", name, targetName)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_interface_dispatch_static_receiver(match.receiver) {\n")
	fmt.Fprintf(buf, "\t\tif match.entry.fn == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn match.entry.fn, true, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbound := __able_interface_bind_receiver_method(match.receiver, match.entry.fn)\n")
	fmt.Fprintf(buf, "\tif bound == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bound, true, nil\n")
	fmt.Fprintf(buf, "}\n\n")
}
