package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderRuntimeConcurrencyExternWrappers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "func __able_extern_channel_new(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_channel_new_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_channel_send(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_channel_send_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_channel_receive(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_channel_receive_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_channel_try_send(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_channel_try_send_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_channel_try_receive(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_channel_try_receive_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_channel_await_try_recv(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_channel_await_try_recv_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_channel_await_try_send(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_channel_await_try_send_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_channel_close(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_channel_close_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_channel_is_closed(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_channel_is_closed_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_mutex_new(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_mutex_new_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_mutex_lock(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_mutex_lock_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_mutex_unlock(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_mutex_unlock_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_mutex_await_lock(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_mutex_await_lock_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
}
