package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderRuntimeIntegerMethodHelpers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "func __able_integer_value(value runtime.Value) (runtime.IntegerValue, bool) {\n")
	fmt.Fprintf(buf, "\tvalue = __able_unwrap_interface(value)\n")
	fmt.Fprintf(buf, "\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true\n")
	fmt.Fprintf(buf, "\tcase *runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tif typed != nil { return *typed, true }\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.IntegerValue{}, false\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_integer_arithmetic(methodName string) func(*bridge.Runtime, *runtime.NativeCallContext, []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\treturn func(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\tif len(args) != 2 {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"%%s expects a receiver and one argument\", methodName)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tleft, ok := __able_integer_value(args[0])\n")
	fmt.Fprintf(buf, "\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"%%s receiver must be a fixed-width integer\", methodName)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tright, ok := __able_integer_value(args[1])\n")
	fmt.Fprintf(buf, "\t\tif !ok || right.TypeSuffix != left.TypeSuffix {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"%%s argument must match receiver type %%s\", methodName, left.TypeSuffix)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tvar mode runtime.FixedIntegerMode\n")
	fmt.Fprintf(buf, "\t\tswitch {\n")
	fmt.Fprintf(buf, "\t\tcase strings.HasPrefix(methodName, \"wrapping_\"):\n")
	fmt.Fprintf(buf, "\t\t\tmode = runtime.FixedIntegerWrapping\n")
	fmt.Fprintf(buf, "\t\tcase strings.HasPrefix(methodName, \"saturating_\"):\n")
	fmt.Fprintf(buf, "\t\t\tmode = runtime.FixedIntegerSaturating\n")
	fmt.Fprintf(buf, "\t\tcase strings.HasPrefix(methodName, \"checked_\"):\n")
	fmt.Fprintf(buf, "\t\t\tmode = runtime.FixedIntegerChecked\n")
	fmt.Fprintf(buf, "\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"unknown fixed integer method %%s\", methodName)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tvar operation runtime.FixedIntegerOperation\n")
	fmt.Fprintf(buf, "\t\tswitch methodName[strings.IndexByte(methodName, '_')+1:] {\n")
	fmt.Fprintf(buf, "\t\tcase \"add\":\n")
	fmt.Fprintf(buf, "\t\t\toperation = runtime.FixedIntegerAdd\n")
	fmt.Fprintf(buf, "\t\tcase \"sub\":\n")
	fmt.Fprintf(buf, "\t\t\toperation = runtime.FixedIntegerSub\n")
	fmt.Fprintf(buf, "\t\tcase \"mul\":\n")
	fmt.Fprintf(buf, "\t\t\toperation = runtime.FixedIntegerMul\n")
	fmt.Fprintf(buf, "\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"unknown fixed integer method %%s\", methodName)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tresult, present, err := runtime.FixedIntegerArithmetic(left, right, operation, mode)\n")
	fmt.Fprintf(buf, "\t\tif err != nil { return nil, err }\n")
	fmt.Fprintf(buf, "\t\tif !present { return runtime.NilValue{}, nil }\n")
	fmt.Fprintf(buf, "\t\treturn result, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
}
