package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderRuntimeCallHelpers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "func __able_member_set(obj runtime.Value, member runtime.Value, value runtime.Value) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbase := __able_unwrap_interface(obj)\n")
	fmt.Fprintf(buf, "\tif name, ok := __able_member_name(member); ok {\n")
	fmt.Fprintf(buf, "\t\tif arr, ok := base.(*runtime.ArrayValue); ok && arr != nil {\n")
	fmt.Fprintf(buf, "\t\t\tswitch name {\n")
	fmt.Fprintf(buf, "\t\t\tcase \"storage_handle\":\n")
	fmt.Fprintf(buf, "\t\t\t\thandle, err := __able_array_handle_from_value(value)\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\tif handle <= 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(fmt.Errorf(\"array storage_handle must be positive\"))\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tstate, err := runtime.ArrayStoreEnsureHandle(handle, 0, 0)\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\tarr.Handle = handle\n")
	fmt.Fprintf(buf, "\t\t\t\tarr.Elements = state.Values\n")
	fmt.Fprintf(buf, "\t\t\t\treturn value\n")
	fmt.Fprintf(buf, "\t\t\tcase \"length\":\n")
	fmt.Fprintf(buf, "\t\t\t\tlength, err := __able_array_index_from_value(value)\n")
	fmt.Fprintf(buf, "\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(fmt.Errorf(\"array length must be a non-negative integer\"))\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif arr.Handle != 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(runtime.ArrayStoreSetLength(arr.Handle, length))\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif length < 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif length <= len(arr.Elements) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tarr.Elements = arr.Elements[:length]\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tfor len(arr.Elements) < length {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tarr.Elements = append(arr.Elements, runtime.NilValue{})\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\treturn value\n")
	fmt.Fprintf(buf, "\t\t\tcase \"capacity\":\n")
	fmt.Fprintf(buf, "\t\t\t\tcapacity, err := __able_array_index_from_value(value)\n")
	fmt.Fprintf(buf, "\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(fmt.Errorf(\"array capacity must be a non-negative integer\"))\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif arr.Handle != 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(runtime.ArrayStoreReserve(arr.Handle, capacity))\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif capacity < len(arr.Elements) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcapacity = len(arr.Elements)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif cap(arr.Elements) < capacity {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tnewValues := make([]runtime.Value, len(arr.Elements), capacity)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcopy(newValues, arr.Elements)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tarr.Elements = newValues\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\treturn value\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif inst := __able_struct_instance(base); inst != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil && inst.Definition.Node.ID.Name == \"Array\" {\n")
	fmt.Fprintf(buf, "\t\t\t\tswitch name {\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"storage_handle\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\thandle, err := __able_array_handle_from_value(value)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif handle <= 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(fmt.Errorf(\"array storage_handle must be positive\"))\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t_, err = runtime.ArrayStoreEnsureHandle(handle, 0, 0)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif inst.Fields == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tinst.Fields = map[string]runtime.Value{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tinst.Fields[\"storage_handle\"] = value\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"length\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\tlength, err := __able_array_index_from_value(value)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(fmt.Errorf(\"array length must be a non-negative integer\"))\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif handleVal, ok := inst.Fields[\"storage_handle\"]; ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\thandle, err := __able_array_handle_from_value(handleVal)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(runtime.ArrayStoreSetLength(handle, length))\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif inst.Fields == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tinst.Fields = map[string]runtime.Value{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tinst.Fields[\"length\"] = bridge.ToInt(int64(length), runtime.IntegerI32)\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"capacity\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcapacity, err := __able_array_index_from_value(value)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(fmt.Errorf(\"array capacity must be a non-negative integer\"))\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif handleVal, ok := inst.Fields[\"storage_handle\"]; ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\thandle, err := __able_array_handle_from_value(handleVal)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(runtime.ArrayStoreReserve(handle, capacity))\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif inst.Fields == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tinst.Fields = map[string]runtime.Value{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tinst.Fields[\"capacity\"] = bridge.ToInt(int64(capacity), runtime.IntegerI32)\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil && inst.Definition.Node.ID.Name == \"HashMap\" {\n")
	fmt.Fprintf(buf, "\t\t\t\tswitch name {\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"handle\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif inst.Fields == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tpanic(fmt.Errorf(\"hash map value missing handle\"))\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tval, ok := inst.Fields[\"handle\"]\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tpanic(fmt.Errorf(\"hash map value missing handle\"))\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil && inst.Definition.Node.ID.Name == \"HashMap\" {\n")
	fmt.Fprintf(buf, "\t\t\t\tswitch name {\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"handle\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\thandle, err := __able_hash_map_handle_from_value(value)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif handle <= 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(fmt.Errorf(\"hash map handle must be positive\"))\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t_, err = runtime.HashMapStoreEnsureHandle(handle, 0)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif inst.Fields == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tinst.Fields = map[string]runtime.Value{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tinst.Fields[\"handle\"] = value\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn value\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := bridge.MemberAssign(__able_runtime, obj, member, value)\n")
	fmt.Fprintf(buf, "\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_member_get(obj runtime.Value, member runtime.Value) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbase := __able_unwrap_interface(obj)\n")
	fmt.Fprintf(buf, "\tif name, ok := __able_member_name(member); ok {\n")
	fmt.Fprintf(buf, "\t\tif arr, ok := base.(*runtime.ArrayValue); ok && arr != nil {\n")
	fmt.Fprintf(buf, "\t\t\tswitch name {\n")
	fmt.Fprintf(buf, "\t\t\tcase \"storage_handle\":\n")
	fmt.Fprintf(buf, "\t\t\t\treturn bridge.ToInt(arr.Handle, runtime.IntegerI64)\n")
	fmt.Fprintf(buf, "\t\t\tcase \"length\":\n")
	fmt.Fprintf(buf, "\t\t\t\tlength := len(arr.Elements)\n")
	fmt.Fprintf(buf, "\t\t\t\tif arr.Handle != 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tvalue, err := runtime.ArrayStoreSize(arr.Handle)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tlength = value\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\treturn bridge.ToInt(int64(length), runtime.IntegerI32)\n")
	fmt.Fprintf(buf, "\t\t\tcase \"capacity\":\n")
	fmt.Fprintf(buf, "\t\t\t\tcapacity := cap(arr.Elements)\n")
	fmt.Fprintf(buf, "\t\t\t\tif arr.Handle != 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tvalue, err := runtime.ArrayStoreCapacity(arr.Handle)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcapacity = value\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\treturn bridge.ToInt(int64(capacity), runtime.IntegerI32)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif inst := __able_struct_instance(base); inst != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil && inst.Definition.Node.ID.Name == \"Array\" {\n")
	fmt.Fprintf(buf, "\t\t\t\thandleVal, ok := inst.Fields[\"storage_handle\"]\n")
	fmt.Fprintf(buf, "\t\t\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tpanic(fmt.Errorf(\"array value missing storage_handle\"))\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\thandle, err := __able_array_handle_from_value(handleVal)\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\tswitch name {\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"storage_handle\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn handleVal\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"length\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\tlength, err := runtime.ArrayStoreSize(handle)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tval := bridge.ToInt(int64(length), runtime.IntegerI32)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif inst.Fields == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tinst.Fields = map[string]runtime.Value{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tinst.Fields[\"length\"] = val\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t\t\tcase \"capacity\":\n")
	fmt.Fprintf(buf, "\t\t\t\t\tcapacity, err := runtime.ArrayStoreCapacity(handle)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tval := bridge.ToInt(int64(capacity), runtime.IntegerI32)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif inst.Fields == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tinst.Fields = map[string]runtime.Value{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tinst.Fields[\"capacity\"] = val\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif future, ok := base.(*runtime.FutureValue); ok && future != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif val, handled := __able_future_member_value(future, name); handled {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := bridge.MemberGet(__able_runtime, obj, member)\n")
	fmt.Fprintf(buf, "\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_member_get_method(obj runtime.Value, member runtime.Value) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbase := __able_unwrap_interface(obj)\n")
	fmt.Fprintf(buf, "\tif name, ok := __able_member_name(member); ok {\n")
	fmt.Fprintf(buf, "\t\tif future, ok := base.(*runtime.FutureValue); ok && future != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif val, handled := __able_future_member_value(future, name); handled {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tisIface := false\n")
	fmt.Fprintf(buf, "\t\tswitch obj.(type) {\n")
	fmt.Fprintf(buf, "\t\tcase runtime.InterfaceValue, *runtime.InterfaceValue:\n")
	fmt.Fprintf(buf, "\t\t\tisIface = true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif isIface {\n")
	fmt.Fprintf(buf, "\t\t\tswitch typed := obj.(type) {\n")
	fmt.Fprintf(buf, "\t\t\tcase *runtime.InterfaceValue:\n")
	fmt.Fprintf(buf, "\t\t\t\tif typed != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif method, ok := __able_interface_dispatch_method(typed, name); ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn method\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif __able_interface_dispatch_strict {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tifaceName := \"\"\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif typed.Interface != nil && typed.Interface.Node != nil && typed.Interface.Node.ID != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\tifaceName = typed.Interface.Node.ID.Name\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif __able_interface_dispatch_has_entries(ifaceName, name) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\t__able_panic_on_error(fmt.Errorf(\"No matching implementation of %%s.%%s\", ifaceName, name))\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tcase runtime.InterfaceValue:\n")
	fmt.Fprintf(buf, "\t\t\t\tif method, ok := __able_interface_dispatch_method(&typed, name); ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn method\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif __able_interface_dispatch_strict {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tifaceName := \"\"\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif typed.Interface != nil && typed.Interface.Node != nil && typed.Interface.Node.ID != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tifaceName = typed.Interface.Node.ID.Name\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif __able_interface_dispatch_has_entries(ifaceName, name) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(fmt.Errorf(\"No matching implementation of %%s.%%s\", ifaceName, name))\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !isIface {\n")
	fmt.Fprintf(buf, "\t\t\tif inst := __able_struct_instance(base); inst != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tif inst.Fields != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif val, ok := inst.Fields[name]; ok && __able_is_callable_value(val) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\ttypeName := inst.Definition.Node.ID.Name\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif entry := __able_lookup_compiled_method(typeName, name, true); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NativeBoundMethodValue{Receiver: inst, Method: *entry.fn}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tisSingleton := len(inst.Definition.Node.GenericParams) == 0 && (inst.Definition.Node.Kind == ast.StructKindSingleton || (inst.Definition.Node.Kind == ast.StructKindNamed && len(inst.Definition.Node.Fields) == 0))\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif isSingleton {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif entry := __able_lookup_compiled_method(typeName, name, false); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\treturn *entry.fn\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tswitch typed := base.(type) {\n")
	fmt.Fprintf(buf, "\t\t\tcase *runtime.StructDefinitionValue:\n")
	fmt.Fprintf(buf, "\t\t\t\tif typed != nil && typed.Node != nil && typed.Node.ID != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif entry := __able_lookup_compiled_method(typed.Node.ID.Name, name, false); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn *entry.fn\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tcase runtime.StructDefinitionValue:\n")
	fmt.Fprintf(buf, "\t\t\t\tif typed.Node != nil && typed.Node.ID != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif entry := __able_lookup_compiled_method(typed.Node.ID.Name, name, false); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn *entry.fn\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tcase runtime.TypeRefValue:\n")
	fmt.Fprintf(buf, "\t\t\t\tif typed.TypeName != \"\" {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif entry := __able_lookup_compiled_method(typed.TypeName, name, false); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn *entry.fn\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tcase *runtime.TypeRefValue:\n")
	fmt.Fprintf(buf, "\t\t\t\tif typed != nil && typed.TypeName != \"\" {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif entry := __able_lookup_compiled_method(typed.TypeName, name, false); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn *entry.fn\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := bridge.MemberGetPreferMethods(__able_runtime, obj, member)\n")
	fmt.Fprintf(buf, "\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_member(obj runtime.Value, member runtime.Value) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_member_get_method(obj, member)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_call_value(fn runtime.Value, args []runtime.Value, call *ast.FunctionCall) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfor {\n")
	fmt.Fprintf(buf, "\t\tswitch typed := fn.(type) {\n")
	fmt.Fprintf(buf, "\t\tcase runtime.InterfaceValue:\n")
	fmt.Fprintf(buf, "\t\t\tfn = typed.Underlying\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\tcase *runtime.InterfaceValue:\n")
	fmt.Fprintf(buf, "\t\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tfn = runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tfn = typed.Underlying\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\tcase runtime.PartialFunctionValue:\n")
	fmt.Fprintf(buf, "\t\t\tmerged := make([]runtime.Value, 0, len(typed.BoundArgs)+len(args))\n")
	fmt.Fprintf(buf, "\t\t\tmerged = append(merged, typed.BoundArgs...)\n")
	fmt.Fprintf(buf, "\t\t\tmerged = append(merged, args...)\n")
	fmt.Fprintf(buf, "\t\t\targs = merged\n")
	fmt.Fprintf(buf, "\t\t\tfn = typed.Target\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\tcase *runtime.PartialFunctionValue:\n")
	fmt.Fprintf(buf, "\t\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tfn = runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tmerged := make([]runtime.Value, 0, len(typed.BoundArgs)+len(args))\n")
	fmt.Fprintf(buf, "\t\t\tmerged = append(merged, typed.BoundArgs...)\n")
	fmt.Fprintf(buf, "\t\t\tmerged = append(merged, args...)\n")
	fmt.Fprintf(buf, "\t\t\targs = merged\n")
	fmt.Fprintf(buf, "\t\t\tfn = typed.Target\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbreak\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\tbridge.PushCallFrame(__able_runtime, call)\n")
	fmt.Fprintf(buf, "\t\tdefer bridge.PopCallFrame(__able_runtime)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif fn != nil {\n")
	fmt.Fprintf(buf, "\t\tenv := __able_runtime.Env()\n")
	fmt.Fprintf(buf, "\t\tvar state any\n")
	fmt.Fprintf(buf, "\t\tif env != nil {\n")
	fmt.Fprintf(buf, "\t\t\tstate = env.RuntimeData()\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tctx := &runtime.NativeCallContext{Env: env, State: state}\n")
	fmt.Fprintf(buf, "\t\tswitch v := fn.(type) {\n")
	fmt.Fprintf(buf, "\t\tcase runtime.NativeFunctionValue:\n")
	fmt.Fprintf(buf, "\t\t\tif v.Arity >= 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\tif len(args) > v.Arity {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tname := v.Name\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif name == \"\" {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tname = \"(native)\"\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\terr := fmt.Errorf(\"Arity mismatch calling %%s: expected %%d, got %%d\", name, v.Arity, len(args))\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif len(args) < v.Arity {\n")
	fmt.Fprintf(buf, "\t\t\t\t\targsCopy := append([]runtime.Value{}, args...)\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.PartialFunctionValue{Target: v, BoundArgs: argsCopy, Call: call}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tval, err := v.Impl(ctx, args)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\tcase *runtime.NativeFunctionValue:\n")
	fmt.Fprintf(buf, "\t\t\tif v != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tif v.Arity >= 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif len(args) > v.Arity {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tname := v.Name\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif name == \"\" {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\tname = \"(native)\"\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\terr := fmt.Errorf(\"Arity mismatch calling %%s: expected %%d, got %%d\", name, v.Arity, len(args))\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif len(args) < v.Arity {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\targsCopy := append([]runtime.Value{}, args...)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.PartialFunctionValue{Target: v, BoundArgs: argsCopy, Call: call}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tval, err := v.Impl(ctx, args)\n")
	fmt.Fprintf(buf, "\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\tcase runtime.NativeBoundMethodValue:\n")
	fmt.Fprintf(buf, "\t\t\tif v.Method.Arity >= 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\tif len(args) > v.Method.Arity {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tname := v.Method.Name\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif name == \"\" {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tname = \"(native)\"\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\terr := fmt.Errorf(\"Arity mismatch calling %%s: expected %%d, got %%d\", name, v.Method.Arity, len(args))\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif len(args) < v.Method.Arity {\n")
	fmt.Fprintf(buf, "\t\t\t\t\targsCopy := append([]runtime.Value{}, args...)\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.PartialFunctionValue{Target: v, BoundArgs: argsCopy, Call: call}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tinjected := append([]runtime.Value{v.Receiver}, args...)\n")
	fmt.Fprintf(buf, "\t\t\tval, err := v.Method.Impl(ctx, injected)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\tcase *runtime.NativeBoundMethodValue:\n")
	fmt.Fprintf(buf, "\t\t\tif v != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tif v.Method.Arity >= 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif len(args) > v.Method.Arity {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tname := v.Method.Name\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif name == \"\" {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\tname = \"(native)\"\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\terr := fmt.Errorf(\"Arity mismatch calling %%s: expected %%d, got %%d\", name, v.Method.Arity, len(args))\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif len(args) < v.Method.Arity {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\targsCopy := append([]runtime.Value{}, args...)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.PartialFunctionValue{Target: v, BoundArgs: argsCopy, Call: call}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tinjected := append([]runtime.Value{v.Receiver}, args...)\n")
	fmt.Fprintf(buf, "\t\t\t\tval, err := v.Method.Impl(ctx, injected)\n")
	fmt.Fprintf(buf, "\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\tcase runtime.BoundMethodValue:\n")
	fmt.Fprintf(buf, "\t\t\tinjected := append([]runtime.Value{v.Receiver}, args...)\n")
	fmt.Fprintf(buf, "\t\t\tswitch method := v.Method.(type) {\n")
	fmt.Fprintf(buf, "\t\t\tcase *runtime.FunctionValue:\n")
	fmt.Fprintf(buf, "\t\t\t\tif method != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif thunk, ok := method.Bytecode.(func(*runtime.Environment, []runtime.Value) (runtime.Value, error)); ok && thunk != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tval, err := thunk(__able_runtime.Env(), injected)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\tcase *runtime.BoundMethodValue:\n")
	fmt.Fprintf(buf, "\t\t\tif v != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tinjected := append([]runtime.Value{v.Receiver}, args...)\n")
	fmt.Fprintf(buf, "\t\t\t\tswitch method := v.Method.(type) {\n")
	fmt.Fprintf(buf, "\t\t\t\tcase *runtime.FunctionValue:\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif method != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif thunk, ok := method.Bytecode.(func(*runtime.Environment, []runtime.Value) (runtime.Value, error)); ok && thunk != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\tval, err := thunk(__able_runtime.Env(), injected)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\tcase *runtime.FunctionValue:\n")
	fmt.Fprintf(buf, "\t\t\tif v != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tif thunk, ok := v.Bytecode.(func(*runtime.Environment, []runtime.Value) (runtime.Value, error)); ok && thunk != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tval, err := thunk(__able_runtime.Env(), args)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_boundary_name := __able_callable_name(fn)\n")
	fmt.Fprintf(buf, "\t__able_mark_boundary_fallback(__able_boundary_name)\n")
	fmt.Fprintf(buf, "\t__able_mark_boundary_explicit(\"call_value\", __able_boundary_name)\n")
	fmt.Fprintf(buf, "\tval, err := bridge.CallValueWithNode(__able_runtime, fn, args, call)\n")
	fmt.Fprintf(buf, "\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_compiled_call_entry struct {\n")
	fmt.Fprintf(buf, "\tfn      *runtime.NativeFunctionValue\n")
	fmt.Fprintf(buf, "\tarity   int\n")
	fmt.Fprintf(buf, "\tminArgs int\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "var __able_compiled_calls map[*runtime.Environment]map[string]*__able_compiled_call_entry\n\n")
	fmt.Fprintf(buf, "var __able_compiled_callable_names map[string]struct{}\n")
	fmt.Fprintf(buf, "var __able_boundary_fallback_count int64\n\n")
	fmt.Fprintf(buf, "var __able_boundary_fallback_mu sync.Mutex\n")
	fmt.Fprintf(buf, "var __able_boundary_fallback_names map[string]int64\n\n")
	fmt.Fprintf(buf, "var __able_boundary_explicit_count int64\n\n")
	fmt.Fprintf(buf, "var __able_boundary_explicit_mu sync.Mutex\n")
	fmt.Fprintf(buf, "var __able_boundary_explicit_names map[string]int64\n\n")
	fmt.Fprintf(buf, "func __able_register_compiled_call(env *runtime.Environment, name string, arity int, minArgs int, wrapper func(*bridge.Runtime, *runtime.NativeCallContext, []runtime.Value) (runtime.Value, error)) {\n")
	fmt.Fprintf(buf, "\tif env == nil || name == \"\" || wrapper == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif minArgs < 0 {\n")
	fmt.Fprintf(buf, "\t\tminArgs = 0\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_compiled_calls == nil {\n")
	fmt.Fprintf(buf, "\t\t__able_compiled_calls = make(map[*runtime.Environment]map[string]*__able_compiled_call_entry)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_compiled_callable_names == nil {\n")
	fmt.Fprintf(buf, "\t\t__able_compiled_callable_names = make(map[string]struct{})\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_compiled_callable_names[name] = struct{}{}\n")
	fmt.Fprintf(buf, "\tperEnv := __able_compiled_calls[env]\n")
	fmt.Fprintf(buf, "\tif perEnv == nil {\n")
	fmt.Fprintf(buf, "\t\tperEnv = make(map[string]*__able_compiled_call_entry)\n")
	fmt.Fprintf(buf, "\t\t__able_compiled_calls[env] = perEnv\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfn := &runtime.NativeFunctionValue{Name: name, Arity: arity}\n")
	fmt.Fprintf(buf, "\tfn.Impl = func(ctx *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\treturn wrapper(__able_runtime, ctx, args)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tenv.Define(name, fn)\n")
	fmt.Fprintf(buf, "\tperEnv[name] = &__able_compiled_call_entry{fn: fn, arity: arity, minArgs: minArgs}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_lookup_compiled_call(env *runtime.Environment, name string) *__able_compiled_call_entry {\n")
	fmt.Fprintf(buf, "\tif env == nil || name == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_compiled_calls == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfor current := env; current != nil; current = current.Parent() {\n")
	fmt.Fprintf(buf, "\t\tperEnv := __able_compiled_calls[current]\n")
	fmt.Fprintf(buf, "\t\tif perEnv == nil {\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif entry := perEnv[name]; entry != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn entry\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_callable_name(value runtime.Value) string {\n")
	fmt.Fprintf(buf, "\tfor value != nil {\n")
	fmt.Fprintf(buf, "\t\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\t\tcase runtime.NativeFunctionValue:\n")
	fmt.Fprintf(buf, "\t\t\treturn typed.Name\n")
	fmt.Fprintf(buf, "\t\tcase *runtime.NativeFunctionValue:\n")
	fmt.Fprintf(buf, "\t\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn typed.Name\n")
	fmt.Fprintf(buf, "\t\tcase runtime.PartialFunctionValue:\n")
	fmt.Fprintf(buf, "\t\t\tvalue = typed.Target\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\tcase *runtime.PartialFunctionValue:\n")
	fmt.Fprintf(buf, "\t\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tvalue = typed.Target\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\tcase runtime.InterfaceValue:\n")
	fmt.Fprintf(buf, "\t\t\tvalue = typed.Underlying\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\tcase *runtime.InterfaceValue:\n")
	fmt.Fprintf(buf, "\t\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tvalue = typed.Underlying\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn \"\"\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_mark_boundary_fallback(name string) {\n")
	fmt.Fprintf(buf, "\tif name == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_compiled_callable_names == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif _, ok := __able_compiled_callable_names[name]; !ok {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tatomic.AddInt64(&__able_boundary_fallback_count, 1)\n")
	fmt.Fprintf(buf, "\t__able_boundary_fallback_mu.Lock()\n")
	fmt.Fprintf(buf, "\tif __able_boundary_fallback_names == nil {\n")
	fmt.Fprintf(buf, "\t\t__able_boundary_fallback_names = make(map[string]int64)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_boundary_fallback_names[name]++\n")
	fmt.Fprintf(buf, "\t__able_boundary_fallback_mu.Unlock()\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_boundary_fallback_count_get() int64 {\n")
	fmt.Fprintf(buf, "\treturn atomic.LoadInt64(&__able_boundary_fallback_count)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_boundary_fallback_snapshot() string {\n")
	fmt.Fprintf(buf, "\t__able_boundary_fallback_mu.Lock()\n")
	fmt.Fprintf(buf, "\tdefer __able_boundary_fallback_mu.Unlock()\n")
	fmt.Fprintf(buf, "\tif len(__able_boundary_fallback_names) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tkeys := make([]string, 0, len(__able_boundary_fallback_names))\n")
	fmt.Fprintf(buf, "\tfor name := range __able_boundary_fallback_names {\n")
	fmt.Fprintf(buf, "\t\tkeys = append(keys, name)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tsort.Strings(keys)\n")
	fmt.Fprintf(buf, "\tparts := make([]string, 0, len(keys))\n")
	fmt.Fprintf(buf, "\tfor _, name := range keys {\n")
	fmt.Fprintf(buf, "\t\tparts = append(parts, fmt.Sprintf(\"%%s=%%d\", name, __able_boundary_fallback_names[name]))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn strings.Join(parts, \",\")\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_mark_boundary_explicit(kind string, name string) {\n")
	fmt.Fprintf(buf, "\tif strings.TrimSpace(kind) == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tkey := kind\n")
	fmt.Fprintf(buf, "\tif strings.TrimSpace(name) != \"\" {\n")
	fmt.Fprintf(buf, "\t\tkey = kind + \":\" + name\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tatomic.AddInt64(&__able_boundary_explicit_count, 1)\n")
	fmt.Fprintf(buf, "\t__able_boundary_explicit_mu.Lock()\n")
	fmt.Fprintf(buf, "\tif __able_boundary_explicit_names == nil {\n")
	fmt.Fprintf(buf, "\t\t__able_boundary_explicit_names = make(map[string]int64)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_boundary_explicit_names[key]++\n")
	fmt.Fprintf(buf, "\t__able_boundary_explicit_mu.Unlock()\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_boundary_explicit_count_get() int64 {\n")
	fmt.Fprintf(buf, "\treturn atomic.LoadInt64(&__able_boundary_explicit_count)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_boundary_explicit_snapshot() string {\n")
	fmt.Fprintf(buf, "\t__able_boundary_explicit_mu.Lock()\n")
	fmt.Fprintf(buf, "\tdefer __able_boundary_explicit_mu.Unlock()\n")
	fmt.Fprintf(buf, "\tif len(__able_boundary_explicit_names) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tkeys := make([]string, 0, len(__able_boundary_explicit_names))\n")
	fmt.Fprintf(buf, "\tfor name := range __able_boundary_explicit_names {\n")
	fmt.Fprintf(buf, "\t\tkeys = append(keys, name)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tsort.Strings(keys)\n")
	fmt.Fprintf(buf, "\tparts := make([]string, 0, len(keys))\n")
	fmt.Fprintf(buf, "\tfor _, name := range keys {\n")
	fmt.Fprintf(buf, "\t\tparts = append(parts, fmt.Sprintf(\"%%s=%%d\", name, __able_boundary_explicit_names[name]))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn strings.Join(parts, \",\")\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_compiled_method_entry struct {\n")
	fmt.Fprintf(buf, "\tfn      *runtime.NativeFunctionValue\n")
	fmt.Fprintf(buf, "\tarity   int\n")
	fmt.Fprintf(buf, "\tminArgs int\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "var __able_compiled_instance_methods map[string]map[string]*__able_compiled_method_entry\n")
	fmt.Fprintf(buf, "var __able_compiled_static_methods map[string]map[string]*__able_compiled_method_entry\n\n")
	fmt.Fprintf(buf, "func __able_register_compiled_method(typeName string, methodName string, expectsSelf bool, arity int, minArgs int, wrapper func(*bridge.Runtime, *runtime.NativeCallContext, []runtime.Value) (runtime.Value, error)) {\n")
	fmt.Fprintf(buf, "\tif typeName == \"\" || methodName == \"\" || wrapper == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif minArgs < 0 {\n")
	fmt.Fprintf(buf, "\t\tminArgs = 0\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvar bucket map[string]map[string]*__able_compiled_method_entry\n")
	fmt.Fprintf(buf, "\tif expectsSelf {\n")
	fmt.Fprintf(buf, "\t\tif __able_compiled_instance_methods == nil {\n")
	fmt.Fprintf(buf, "\t\t\t__able_compiled_instance_methods = make(map[string]map[string]*__able_compiled_method_entry)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbucket = __able_compiled_instance_methods\n")
	fmt.Fprintf(buf, "\t} else {\n")
	fmt.Fprintf(buf, "\t\tif __able_compiled_static_methods == nil {\n")
	fmt.Fprintf(buf, "\t\t\t__able_compiled_static_methods = make(map[string]map[string]*__able_compiled_method_entry)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbucket = __able_compiled_static_methods\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tperType := bucket[typeName]\n")
	fmt.Fprintf(buf, "\tif perType == nil {\n")
	fmt.Fprintf(buf, "\t\tperType = make(map[string]*__able_compiled_method_entry)\n")
	fmt.Fprintf(buf, "\t\tbucket[typeName] = perType\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfn := &runtime.NativeFunctionValue{Name: methodName, Arity: arity}\n")
	fmt.Fprintf(buf, "\tfn.Impl = func(ctx *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\treturn wrapper(__able_runtime, ctx, args)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tperType[methodName] = &__able_compiled_method_entry{fn: fn, arity: arity, minArgs: minArgs}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_lookup_compiled_method(typeName string, methodName string, expectsSelf bool) *__able_compiled_method_entry {\n")
	fmt.Fprintf(buf, "\tif typeName == \"\" || methodName == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvar bucket map[string]map[string]*__able_compiled_method_entry\n")
	fmt.Fprintf(buf, "\tif expectsSelf {\n")
	fmt.Fprintf(buf, "\t\tbucket = __able_compiled_instance_methods\n")
	fmt.Fprintf(buf, "\t} else {\n")
	fmt.Fprintf(buf, "\t\tbucket = __able_compiled_static_methods\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif bucket == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tperType := bucket[typeName]\n")
	fmt.Fprintf(buf, "\tif perType == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn perType[methodName]\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_call_named(name string, args []runtime.Value, call *ast.FunctionCall) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch name {\n")
	fmt.Fprintf(buf, "\tcase \"future_yield\":\n")
	fmt.Fprintf(buf, "\t\tval, err := __able_future_yield()\n")
	fmt.Fprintf(buf, "\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn val\n")
	fmt.Fprintf(buf, "\tcase \"future_cancelled\":\n")
	fmt.Fprintf(buf, "\t\tval, err := __able_future_cancelled()\n")
	fmt.Fprintf(buf, "\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn val\n")
	fmt.Fprintf(buf, "\tcase \"future_flush\":\n")
	fmt.Fprintf(buf, "\t\treturn __able_future_flush()\n")
	fmt.Fprintf(buf, "\tcase \"future_pending_tasks\":\n")
	fmt.Fprintf(buf, "\t\treturn __able_future_pending_tasks()\n")
	fmt.Fprintf(buf, "\tcase \"__able_await_default\":\n")
	fmt.Fprintf(buf, "\t\tval, err := __able_await_default_impl(args)\n")
	fmt.Fprintf(buf, "\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn val\n")
	fmt.Fprintf(buf, "\tcase \"__able_await_sleep_ms\":\n")
	fmt.Fprintf(buf, "\t\tval, err := __able_await_sleep_ms_impl(args)\n")
	fmt.Fprintf(buf, "\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn val\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif env := __able_runtime.Env(); env != nil {\n")
	fmt.Fprintf(buf, "\t\tif entry := __able_lookup_compiled_call(env, name); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif entry.arity >= 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\tif len(args) < entry.minArgs {\n")
	fmt.Fprintf(buf, "\t\t\t\t\targsCopy := append([]runtime.Value{}, args...)\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.PartialFunctionValue{Target: entry.fn, BoundArgs: argsCopy, Call: call}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif len(args) > entry.arity {\n")
	fmt.Fprintf(buf, "\t\t\t\t\terr := fmt.Errorf(\"Arity mismatch calling %%s: expected %%d, got %%d\", name, entry.arity, len(args))\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif entry.minArgs < entry.arity && len(args) == entry.minArgs {\n")
	fmt.Fprintf(buf, "\t\t\t\t\targs = append(append([]runtime.Value{}, args...), runtime.NilValue{})\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t} else if entry.minArgs > 0 && len(args) < entry.minArgs {\n")
	fmt.Fprintf(buf, "\t\t\t\targsCopy := append([]runtime.Value{}, args...)\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.PartialFunctionValue{Target: entry.fn, BoundArgs: argsCopy, Call: call}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tvar state any\n")
	fmt.Fprintf(buf, "\t\t\tif env != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tstate = env.RuntimeData()\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tctx := &runtime.NativeCallContext{Env: env, State: state}\n")
	fmt.Fprintf(buf, "\t\t\tval, err := entry.fn.Impl(ctx, args)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif resolved, err := env.Get(name); err == nil && resolved != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_call_value(resolved, args, call)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_mark_boundary_fallback(name)\n")
	fmt.Fprintf(buf, "\t__able_mark_boundary_explicit(\"call_named\", name)\n")
	fmt.Fprintf(buf, "\tval, err := bridge.CallNamedWithNode(__able_runtime, name, args, call)\n")
	fmt.Fprintf(buf, "\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_global_get(name string, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := bridge.Get(__able_runtime, name)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, node, err)\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_global_set(name string, value runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif err := bridge.Assign(__able_runtime, name, value); err != nil {\n")
	fmt.Fprintf(buf, "\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, node, err)\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif value == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn value\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_push_call_frame(call *ast.FunctionCall) {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbridge.PushCallFrame(__able_runtime, call)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_pop_call_frame() {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbridge.PopCallFrame(__able_runtime)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_spawn(task func(*runtime.Environment) (runtime.Value, error)) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfuture := __able_spawn_future(task)\n")
	fmt.Fprintf(buf, "\tif future == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn future\n")
	fmt.Fprintf(buf, "}\n\n")
	if len(g.awaitExprs) > 0 {
		fmt.Fprintf(buf, "func __able_await(expr *ast.AwaitExpression, iterable runtime.Value) runtime.Value {\n")
		fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
		fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
		fmt.Fprintf(buf, "\t}\n")
		fmt.Fprintf(buf, "\tval, err := __able_await_value(expr, iterable)\n")
		fmt.Fprintf(buf, "\t__able_panic_on_error(err)\n")
		fmt.Fprintf(buf, "\tif val == nil {\n")
		fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
		fmt.Fprintf(buf, "\t}\n")
		fmt.Fprintf(buf, "\treturn val\n")
		fmt.Fprintf(buf, "}\n\n")
	}
	fmt.Fprintf(buf, "func __able_is_callable_value(val runtime.Value) bool {\n")
	fmt.Fprintf(buf, "\tswitch val.(type) {\n")
	fmt.Fprintf(buf, "\tcase *runtime.FunctionValue, *runtime.FunctionOverloadValue,\n")
	fmt.Fprintf(buf, "\t\truntime.NativeFunctionValue, *runtime.NativeFunctionValue,\n")
	fmt.Fprintf(buf, "\t\truntime.BoundMethodValue, *runtime.BoundMethodValue,\n")
	fmt.Fprintf(buf, "\t\truntime.NativeBoundMethodValue, *runtime.NativeBoundMethodValue,\n")
	fmt.Fprintf(buf, "\t\truntime.PartialFunctionValue, *runtime.PartialFunctionValue:\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_member_name(member runtime.Value) (string, bool) {\n")
	fmt.Fprintf(buf, "\tval := __able_unwrap_interface(member)\n")
	fmt.Fprintf(buf, "\tswitch v := val.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.StringValue:\n")
	fmt.Fprintf(buf, "\t\treturn v.Val, true\n")
	fmt.Fprintf(buf, "\tcase *runtime.StringValue:\n")
	fmt.Fprintf(buf, "\t\tif v == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn \"\", false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn v.Val, true\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn \"\", false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
}
