package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderRuntimeCallHelpersTail(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "func __able_register_compiled_call(env *runtime.Environment, name string, arity int, minArgs int, ufcsTarget string, wrapper func(*bridge.Runtime, *runtime.NativeCallContext, []runtime.Value) (runtime.Value, error)) {\n")
	fmt.Fprintf(buf, "\tif env == nil || name == \"\" || wrapper == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif minArgs < 0 {\n")
	fmt.Fprintf(buf, "\t\tminArgs = 0\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_compiled_calls == nil {\n")
	fmt.Fprintf(buf, "\t\t__able_compiled_calls = make(map[*runtime.Environment]map[string]*__able_compiled_call_entry)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif strings.TrimSpace(ufcsTarget) != \"\" {\n")
	fmt.Fprintf(buf, "\t\tif __able_compiled_ufcs_targets == nil {\n")
	fmt.Fprintf(buf, "\t\t\t__able_compiled_ufcs_targets = make(map[string]map[string]struct{})\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\ttargets := __able_compiled_ufcs_targets[name]\n")
	fmt.Fprintf(buf, "\t\tif targets == nil {\n")
	fmt.Fprintf(buf, "\t\t\ttargets = make(map[string]struct{})\n")
	fmt.Fprintf(buf, "\t\t\t__able_compiled_ufcs_targets[name] = targets\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\ttargets[strings.TrimSpace(ufcsTarget)] = struct{}{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_compiled_callable_names == nil {\n")
	fmt.Fprintf(buf, "\t\t__able_compiled_callable_names = make(map[string]struct{})\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_compiled_callable_names[name] = struct{}{}\n")
	fmt.Fprintf(buf, "\tperEnv := __able_compiled_calls[env]\n")
	fmt.Fprintf(buf, "\tif perEnv == nil {\n")
	fmt.Fprintf(buf, "\t\tperEnv = make(map[string]*__able_compiled_call_entry)\n")
	fmt.Fprintf(buf, "\t\t__able_compiled_calls[env] = perEnv\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfn := &runtime.NativeFunctionValue{Name: name, Arity: arity}\n")
	fmt.Fprintf(buf, "\tfn.Impl = func(ctx *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\treturn wrapper(__able_runtime, ctx, args)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tenv.Define(name, fn)\n")
	fmt.Fprintf(buf, "\tperEnv[name] = &__able_compiled_call_entry{fn: fn, arity: arity, minArgs: minArgs, ufcsTarget: strings.TrimSpace(ufcsTarget)}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_compiled_ufcs_target_exists(name string, target string) bool {\n")
	fmt.Fprintf(buf, "\tname = strings.TrimSpace(name)\n")
	fmt.Fprintf(buf, "\ttarget = strings.TrimSpace(target)\n")
	fmt.Fprintf(buf, "\tif name == \"\" || target == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_compiled_ufcs_targets == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\ttargets := __able_compiled_ufcs_targets[name]\n")
	fmt.Fprintf(buf, "\tif len(targets) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t_, ok := targets[target]\n")
	fmt.Fprintf(buf, "\treturn ok\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_lookup_compiled_call(env *runtime.Environment, name string) *__able_compiled_call_entry {\n")
	fmt.Fprintf(buf, "\tif env == nil || name == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_compiled_calls == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfor current := env; current != nil; current = current.Parent() {\n")
	fmt.Fprintf(buf, "\t\tperEnv := __able_compiled_calls[current]\n")
	fmt.Fprintf(buf, "\t\tif perEnv == nil {\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif entry := perEnv[name]; entry != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn entry\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_callable_name(value runtime.Value) string {\n")
	fmt.Fprintf(buf, "\tfor value != nil {\n")
	fmt.Fprintf(buf, "\t\tif native, ok, nilPtr := __able_callable_native_function_value(value); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn native.Name\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif nativeBound, ok, nilPtr := __able_callable_native_bound_method_value(value); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif strings.TrimSpace(nativeBound.Method.Name) != \"\" {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn nativeBound.Method.Name\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tvalue = nativeBound.Method\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif bound, ok, nilPtr := __able_callable_bound_method_value(value); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tvalue = bound.Method\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif partial, ok, nilPtr := __able_callable_partial_value(value); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tvalue = partial.Target\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif iface, ok, nilPtr := __able_callable_interface_value(value); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tvalue = iface.Underlying\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn \"\"\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_mark_boundary_fallback(name string) {\n")
	fmt.Fprintf(buf, "\tif name == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_compiled_callable_names == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif _, ok := __able_compiled_callable_names[name]; !ok {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tatomic.AddInt64(&__able_boundary_fallback_count, 1)\n")
	fmt.Fprintf(buf, "\t__able_boundary_fallback_mu.Lock()\n")
	fmt.Fprintf(buf, "\tif __able_boundary_fallback_names == nil {\n")
	fmt.Fprintf(buf, "\t\t__able_boundary_fallback_names = make(map[string]int64)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_boundary_fallback_names[name]++\n")
	fmt.Fprintf(buf, "\t__able_boundary_fallback_mu.Unlock()\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_boundary_fallback_count_get() int64 {\n")
	fmt.Fprintf(buf, "\treturn atomic.LoadInt64(&__able_boundary_fallback_count)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_boundary_fallback_snapshot() string {\n")
	fmt.Fprintf(buf, "\t__able_boundary_fallback_mu.Lock()\n")
	fmt.Fprintf(buf, "\tdefer __able_boundary_fallback_mu.Unlock()\n")
	fmt.Fprintf(buf, "\tif len(__able_boundary_fallback_names) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tkeys := make([]string, 0, len(__able_boundary_fallback_names))\n")
	fmt.Fprintf(buf, "\tfor name := range __able_boundary_fallback_names {\n")
	fmt.Fprintf(buf, "\t\tkeys = append(keys, name)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tsort.Strings(keys)\n")
	fmt.Fprintf(buf, "\tparts := make([]string, 0, len(keys))\n")
	fmt.Fprintf(buf, "\tfor _, name := range keys {\n")
	fmt.Fprintf(buf, "\t\tparts = append(parts, fmt.Sprintf(\"%%s=%%d\", name, __able_boundary_fallback_names[name]))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn strings.Join(parts, \",\")\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_mark_boundary_explicit(kind string, name string) {\n")
	fmt.Fprintf(buf, "\tif strings.TrimSpace(kind) == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tkey := kind\n")
	fmt.Fprintf(buf, "\tif strings.TrimSpace(name) != \"\" {\n")
	fmt.Fprintf(buf, "\t\tkey = kind + \":\" + name\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tatomic.AddInt64(&__able_boundary_explicit_count, 1)\n")
	fmt.Fprintf(buf, "\t__able_boundary_explicit_mu.Lock()\n")
	fmt.Fprintf(buf, "\tif __able_boundary_explicit_names == nil {\n")
	fmt.Fprintf(buf, "\t\t__able_boundary_explicit_names = make(map[string]int64)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_boundary_explicit_names[key]++\n")
	fmt.Fprintf(buf, "\t__able_boundary_explicit_mu.Unlock()\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_boundary_explicit_count_get() int64 {\n")
	fmt.Fprintf(buf, "\treturn atomic.LoadInt64(&__able_boundary_explicit_count)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_boundary_explicit_snapshot() string {\n")
	fmt.Fprintf(buf, "\t__able_boundary_explicit_mu.Lock()\n")
	fmt.Fprintf(buf, "\tdefer __able_boundary_explicit_mu.Unlock()\n")
	fmt.Fprintf(buf, "\tif len(__able_boundary_explicit_names) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn \"\"\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tkeys := make([]string, 0, len(__able_boundary_explicit_names))\n")
	fmt.Fprintf(buf, "\tfor name := range __able_boundary_explicit_names {\n")
	fmt.Fprintf(buf, "\t\tkeys = append(keys, name)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tsort.Strings(keys)\n")
	fmt.Fprintf(buf, "\tparts := make([]string, 0, len(keys))\n")
	fmt.Fprintf(buf, "\tfor _, name := range keys {\n")
	fmt.Fprintf(buf, "\t\tparts = append(parts, fmt.Sprintf(\"%%s=%%d\", name, __able_boundary_explicit_names[name]))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn strings.Join(parts, \",\")\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_compiled_method_entry struct {\n")
	fmt.Fprintf(buf, "\tfn      *runtime.NativeFunctionValue\n")
	fmt.Fprintf(buf, "\tarity   int\n")
	fmt.Fprintf(buf, "\tminArgs int\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "var __able_compiled_instance_methods map[string]map[string]*__able_compiled_method_entry\n")
	fmt.Fprintf(buf, "var __able_compiled_static_methods map[string]map[string]*__able_compiled_method_entry\n\n")
	fmt.Fprintf(buf, "func __able_register_compiled_method(typeName string, methodName string, expectsSelf bool, arity int, minArgs int, wrapper func(*bridge.Runtime, *runtime.NativeCallContext, []runtime.Value) (runtime.Value, error)) {\n")
	fmt.Fprintf(buf, "\tif typeName == \"\" || methodName == \"\" || wrapper == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif minArgs < 0 {\n")
	fmt.Fprintf(buf, "\t\tminArgs = 0\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvar bucket map[string]map[string]*__able_compiled_method_entry\n")
	fmt.Fprintf(buf, "\tif expectsSelf {\n")
	fmt.Fprintf(buf, "\t\tif __able_compiled_instance_methods == nil {\n")
	fmt.Fprintf(buf, "\t\t\t__able_compiled_instance_methods = make(map[string]map[string]*__able_compiled_method_entry)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbucket = __able_compiled_instance_methods\n")
	fmt.Fprintf(buf, "\t} else {\n")
	fmt.Fprintf(buf, "\t\tif __able_compiled_static_methods == nil {\n")
	fmt.Fprintf(buf, "\t\t\t__able_compiled_static_methods = make(map[string]map[string]*__able_compiled_method_entry)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbucket = __able_compiled_static_methods\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tperType := bucket[typeName]\n")
	fmt.Fprintf(buf, "\tif perType == nil {\n")
	fmt.Fprintf(buf, "\t\tperType = make(map[string]*__able_compiled_method_entry)\n")
	fmt.Fprintf(buf, "\t\tbucket[typeName] = perType\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfn := &runtime.NativeFunctionValue{Name: methodName, Arity: arity}\n")
	fmt.Fprintf(buf, "\tfn.Impl = func(ctx *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\treturn wrapper(__able_runtime, ctx, args)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tperType[methodName] = &__able_compiled_method_entry{fn: fn, arity: arity, minArgs: minArgs}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_lookup_compiled_method(typeName string, methodName string, expectsSelf bool) *__able_compiled_method_entry {\n")
	fmt.Fprintf(buf, "\tif typeName == \"\" || methodName == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvar bucket map[string]map[string]*__able_compiled_method_entry\n")
	fmt.Fprintf(buf, "\tif expectsSelf {\n")
	fmt.Fprintf(buf, "\t\tbucket = __able_compiled_instance_methods\n")
	fmt.Fprintf(buf, "\t} else {\n")
	fmt.Fprintf(buf, "\t\tbucket = __able_compiled_static_methods\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif bucket == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tperType := bucket[typeName]\n")
	fmt.Fprintf(buf, "\tif perType != nil {\n")
	fmt.Fprintf(buf, "\t\tif entry := perType[methodName]; entry != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn entry\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif strings.HasPrefix(typeName, \"Kernel\") {\n")
	fmt.Fprintf(buf, "\t\tif alias := strings.TrimSpace(strings.TrimPrefix(typeName, \"Kernel\")); alias != \"\" {\n")
	fmt.Fprintf(buf, "\t\t\tif perAlias := bucket[alias]; perAlias != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tif entry := perAlias[methodName]; entry != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn entry\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_integer_clone(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"clone expects only a receiver\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif args[0] == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn args[0], nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_integer_to_string(rt *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"to_string expects only a receiver\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif rt == nil {\n")
	fmt.Fprintf(buf, "\t\trt = __able_runtime\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif rt == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"compiler: missing runtime\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\ttext, err := bridge.Stringify(rt, args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.StringValue{Val: text}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_iterator_next(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"next expects only a receiver\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treceiver, ok, nilPtr := __able_runtime_iterator_value(args[0])\n")
	fmt.Fprintf(buf, "\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"next receiver must be an iterator\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvalue, done, err := receiver.Next()\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif done {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.IteratorEnd, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif value == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn value, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_future_receiver(args []runtime.Value, member string) (*runtime.FutureValue, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"%%s requires receiver\", member)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\trecv, ok, nilPtr := __able_runtime_future_value(args[0])\n")
	fmt.Fprintf(buf, "\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"%%s receiver must be a future\", member)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn recv, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_future_status(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\trecv, err := __able_builtin_future_receiver(args, \"status\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn __able_future_status_value(recv), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_future_value(_ *bridge.Runtime, ctx *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\trecv, err := __able_builtin_future_receiver(args, \"value\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tpayload := __able_payload_from_ctx(ctx)\n")
	fmt.Fprintf(buf, "\treturn __able_future_value_with_payload(recv, payload), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_future_cancel(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\trecv, err := __able_builtin_future_receiver(args, \"cancel\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn __able_future_cancel(recv), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_future_is_ready(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\trecv, err := __able_builtin_future_receiver(args, \"is_ready\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.BoolValue{Val: recv.Status() != runtime.FuturePending}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_future_register(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\trecv, err := __able_builtin_future_receiver(args, \"register\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(args) < 2 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"register requires receiver and waker\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn __able_future_register_awaiter(recv, args[1])\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_future_commit(_ *bridge.Runtime, ctx *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\trecv, err := __able_builtin_future_receiver(args, \"commit\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tpayload := __able_payload_from_ctx(ctx)\n")
	fmt.Fprintf(buf, "\treturn __able_future_value_with_payload(recv, payload), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_future_is_default(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t_, err := __able_builtin_future_receiver(args, \"is_default\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.BoolValue{Val: false}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_dynpackage_member_call(rt *bridge.Runtime, args []runtime.Value, member string) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) < 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"DynPackage.%%s expects a receiver\", member)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif rt == nil {\n")
	fmt.Fprintf(buf, "\t\trt = __able_runtime\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif rt == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"compiler: missing runtime\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treceiver := args[0]\n")
	fmt.Fprintf(buf, "\tif dyn, ok, nilPtr := __able_runtime_dynpackage_value(receiver); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"DynPackage.%%s receiver must be a dynamic package\", member)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treceiver = dyn\n")
	fmt.Fprintf(buf, "\t} else {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"DynPackage.%%s receiver must be a dynamic package\", member)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tmethod, err := bridge.MemberGet(rt, receiver, runtime.StringValue{Val: member})\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif method == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.CallValue(rt, method, args[1:])\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_dynpackage_def(rt *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\treturn __able_builtin_dynpackage_member_call(rt, args, \"def\")\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_dynpackage_eval(rt *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\treturn __able_builtin_dynpackage_member_call(rt, args, \"eval\")\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_error_receiver(args []runtime.Value, member string) (runtime.ErrorValue, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.ErrorValue{}, fmt.Errorf(\"Error.%%s expects only a receiver\", member)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif recv, ok, nilPtr := __able_runtime_error_value(args[0]); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.ErrorValue{}, fmt.Errorf(\"Error.%%s receiver must be an error value\", member)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn recv, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.ErrorValue{}, fmt.Errorf(\"Error.%%s receiver must be an error value\", member)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_error_message(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\trecv, err := __able_builtin_error_receiver(args, \"message\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.StringValue{Val: recv.Message}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_error_cause(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\trecv, err := __able_builtin_error_receiver(args, \"cause\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif recv.Payload != nil {\n")
	fmt.Fprintf(buf, "\t\tif cause, ok := recv.Payload[\"cause\"]; ok && cause != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn cause, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_named_future_yield(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"future_yield expects no arguments\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := __able_future_yield()\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_named_future_cancelled(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"future_cancelled expects no arguments\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := __able_future_cancelled()\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_named_future_flush(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"future_flush expects no arguments\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval := __able_future_flush()\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_named_future_pending_tasks(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"future_pending_tasks expects no arguments\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval := __able_future_pending_tasks()\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_named_await_default(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tval, err := __able_await_default_impl(args)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_builtin_named_await_sleep_ms(_ *bridge.Runtime, _ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tval, err := __able_await_sleep_ms_impl(args)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_register_builtin_compiled_calls(entryEnv *runtime.Environment, interp *interpreter.Interpreter) {\n")
	fmt.Fprintf(buf, "\tregisterIn := func(env *runtime.Environment) {\n")
	fmt.Fprintf(buf, "\t\tif env == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\t__able_register_compiled_call(env, \"future_yield\", 0, 0, \"\", __able_builtin_named_future_yield)\n")
	fmt.Fprintf(buf, "\t\t__able_register_compiled_call(env, \"future_cancelled\", 0, 0, \"\", __able_builtin_named_future_cancelled)\n")
	fmt.Fprintf(buf, "\t\t__able_register_compiled_call(env, \"future_flush\", 0, 0, \"\", __able_builtin_named_future_flush)\n")
	fmt.Fprintf(buf, "\t\t__able_register_compiled_call(env, \"future_pending_tasks\", 0, 0, \"\", __able_builtin_named_future_pending_tasks)\n")
	fmt.Fprintf(buf, "\t\t__able_register_compiled_call(env, \"__able_await_default\", -1, 0, \"\", __able_builtin_named_await_default)\n")
	fmt.Fprintf(buf, "\t\t__able_register_compiled_call(env, \"__able_await_sleep_ms\", -1, 1, \"\", __able_builtin_named_await_sleep_ms)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tregisterIn(entryEnv)\n")
	fmt.Fprintf(buf, "\tif interp != nil {\n")
	fmt.Fprintf(buf, "\t\tif global := interp.GlobalEnvironment(); global != nil && global != entryEnv {\n")
	fmt.Fprintf(buf, "\t\t\tregisterIn(global)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_register_builtin_compiled_methods() {\n")
	fmt.Fprintf(buf, "\tintegerTypes := []string{\"i8\", \"i16\", \"i32\", \"i64\", \"i128\", \"u8\", \"u16\", \"u32\", \"u64\", \"u128\", \"isize\", \"usize\"}\n")
	fmt.Fprintf(buf, "\tfor _, typeName := range integerTypes {\n")
	fmt.Fprintf(buf, "\t\t__able_register_compiled_method(typeName, \"clone\", true, 0, 0, __able_builtin_integer_clone)\n")
	fmt.Fprintf(buf, "\t\t__able_register_compiled_method(typeName, \"to_string\", true, 0, 0, __able_builtin_integer_to_string)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_register_compiled_method(\"Future\", \"status\", true, 0, 0, __able_builtin_future_status)\n")
	fmt.Fprintf(buf, "\t__able_register_compiled_method(\"Future\", \"value\", true, 0, 0, __able_builtin_future_value)\n")
	fmt.Fprintf(buf, "\t__able_register_compiled_method(\"Future\", \"cancel\", true, 0, 0, __able_builtin_future_cancel)\n")
	fmt.Fprintf(buf, "\t__able_register_compiled_method(\"Future\", \"is_ready\", true, 0, 0, __able_builtin_future_is_ready)\n")
	fmt.Fprintf(buf, "\t__able_register_compiled_method(\"Future\", \"register\", true, 1, 1, __able_builtin_future_register)\n")
	fmt.Fprintf(buf, "\t__able_register_compiled_method(\"Future\", \"commit\", true, 0, 0, __able_builtin_future_commit)\n")
	fmt.Fprintf(buf, "\t__able_register_compiled_method(\"Future\", \"is_default\", true, 0, 0, __able_builtin_future_is_default)\n")
	fmt.Fprintf(buf, "\t__able_register_compiled_method(\"Iterator\", \"next\", true, 0, 0, __able_builtin_iterator_next)\n")
	fmt.Fprintf(buf, "\t__able_register_compiled_method(\"DynPackage\", \"def\", true, 1, 1, __able_builtin_dynpackage_def)\n")
	fmt.Fprintf(buf, "\t__able_register_compiled_method(\"DynPackage\", \"eval\", true, 1, 1, __able_builtin_dynpackage_eval)\n")
	fmt.Fprintf(buf, "\t__able_register_compiled_method(\"Error\", \"message\", true, 0, 0, __able_builtin_error_message)\n")
	fmt.Fprintf(buf, "\t__able_register_compiled_method(\"Error\", \"cause\", true, 0, 0, __able_builtin_error_cause)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_resolve_qualified_callable(name string, env *runtime.Environment) (runtime.Value, bool, error) {\n")
	fmt.Fprintf(buf, "\tif strings.TrimSpace(name) == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tdot := strings.Index(name, \".\")\n")
	fmt.Fprintf(buf, "\tif dot <= 0 || dot >= len(name)-1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thead := name[:dot]\n")
	fmt.Fprintf(buf, "\ttail := name[dot+1:]\n")
	fmt.Fprintf(buf, "\tif head == \"\" || tail == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tlookupStatic := func(typeName string) (runtime.Value, bool) {\n")
	fmt.Fprintf(buf, "\t\tif typeName == \"\" {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif entry := __able_lookup_compiled_method(typeName, tail, false); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn *entry.fn, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tresolveReceiver := func(receiver runtime.Value) (runtime.Value, bool) {\n")
	fmt.Fprintf(buf, "\t\tswitch typed := receiver.(type) {\n")
	fmt.Fprintf(buf, "\t\tcase runtime.ImplementationNamespaceValue:\n")
	fmt.Fprintf(buf, "\t\t\tif typed.Methods != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tif method, ok := typed.Methods[tail]; ok && method != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn method, true\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tcandidate := __able_member_get_method(receiver, runtime.StringValue{Val: tail})\n")
	fmt.Fprintf(buf, "\t\tif !__able_is_nil(candidate) {\n")
	fmt.Fprintf(buf, "\t\t\treturn candidate, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif env != nil {\n")
	fmt.Fprintf(buf, "\t\tif receiver, err := env.Get(head); err == nil && receiver != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif method, ok := resolveReceiver(receiver); ok {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn method, true, nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif def, ok := env.StructDefinition(head); ok && def != nil {\n")
	fmt.Fprintf(buf, "\t\t\tstructTypeName := head\n")
	fmt.Fprintf(buf, "\t\t\tif def.Node != nil && def.Node.ID != nil && def.Node.ID.Name != \"\" {\n")
	fmt.Fprintf(buf, "\t\t\t\tstructTypeName = def.Node.ID.Name\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif method, ok := lookupStatic(structTypeName); ok {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn method, true, nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif method, ok := lookupStatic(head); ok {\n")
	fmt.Fprintf(buf, "\t\treturn method, true, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil, false, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_call_named(name string, args []runtime.Value, call *ast.FunctionCall) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif env := __able_runtime.Env(); env != nil {\n")
	fmt.Fprintf(buf, "\t\tif entry := __able_lookup_compiled_call(env, name); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif entry.arity >= 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\tif len(args) < entry.minArgs {\n")
	fmt.Fprintf(buf, "\t\t\t\t\targsCopy := append([]runtime.Value{}, args...)\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.PartialFunctionValue{Target: entry.fn, BoundArgs: argsCopy, Call: call}\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif len(args) > entry.arity {\n")
	fmt.Fprintf(buf, "\t\t\t\t\terr := fmt.Errorf(\"Arity mismatch calling %%s: expected %%d, got %%d\", name, entry.arity, len(args))\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif entry.minArgs < entry.arity && len(args) == entry.minArgs {\n")
	fmt.Fprintf(buf, "\t\t\t\t\targs = append(append([]runtime.Value{}, args...), runtime.NilValue{})\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t} else if entry.minArgs > 0 && len(args) < entry.minArgs {\n")
	fmt.Fprintf(buf, "\t\t\t\targsCopy := append([]runtime.Value{}, args...)\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.PartialFunctionValue{Target: entry.fn, BoundArgs: argsCopy, Call: call}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tvar state any\n")
	fmt.Fprintf(buf, "\t\t\tif env != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tstate = env.RuntimeData()\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tctx := &runtime.NativeCallContext{Env: env, State: state}\n")
	fmt.Fprintf(buf, "\t\t\tval, err := entry.fn.Impl(ctx, args)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif resolved, err := env.Get(name); err == nil && resolved != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_call_value(resolved, args, call)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\t// UFCS fallback: if name(receiver, ...) isn't a known function, check if\n")
	fmt.Fprintf(buf, "\t\t// receiver's type has a compiled method matching the name.\n")
	fmt.Fprintf(buf, "\t\tif len(args) > 0 {\n")
	fmt.Fprintf(buf, "\t\t\treceiverTypeName := __able_runtime_value_type_name(args[0])\n")
	fmt.Fprintf(buf, "\t\t\tif receiverTypeName != \"\" {\n")
	fmt.Fprintf(buf, "\t\t\t\tif entry := __able_lookup_compiled_method(receiverTypeName, name, true); entry != nil && entry.fn != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tvar state any\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif env != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tstate = env.RuntimeData()\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tctx := &runtime.NativeCallContext{Env: env, State: state}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tval, err := entry.fn.Impl(ctx, args)\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn val\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif !__able_allow_dynamic_bridge {\n")
	fmt.Fprintf(buf, "\t\terr := fmt.Errorf(\"compiler: unresolved static call %%s\", name)\n")
	fmt.Fprintf(buf, "\t\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, call, err)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_mark_boundary_fallback(name)\n")
	fmt.Fprintf(buf, "\t__able_mark_boundary_explicit(\"call_named\", name)\n")
	fmt.Fprintf(buf, "\tval, err := bridge.CallNamedWithNode(__able_runtime, name, args, call)\n")
	fmt.Fprintf(buf, "\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_env_get(name string, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := bridge.Get(__able_runtime, name)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, node, err)\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_env_set(name string, value runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif err := bridge.Assign(__able_runtime, name, value); err != nil {\n")
	fmt.Fprintf(buf, "\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, node, err)\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif value == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn value\n")
	fmt.Fprintf(buf, "}\n\n")
	// __able_match_singleton checks if a runtime value matches a singleton struct by name.
	// Works for both StructDefinitionValue (interpreter representation) and
	// StructInstanceValue (compiled representation) of singleton structs.
	fmt.Fprintf(buf, "func __able_match_singleton(val runtime.Value, name string) bool {\n")
	fmt.Fprintf(buf, "\tif val == nil || name == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif def, ok := val.(*runtime.StructDefinitionValue); ok {\n")
	fmt.Fprintf(buf, "\t\treturn def != nil && def.Node != nil && def.Node.ID != nil && def.Node.ID.Name == name\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif def, ok := val.(runtime.StructDefinitionValue); ok {\n")
	fmt.Fprintf(buf, "\t\treturn def.Node != nil && def.Node.ID != nil && def.Node.ID.Name == name\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif inst := __able_struct_instance(val); inst != nil {\n")
	fmt.Fprintf(buf, "\t\treturn inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil && inst.Definition.Node.ID.Name == name\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn false\n")
	fmt.Fprintf(buf, "}\n\n")

	// __able_impl_self_method creates a bound method value that dispatches to a
	// specific impl sibling method. Used by default interface methods to call
	// other methods in the same named impl (e.g., describe() calling self.name()
	// through the Fancy impl).
	fmt.Fprintf(buf, "func __able_impl_self_method(receiver runtime.Value, name string, arity int, wrap func(*bridge.Runtime, *runtime.NativeCallContext, []runtime.Value) (runtime.Value, error)) runtime.Value {\n")
	// The arity accounts for the bound receiver being injected automatically,
	// so subtract 1 from the total method arity for the caller-facing check.
	fmt.Fprintf(buf, "\tboundArity := arity - 1\n")
	fmt.Fprintf(buf, "\tif boundArity < -1 { boundArity = -1 }\n")
	fmt.Fprintf(buf, "\tfn := &runtime.NativeFunctionValue{Name: name, Arity: boundArity}\n")
	fmt.Fprintf(buf, "\tfn.Impl = func(ctx *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\treturn wrap(__able_runtime, ctx, args)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.NativeBoundMethodValue{Receiver: receiver, Method: *fn}\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "func __able_push_call_frame(call *ast.FunctionCall) {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbridge.PushCallFrame(__able_runtime, call)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_pop_call_frame() {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbridge.PopCallFrame(__able_runtime)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_spawn(task func(*runtime.Environment) (runtime.Value, error)) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_runtime.MarkConcurrent()\n")
	fmt.Fprintf(buf, "\tfuture := __able_spawn_future(task)\n")
	fmt.Fprintf(buf, "\tif future == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn future\n")
	fmt.Fprintf(buf, "}\n\n")
	if len(g.awaitExprs) > 0 {
		fmt.Fprintf(buf, "func __able_await(expr *ast.AwaitExpression, iterable runtime.Value) runtime.Value {\n")
		fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
		fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
		fmt.Fprintf(buf, "\t}\n")
		fmt.Fprintf(buf, "\tval, err := __able_await_value(expr, iterable)\n")
		fmt.Fprintf(buf, "\t__able_panic_on_error(err)\n")
		fmt.Fprintf(buf, "\tif val == nil {\n")
		fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
		fmt.Fprintf(buf, "\t}\n")
		fmt.Fprintf(buf, "\treturn val\n")
		fmt.Fprintf(buf, "}\n\n")
	}
	fmt.Fprintf(buf, "func __able_is_callable_value(val runtime.Value) bool {\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif _, ok, nilPtr := __able_callable_function_value(val); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif _, ok, nilPtr := __able_callable_function_overload_value(val); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif _, ok, nilPtr := __able_callable_native_function_value(val); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif _, ok, nilPtr := __able_callable_native_bound_method_value(val); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif _, ok, nilPtr := __able_callable_bound_method_value(val); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif _, ok, nilPtr := __able_callable_partial_value(val); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn false\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_runtime_array_value(value runtime.Value) (*runtime.ArrayValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\tcase *runtime.ArrayValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_runtime_string_value(value runtime.Value) (runtime.StringValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.StringValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tcase *runtime.StringValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.StringValue{}, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn *typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.StringValue{}, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_runtime_char_value(value runtime.Value) (runtime.CharValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.CharValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tcase *runtime.CharValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.CharValue{}, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn *typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.CharValue{}, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_runtime_iterator_value(value runtime.Value) (*runtime.IteratorValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\tcase *runtime.IteratorValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_runtime_future_value(value runtime.Value) (*runtime.FutureValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\tcase *runtime.FutureValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_runtime_error_value(value runtime.Value) (runtime.ErrorValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.ErrorValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tcase *runtime.ErrorValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.ErrorValue{}, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn *typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.ErrorValue{}, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_runtime_dynpackage_value(value runtime.Value) (runtime.DynPackageValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.DynPackageValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tcase *runtime.DynPackageValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.DynPackageValue{}, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn *typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.DynPackageValue{}, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_runtime_struct_instance_value(value runtime.Value) (*runtime.StructInstanceValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\tcase *runtime.StructInstanceValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn nil, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_runtime_nil_value(value runtime.Value) (runtime.NilValue, bool, bool) {\n")
	fmt.Fprintf(buf, "\tswitch typed := value.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.NilValue:\n")
	fmt.Fprintf(buf, "\t\treturn typed, true, false\n")
	fmt.Fprintf(buf, "\tcase *runtime.NilValue:\n")
	fmt.Fprintf(buf, "\t\tif typed == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, false, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn *typed, true, false\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, false, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_member_name(member runtime.Value) (string, bool) {\n")
	fmt.Fprintf(buf, "\tval := __able_unwrap_interface(member)\n")
	fmt.Fprintf(buf, "\tif str, ok, nilPtr := __able_runtime_string_value(val); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn \"\", false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn str.Val, true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn \"\", false\n")
	fmt.Fprintf(buf, "}\n\n")
}
