package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderRuntimeConcurrencyHelpers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "var __able_concurrency_error_defs map[string]*runtime.StructDefinitionValue\n\n")
	fmt.Fprintf(buf, "type __able_channel_awaitable struct {\n")
	fmt.Fprintf(buf, "\thandle       int64\n")
	fmt.Fprintf(buf, "\top           __able_channel_await_kind\n")
	fmt.Fprintf(buf, "\tpayload      runtime.Value\n")
	fmt.Fprintf(buf, "\tcallback     runtime.Value\n")
	fmt.Fprintf(buf, "\tregistration *__able_channel_await_registration\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (a *__able_channel_awaitable) isReady() (bool, error) {\n")
	fmt.Fprintf(buf, "\tif a == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false, fmt.Errorf(\"awaitable not initialized\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif a.handle == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.ChannelStoreState(a.handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn false, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tclosed, err := runtime.ChannelStoreIsClosed(a.handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn false, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tlength := len(state.Ch)\n")
	fmt.Fprintf(buf, "\tcapacity := state.Capacity\n")
	fmt.Fprintf(buf, "\tsendWaiters, recvWaiters, sendAwaiters, recvAwaiters := __able_channel_await_snapshot(a.handle)\n")
	fmt.Fprintf(buf, "\tswitch a.op {\n")
	fmt.Fprintf(buf, "\tcase __able_channel_await_recv:\n")
	fmt.Fprintf(buf, "\t\tif length > 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn true, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif capacity == 0 && (sendWaiters > 0 || sendAwaiters > 0) {\n")
	fmt.Fprintf(buf, "\t\t\treturn true, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif closed {\n")
	fmt.Fprintf(buf, "\t\t\treturn true, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn false, nil\n")
	fmt.Fprintf(buf, "\tcase __able_channel_await_send:\n")
	fmt.Fprintf(buf, "\t\tif closed {\n")
	fmt.Fprintf(buf, "\t\t\tbridge.Raise(__able_concurrency_error_value(\"ChannelSendOnClosed\", \"send on closed channel\"))\n")
	fmt.Fprintf(buf, "\t\t\treturn false, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif capacity == 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn recvWaiters > 0 || recvAwaiters > 0, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn length < capacity, nil\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn false, fmt.Errorf(\"unknown awaitable operation\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (a *__able_channel_awaitable) register(waker runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif a == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"awaitable not initialized\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif a.handle == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn __able_make_await_registration_value(nil), nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif a.registration != nil {\n")
	fmt.Fprintf(buf, "\t\treturn __able_make_await_registration_value(a.registration.cancel), nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treg := __able_add_channel_awaiter(a.handle, a.op, waker)\n")
	fmt.Fprintf(buf, "\ta.registration = reg\n")
	fmt.Fprintf(buf, "\tcancelFn := func() {\n")
	fmt.Fprintf(buf, "\t\tif a.registration != nil {\n")
	fmt.Fprintf(buf, "\t\t\ta.registration.cancel()\n")
	fmt.Fprintf(buf, "\t\t\ta.registration = nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn __able_make_await_registration_value(cancelFn), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (a *__able_channel_awaitable) commit() (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif a == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"awaitable not initialized\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandleVal := bridge.ToInt(a.handle, runtime.IntegerI64)\n")
	fmt.Fprintf(buf, "\tswitch a.op {\n")
	fmt.Fprintf(buf, "\tcase __able_channel_await_recv:\n")
	fmt.Fprintf(buf, "\t\tvalue := __able_extern_call([]runtime.Value{handleVal}, nil, __able_channel_receive_impl)\n")
	fmt.Fprintf(buf, "\t\tif a.callback == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_call_value(a.callback, []runtime.Value{value}, nil), nil\n")
	fmt.Fprintf(buf, "\tcase __able_channel_await_send:\n")
	fmt.Fprintf(buf, "\t\t_ = __able_extern_call([]runtime.Value{handleVal, a.payload}, nil, __able_channel_send_impl)\n")
	fmt.Fprintf(buf, "\t\tif a.callback == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_call_value(a.callback, nil, nil), nil\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"unknown awaitable operation\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (a *__able_channel_awaitable) toStruct() *runtime.StructInstanceValue {\n")
	fmt.Fprintf(buf, "\tinst := &runtime.StructInstanceValue{Fields: make(map[string]runtime.Value)}\n")
	fmt.Fprintf(buf, "\tisReady := runtime.NativeFunctionValue{\n")
	fmt.Fprintf(buf, "\t\tName:  \"Awaitable.is_ready\",\n")
	fmt.Fprintf(buf, "\t\tArity: 0,\n")
	fmt.Fprintf(buf, "\t\tImpl: func(_ *runtime.NativeCallContext, _ []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\t\tready, err := a.isReady()\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.BoolValue{Val: ready}, nil\n")
	fmt.Fprintf(buf, "\t\t},\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tregister := runtime.NativeFunctionValue{\n")
	fmt.Fprintf(buf, "\t\tName:  \"Awaitable.register\",\n")
	fmt.Fprintf(buf, "\t\tArity: 1,\n")
	fmt.Fprintf(buf, "\t\tImpl: func(_ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\t\tif len(args) == 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn nil, fmt.Errorf(\"register expects waker argument\")\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\twaker := args[len(args)-1]\n")
	fmt.Fprintf(buf, "\t\t\treturn a.register(waker)\n")
	fmt.Fprintf(buf, "\t\t},\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcommit := runtime.NativeFunctionValue{\n")
	fmt.Fprintf(buf, "\t\tName:  \"Awaitable.commit\",\n")
	fmt.Fprintf(buf, "\t\tArity: 0,\n")
	fmt.Fprintf(buf, "\t\tImpl: func(_ *runtime.NativeCallContext, _ []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\t\treturn a.commit()\n")
	fmt.Fprintf(buf, "\t\t},\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tisDefault := runtime.NativeFunctionValue{\n")
	fmt.Fprintf(buf, "\t\tName:  \"Awaitable.is_default\",\n")
	fmt.Fprintf(buf, "\t\tArity: 0,\n")
	fmt.Fprintf(buf, "\t\tImpl: func(_ *runtime.NativeCallContext, _ []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.BoolValue{Val: false}, nil\n")
	fmt.Fprintf(buf, "\t\t},\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tinst.Fields[\"is_ready\"] = &runtime.NativeBoundMethodValue{Receiver: inst, Method: isReady}\n")
	fmt.Fprintf(buf, "\tinst.Fields[\"register\"] = &runtime.NativeBoundMethodValue{Receiver: inst, Method: register}\n")
	fmt.Fprintf(buf, "\tinst.Fields[\"commit\"] = &runtime.NativeBoundMethodValue{Receiver: inst, Method: commit}\n")
	fmt.Fprintf(buf, "\tinst.Fields[\"is_default\"] = &runtime.NativeBoundMethodValue{Receiver: inst, Method: isDefault}\n")
	fmt.Fprintf(buf, "\treturn inst\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_channel_await_try_recv_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 2 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_channel_await_try_recv expects handle and callback\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_int64_from_value(args[0], \"channel handle\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tawaitable := &__able_channel_awaitable{handle: handle, op: __able_channel_await_recv, callback: args[1]}\n")
	fmt.Fprintf(buf, "\treturn awaitable.toStruct(), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_channel_await_try_send_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 3 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_channel_await_try_send expects handle, value, and callback\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_int64_from_value(args[0], \"channel handle\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tawaitable := &__able_channel_awaitable{handle: handle, op: __able_channel_await_send, payload: args[1], callback: args[2]}\n")
	fmt.Fprintf(buf, "\treturn awaitable.toStruct(), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_concurrency_error_struct(name string) *runtime.StructDefinitionValue {\n")
	fmt.Fprintf(buf, "\tif name == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_concurrency_error_defs == nil {\n")
	fmt.Fprintf(buf, "\t\t__able_concurrency_error_defs = make(map[string]*runtime.StructDefinitionValue)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif def, ok := __able_concurrency_error_defs[name]; ok {\n")
	fmt.Fprintf(buf, "\t\treturn def\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_runtime != nil {\n")
	fmt.Fprintf(buf, "\t\tcandidates := []string{\n")
	fmt.Fprintf(buf, "\t\t\tname,\n")
	fmt.Fprintf(buf, "\t\t\t\"concurrency.\" + name,\n")
	fmt.Fprintf(buf, "\t\t\t\"able.\" + name,\n")
	fmt.Fprintf(buf, "\t\t\t\"able.concurrency.\" + name,\n")
	fmt.Fprintf(buf, "\t\t\t\"able.concurrency.channel.\" + name,\n")
	fmt.Fprintf(buf, "\t\t\t\"able.concurrency.mutex.\" + name,\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tfor _, key := range candidates {\n")
	fmt.Fprintf(buf, "\t\t\tif def, err := __able_runtime.StructDefinition(key); err == nil && def != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_concurrency_error_defs[name] = def\n")
	fmt.Fprintf(buf, "\t\t\t\treturn def\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tplaceholder := ast.NewStructDefinition(ast.NewIdentifier(name), nil, ast.StructKindNamed, nil, nil, false)\n")
	fmt.Fprintf(buf, "\tdef := &runtime.StructDefinitionValue{Node: placeholder}\n")
	fmt.Fprintf(buf, "\t__able_concurrency_error_defs[name] = def\n")
	fmt.Fprintf(buf, "\treturn def\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_concurrency_error_value(name, message string) runtime.ErrorValue {\n")
	fmt.Fprintf(buf, "\tdef := __able_concurrency_error_struct(name)\n")
	fmt.Fprintf(buf, "\tif def == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.ErrorValue{Message: message}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tinstance := &runtime.StructInstanceValue{Definition: def}\n")
	fmt.Fprintf(buf, "\tpayload := map[string]runtime.Value{\"value\": instance}\n")
	fmt.Fprintf(buf, "\treturn runtime.ErrorValue{Message: message, Payload: payload}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_concurrency_error(name, message string) error {\n")
	fmt.Fprintf(buf, "\treturn __able_value_error{value: __able_concurrency_error_value(name, message)}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_channel_await_kind int\n\n")
	fmt.Fprintf(buf, "const (\n")
	fmt.Fprintf(buf, "\t__able_channel_await_recv __able_channel_await_kind = iota\n")
	fmt.Fprintf(buf, "\t__able_channel_await_send\n")
	fmt.Fprintf(buf, ")\n\n")
	fmt.Fprintf(buf, "type __able_channel_await_state struct {\n")
	fmt.Fprintf(buf, "\tmu           sync.Mutex\n")
	fmt.Fprintf(buf, "\tsendWaiters  int\n")
	fmt.Fprintf(buf, "\trecvWaiters  int\n")
	fmt.Fprintf(buf, "\tsendAwaiters map[*__able_channel_await_registration]struct{}\n")
	fmt.Fprintf(buf, "\trecvAwaiters map[*__able_channel_await_registration]struct{}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_channel_await_registration struct {\n")
	fmt.Fprintf(buf, "\tstate     *__able_channel_await_state\n")
	fmt.Fprintf(buf, "\tkind      __able_channel_await_kind\n")
	fmt.Fprintf(buf, "\twaker     runtime.Value\n")
	fmt.Fprintf(buf, "\tmu        sync.Mutex\n")
	fmt.Fprintf(buf, "\tcancelled bool\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "var __able_channel_await_states map[int64]*__able_channel_await_state\n")
	fmt.Fprintf(buf, "var __able_channel_await_mu sync.Mutex\n\n")
	fmt.Fprintf(buf, "func __able_channel_await_state_for(handle int64) *__able_channel_await_state {\n")
	fmt.Fprintf(buf, "\tif handle == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_channel_await_mu.Lock()\n")
	fmt.Fprintf(buf, "\tif __able_channel_await_states == nil {\n")
	fmt.Fprintf(buf, "\t\t__able_channel_await_states = make(map[int64]*__able_channel_await_state)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate := __able_channel_await_states[handle]\n")
	fmt.Fprintf(buf, "\tif state == nil {\n")
	fmt.Fprintf(buf, "\t\tstate = &__able_channel_await_state{}\n")
	fmt.Fprintf(buf, "\t\t__able_channel_await_states[handle] = state\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_channel_await_mu.Unlock()\n")
	fmt.Fprintf(buf, "\treturn state\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_channel_await_snapshot(handle int64) (int, int, int, int) {\n")
	fmt.Fprintf(buf, "\tstate := __able_channel_await_state_for(handle)\n")
	fmt.Fprintf(buf, "\tif state == nil {\n")
	fmt.Fprintf(buf, "\t\treturn 0, 0, 0, 0\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.mu.Lock()\n")
	fmt.Fprintf(buf, "\tsendWaiters := state.sendWaiters\n")
	fmt.Fprintf(buf, "\trecvWaiters := state.recvWaiters\n")
	fmt.Fprintf(buf, "\tsendAwaiters := len(state.sendAwaiters)\n")
	fmt.Fprintf(buf, "\trecvAwaiters := len(state.recvAwaiters)\n")
	fmt.Fprintf(buf, "\tstate.mu.Unlock()\n")
	fmt.Fprintf(buf, "\treturn sendWaiters, recvWaiters, sendAwaiters, recvAwaiters\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_channel_inc_send_waiters(handle int64, capacity int) bool {\n")
	fmt.Fprintf(buf, "\tstate := __able_channel_await_state_for(handle)\n")
	fmt.Fprintf(buf, "\tif state == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.mu.Lock()\n")
	fmt.Fprintf(buf, "\tstate.sendWaiters++\n")
	fmt.Fprintf(buf, "\tnewWaiter := capacity == 0 && state.sendWaiters == 1\n")
	fmt.Fprintf(buf, "\tstate.mu.Unlock()\n")
	fmt.Fprintf(buf, "\treturn newWaiter\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_channel_dec_send_waiters(handle int64) {\n")
	fmt.Fprintf(buf, "\tstate := __able_channel_await_state_for(handle)\n")
	fmt.Fprintf(buf, "\tif state == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.mu.Lock()\n")
	fmt.Fprintf(buf, "\tif state.sendWaiters > 0 {\n")
	fmt.Fprintf(buf, "\t\tstate.sendWaiters--\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.mu.Unlock()\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_channel_inc_recv_waiters(handle int64, capacity int) bool {\n")
	fmt.Fprintf(buf, "\tstate := __able_channel_await_state_for(handle)\n")
	fmt.Fprintf(buf, "\tif state == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.mu.Lock()\n")
	fmt.Fprintf(buf, "\tstate.recvWaiters++\n")
	fmt.Fprintf(buf, "\tnewWaiter := capacity == 0 && state.recvWaiters == 1\n")
	fmt.Fprintf(buf, "\tstate.mu.Unlock()\n")
	fmt.Fprintf(buf, "\treturn newWaiter\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_channel_dec_recv_waiters(handle int64) {\n")
	fmt.Fprintf(buf, "\tstate := __able_channel_await_state_for(handle)\n")
	fmt.Fprintf(buf, "\tif state == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.mu.Lock()\n")
	fmt.Fprintf(buf, "\tif state.recvWaiters > 0 {\n")
	fmt.Fprintf(buf, "\t\tstate.recvWaiters--\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.mu.Unlock()\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (r *__able_channel_await_registration) cancel() {\n")
	fmt.Fprintf(buf, "\tif r == nil || r.state == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tr.mu.Lock()\n")
	fmt.Fprintf(buf, "\tif r.cancelled {\n")
	fmt.Fprintf(buf, "\t\tr.mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tr.cancelled = true\n")
	fmt.Fprintf(buf, "\tr.mu.Unlock()\n")
	fmt.Fprintf(buf, "\tr.state.mu.Lock()\n")
	fmt.Fprintf(buf, "\tswitch r.kind {\n")
	fmt.Fprintf(buf, "\tcase __able_channel_await_send:\n")
	fmt.Fprintf(buf, "\t\tdelete(r.state.sendAwaiters, r)\n")
	fmt.Fprintf(buf, "\tcase __able_channel_await_recv:\n")
	fmt.Fprintf(buf, "\t\tdelete(r.state.recvAwaiters, r)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tr.state.mu.Unlock()\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (r *__able_channel_await_registration) trigger() {\n")
	fmt.Fprintf(buf, "\tif r == nil || r.waker == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tr.mu.Lock()\n")
	fmt.Fprintf(buf, "\tif r.cancelled {\n")
	fmt.Fprintf(buf, "\t\tr.mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tr.mu.Unlock()\n")
	fmt.Fprintf(buf, "\t__able_invoke_await_waker(r.waker)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_add_channel_awaiter(handle int64, kind __able_channel_await_kind, waker runtime.Value) *__able_channel_await_registration {\n")
	fmt.Fprintf(buf, "\tstate := __able_channel_await_state_for(handle)\n")
	fmt.Fprintf(buf, "\tif state == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treg := &__able_channel_await_registration{state: state, kind: kind, waker: waker}\n")
	fmt.Fprintf(buf, "\tstate.mu.Lock()\n")
	fmt.Fprintf(buf, "\tswitch kind {\n")
	fmt.Fprintf(buf, "\tcase __able_channel_await_send:\n")
	fmt.Fprintf(buf, "\t\tif state.sendAwaiters == nil {\n")
	fmt.Fprintf(buf, "\t\t\tstate.sendAwaiters = make(map[*__able_channel_await_registration]struct{})\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tstate.sendAwaiters[reg] = struct{}{}\n")
	fmt.Fprintf(buf, "\tcase __able_channel_await_recv:\n")
	fmt.Fprintf(buf, "\t\tif state.recvAwaiters == nil {\n")
	fmt.Fprintf(buf, "\t\t\tstate.recvAwaiters = make(map[*__able_channel_await_registration]struct{})\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tstate.recvAwaiters[reg] = struct{}{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.mu.Unlock()\n")
	fmt.Fprintf(buf, "\treturn reg\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_notify_channel_awaiters(handle int64, kind __able_channel_await_kind) {\n")
	fmt.Fprintf(buf, "\tstate := __able_channel_await_state_for(handle)\n")
	fmt.Fprintf(buf, "\tif state == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.mu.Lock()\n")
	fmt.Fprintf(buf, "\tvar regs []*__able_channel_await_registration\n")
	fmt.Fprintf(buf, "\tswitch kind {\n")
	fmt.Fprintf(buf, "\tcase __able_channel_await_send:\n")
	fmt.Fprintf(buf, "\t\tfor reg := range state.sendAwaiters {\n")
	fmt.Fprintf(buf, "\t\t\tregs = append(regs, reg)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\tcase __able_channel_await_recv:\n")
	fmt.Fprintf(buf, "\t\tfor reg := range state.recvAwaiters {\n")
	fmt.Fprintf(buf, "\t\t\tregs = append(regs, reg)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.mu.Unlock()\n")
	fmt.Fprintf(buf, "\tfor _, reg := range regs {\n")
	fmt.Fprintf(buf, "\t\treg.trigger()\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_invoke_await_waker(waker runtime.Value) {\n")
	fmt.Fprintf(buf, "\tif waker == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tmember := __able_member(waker, runtime.StringValue{Val: \"wake\"})\n")
	fmt.Fprintf(buf, "\t_ = __able_call_value(member, nil, nil)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_make_await_registration_value(cancelFn func()) runtime.Value {\n")
	fmt.Fprintf(buf, "\tinst := &runtime.StructInstanceValue{Fields: make(map[string]runtime.Value)}\n")
	fmt.Fprintf(buf, "\tif __able_runtime != nil {\n")
	fmt.Fprintf(buf, "\t\tif def, err := __able_runtime.StructDefinition(\"AwaitRegistration\"); err == nil && def != nil {\n")
	fmt.Fprintf(buf, "\t\t\tinst.Definition = def\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcancelMethod := runtime.NativeFunctionValue{\n")
	fmt.Fprintf(buf, "\t\tName:  \"AwaitRegistration.cancel\",\n")
	fmt.Fprintf(buf, "\t\tArity: 0,\n")
	fmt.Fprintf(buf, "\t\tImpl: func(_ *runtime.NativeCallContext, _ []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\t\tif cancelFn != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tcancelFn()\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t\t},\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tinst.Fields[\"cancel\"] = &runtime.NativeBoundMethodValue{Receiver: inst, Method: cancelMethod}\n")
	fmt.Fprintf(buf, "\treturn inst\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_mutex_await_state struct {\n")
	fmt.Fprintf(buf, "\tmu       sync.Mutex\n")
	fmt.Fprintf(buf, "\tawaiters map[*__able_mutex_await_registration]struct{}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_mutex_await_registration struct {\n")
	fmt.Fprintf(buf, "\tstate     *__able_mutex_await_state\n")
	fmt.Fprintf(buf, "\twaker     runtime.Value\n")
	fmt.Fprintf(buf, "\tmu        sync.Mutex\n")
	fmt.Fprintf(buf, "\tcancelled bool\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "var __able_mutex_await_states map[int64]*__able_mutex_await_state\n")
	fmt.Fprintf(buf, "var __able_mutex_await_mu sync.Mutex\n\n")
	fmt.Fprintf(buf, "func __able_mutex_await_state_for(handle int64) *__able_mutex_await_state {\n")
	fmt.Fprintf(buf, "\tif handle == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_mutex_await_mu.Lock()\n")
	fmt.Fprintf(buf, "\tif __able_mutex_await_states == nil {\n")
	fmt.Fprintf(buf, "\t\t__able_mutex_await_states = make(map[int64]*__able_mutex_await_state)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate := __able_mutex_await_states[handle]\n")
	fmt.Fprintf(buf, "\tif state == nil {\n")
	fmt.Fprintf(buf, "\t\tstate = &__able_mutex_await_state{}\n")
	fmt.Fprintf(buf, "\t\t__able_mutex_await_states[handle] = state\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_mutex_await_mu.Unlock()\n")
	fmt.Fprintf(buf, "\treturn state\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (r *__able_mutex_await_registration) cancel() {\n")
	fmt.Fprintf(buf, "\tif r == nil || r.state == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tr.mu.Lock()\n")
	fmt.Fprintf(buf, "\tif r.cancelled {\n")
	fmt.Fprintf(buf, "\t\tr.mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tr.cancelled = true\n")
	fmt.Fprintf(buf, "\tr.mu.Unlock()\n")
	fmt.Fprintf(buf, "\tr.state.mu.Lock()\n")
	fmt.Fprintf(buf, "\tif r.state.awaiters != nil {\n")
	fmt.Fprintf(buf, "\t\tdelete(r.state.awaiters, r)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tr.state.mu.Unlock()\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (r *__able_mutex_await_registration) trigger() {\n")
	fmt.Fprintf(buf, "\tif r == nil || r.waker == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tr.mu.Lock()\n")
	fmt.Fprintf(buf, "\tif r.cancelled {\n")
	fmt.Fprintf(buf, "\t\tr.mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tr.cancelled = true\n")
	fmt.Fprintf(buf, "\tr.mu.Unlock()\n")
	fmt.Fprintf(buf, "\t__able_invoke_await_waker(r.waker)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_add_mutex_awaiter(handle int64, waker runtime.Value) *__able_mutex_await_registration {\n")
	fmt.Fprintf(buf, "\tstate := __able_mutex_await_state_for(handle)\n")
	fmt.Fprintf(buf, "\tif state == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treg := &__able_mutex_await_registration{state: state, waker: waker}\n")
	fmt.Fprintf(buf, "\tstate.mu.Lock()\n")
	fmt.Fprintf(buf, "\tif state.awaiters == nil {\n")
	fmt.Fprintf(buf, "\t\tstate.awaiters = make(map[*__able_mutex_await_registration]struct{})\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.awaiters[reg] = struct{}{}\n")
	fmt.Fprintf(buf, "\tstate.mu.Unlock()\n")
	fmt.Fprintf(buf, "\treturn reg\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_notify_mutex_awaiters(handle int64) {\n")
	fmt.Fprintf(buf, "\tstate := __able_mutex_await_state_for(handle)\n")
	fmt.Fprintf(buf, "\tif state == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.mu.Lock()\n")
	fmt.Fprintf(buf, "\tregs := make([]*__able_mutex_await_registration, 0, len(state.awaiters))\n")
	fmt.Fprintf(buf, "\tfor reg := range state.awaiters {\n")
	fmt.Fprintf(buf, "\t\tregs = append(regs, reg)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.awaiters = make(map[*__able_mutex_await_registration]struct{})\n")
	fmt.Fprintf(buf, "\tstate.mu.Unlock()\n")
	fmt.Fprintf(buf, "\tfor _, reg := range regs {\n")
	fmt.Fprintf(buf, "\t\treg.trigger()\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_channel_new_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_channel_new expects capacity argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcapacity, err := __able_int64_from_value(args[0], \"channel capacity\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif capacity < 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"channel capacity must be non-negative\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := runtime.ChannelStoreNew(int(capacity))\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.ToInt(handle, runtime.IntegerI64), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_block_on_nil_channel() (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tpayload := __able_current_payload()\n")
	fmt.Fprintf(buf, "\tif payload == nil || payload.handle == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"channel operation on nil handle outside async context\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tctx := payload.handle.Context()\n")
	fmt.Fprintf(buf, "\tif ctx == nil {\n")
	fmt.Fprintf(buf, "\t\tctx = context.Background()\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_mark_current_task_blocked()\n")
	fmt.Fprintf(buf, "\tdefer __able_mark_current_task_unblocked()\n")
	fmt.Fprintf(buf, "\t<-ctx.Done()\n")
	fmt.Fprintf(buf, "\treturn nil, ctx.Err()\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_channel_send_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 2 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_channel_send expects handle and value\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_int64_from_value(args[0], \"channel handle\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handle == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn __able_block_on_nil_channel()\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handle < 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"channel handle must be non-negative\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif closed, err := runtime.ChannelStoreIsClosed(handle); err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t} else if closed {\n")
	fmt.Fprintf(buf, "\t\treturn nil, __able_concurrency_error(\"ChannelSendOnClosed\", \"send on closed channel\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.ChannelStoreState(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tctx := context.Background()\n")
	fmt.Fprintf(buf, "\tif payload := __able_current_payload(); payload != nil && payload.handle != nil {\n")
	fmt.Fprintf(buf, "\t\tif taskCtx := payload.handle.Context(); taskCtx != nil {\n")
	fmt.Fprintf(buf, "\t\t\tctx = taskCtx\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tch := state.Ch\n")
	fmt.Fprintf(buf, "\tselect {\n")
	fmt.Fprintf(buf, "\tcase ch <- args[1]:\n")
	fmt.Fprintf(buf, "\t\t__able_notify_channel_awaiters(handle, __able_channel_await_recv)\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_channel_inc_send_waiters(handle, state.Capacity) {\n")
	fmt.Fprintf(buf, "\t\t__able_notify_channel_awaiters(handle, __able_channel_await_recv)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tdefer __able_channel_dec_send_waiters(handle)\n")
	fmt.Fprintf(buf, "\t__able_mark_current_task_blocked()\n")
	fmt.Fprintf(buf, "\tdefer __able_mark_current_task_unblocked()\n")
	fmt.Fprintf(buf, "\tselect {\n")
	fmt.Fprintf(buf, "\tcase ch <- args[1]:\n")
	fmt.Fprintf(buf, "\t\t__able_notify_channel_awaiters(handle, __able_channel_await_recv)\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\tcase <-state.CloseCh:\n")
	fmt.Fprintf(buf, "\t\treturn nil, __able_concurrency_error(\"ChannelSendOnClosed\", \"send on closed channel\")\n")
	fmt.Fprintf(buf, "\tcase <-ctx.Done():\n")
	fmt.Fprintf(buf, "\t\treturn nil, ctx.Err()\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_channel_receive_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_channel_receive expects handle argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_int64_from_value(args[0], \"channel handle\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handle == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn __able_block_on_nil_channel()\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handle < 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"channel handle must be non-negative\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.ChannelStoreState(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tctx := context.Background()\n")
	fmt.Fprintf(buf, "\tif payload := __able_current_payload(); payload != nil && payload.handle != nil {\n")
	fmt.Fprintf(buf, "\t\tif taskCtx := payload.handle.Context(); taskCtx != nil {\n")
	fmt.Fprintf(buf, "\t\t\tctx = taskCtx\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tch := state.Ch\n")
	fmt.Fprintf(buf, "\tclosed, err := runtime.ChannelStoreIsClosed(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfor {\n")
	fmt.Fprintf(buf, "\t\tif closed && len(ch) == 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif len(ch) > 0 {\n")
	fmt.Fprintf(buf, "\t\t\tvalue := <-ch\n")
	fmt.Fprintf(buf, "\t\t\tif value == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t__able_notify_channel_awaiters(handle, __able_channel_await_send)\n")
	fmt.Fprintf(buf, "\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif __able_channel_inc_recv_waiters(handle, state.Capacity) {\n")
	fmt.Fprintf(buf, "\t\t\t__able_notify_channel_awaiters(handle, __able_channel_await_send)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\t__able_mark_current_task_blocked()\n")
	fmt.Fprintf(buf, "\t\tselect {\n")
	fmt.Fprintf(buf, "\t\tcase value := <-ch:\n")
	fmt.Fprintf(buf, "\t\t\t__able_mark_current_task_unblocked()\n")
	fmt.Fprintf(buf, "\t\t\t__able_channel_dec_recv_waiters(handle)\n")
	fmt.Fprintf(buf, "\t\t\tif value == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t__able_notify_channel_awaiters(handle, __able_channel_await_send)\n")
	fmt.Fprintf(buf, "\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\tcase <-state.CloseCh:\n")
	fmt.Fprintf(buf, "\t\t\t__able_mark_current_task_unblocked()\n")
	fmt.Fprintf(buf, "\t\t\t__able_channel_dec_recv_waiters(handle)\n")
	fmt.Fprintf(buf, "\t\t\tclosed = true\n")
	fmt.Fprintf(buf, "\t\tcase <-ctx.Done():\n")
	fmt.Fprintf(buf, "\t\t\t__able_mark_current_task_unblocked()\n")
	fmt.Fprintf(buf, "\t\t\t__able_channel_dec_recv_waiters(handle)\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, ctx.Err()\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_channel_try_send_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 2 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_channel_try_send expects handle and value\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_int64_from_value(args[0], \"channel handle\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handle == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.BoolValue{Val: false}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handle < 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"channel handle must be non-negative\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif closed, err := runtime.ChannelStoreIsClosed(handle); err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t} else if closed {\n")
	fmt.Fprintf(buf, "\t\treturn nil, __able_concurrency_error(\"ChannelSendOnClosed\", \"send on closed channel\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.ChannelStoreState(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tselect {\n")
	fmt.Fprintf(buf, "\tcase <-state.CloseCh:\n")
	fmt.Fprintf(buf, "\t\treturn nil, __able_concurrency_error(\"ChannelSendOnClosed\", \"send on closed channel\")\n")
	fmt.Fprintf(buf, "\tcase state.Ch <- args[1]:\n")
	fmt.Fprintf(buf, "\t\t__able_notify_channel_awaiters(handle, __able_channel_await_recv)\n")
	fmt.Fprintf(buf, "\t\treturn runtime.BoolValue{Val: true}, nil\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.BoolValue{Val: false}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_channel_try_receive_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_channel_try_receive expects handle argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_int64_from_value(args[0], \"channel handle\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handle == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handle < 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"channel handle must be non-negative\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.ChannelStoreState(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif closed, err := runtime.ChannelStoreIsClosed(handle); err == nil && closed && len(state.Ch) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tselect {\n")
	fmt.Fprintf(buf, "\tcase value := <-state.Ch:\n")
	fmt.Fprintf(buf, "\t\tif value == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\t__able_notify_channel_awaiters(handle, __able_channel_await_send)\n")
	fmt.Fprintf(buf, "\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_channel_close_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_channel_close expects handle argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_int64_from_value(args[0], \"channel handle\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handle == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, __able_concurrency_error(\"ChannelNil\", \"close of nil channel\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handle < 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"channel handle must be non-negative\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tclosed, err := runtime.ChannelStoreClose(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif !closed {\n")
	fmt.Fprintf(buf, "\t\treturn nil, __able_concurrency_error(\"ChannelClosed\", \"close of closed channel\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_notify_channel_awaiters(handle, __able_channel_await_recv)\n")
	fmt.Fprintf(buf, "\t__able_notify_channel_awaiters(handle, __able_channel_await_send)\n")
	fmt.Fprintf(buf, "\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_channel_is_closed_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_channel_is_closed expects handle argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_int64_from_value(args[0], \"channel handle\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handle == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.BoolValue{Val: false}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handle < 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"channel handle must be non-negative\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tclosed, err := runtime.ChannelStoreIsClosed(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.BoolValue{Val: closed}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_mutex_new_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_mutex_new expects no arguments\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle := runtime.MutexStoreNew()\n")
	fmt.Fprintf(buf, "\treturn bridge.ToInt(handle, runtime.IntegerI64), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_mutex_lock_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_mutex_lock expects handle argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_int64_from_value(args[0], \"mutex handle\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handle <= 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"mutex handle must be positive\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.MutexStoreState(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tctx := context.Background()\n")
	fmt.Fprintf(buf, "\tif payload := __able_current_payload(); payload != nil && payload.handle != nil {\n")
	fmt.Fprintf(buf, "\t\tif taskCtx := payload.handle.Context(); taskCtx != nil {\n")
	fmt.Fprintf(buf, "\t\t\tctx = taskCtx\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.Mu.Lock()\n")
	fmt.Fprintf(buf, "\tif !state.Locked {\n")
	fmt.Fprintf(buf, "\t\tstate.Locked = true\n")
	fmt.Fprintf(buf, "\t\tstate.Mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tregistered := false\n")
	fmt.Fprintf(buf, "\twaiting := false\n")
	fmt.Fprintf(buf, "\tfor {\n")
	fmt.Fprintf(buf, "\t\tif !state.Locked {\n")
	fmt.Fprintf(buf, "\t\t\tstate.Locked = true\n")
	fmt.Fprintf(buf, "\t\t\tif registered {\n")
	fmt.Fprintf(buf, "\t\t\t\tstate.Waiters--\n")
	fmt.Fprintf(buf, "\t\t\t\tregistered = false\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif waiting {\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_mark_current_task_unblocked()\n")
	fmt.Fprintf(buf, "\t\t\t\twaiting = false\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tstate.Cond.Signal()\n")
	fmt.Fprintf(buf, "\t\t\tstate.Mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !registered {\n")
	fmt.Fprintf(buf, "\t\t\tstate.Waiters++\n")
	fmt.Fprintf(buf, "\t\t\tregistered = true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !waiting {\n")
	fmt.Fprintf(buf, "\t\t\t__able_mark_current_task_blocked()\n")
	fmt.Fprintf(buf, "\t\t\twaiting = true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tselect {\n")
	fmt.Fprintf(buf, "\t\tcase <-ctx.Done():\n")
	fmt.Fprintf(buf, "\t\t\tif waiting {\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_mark_current_task_unblocked()\n")
	fmt.Fprintf(buf, "\t\t\t\twaiting = false\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif registered {\n")
	fmt.Fprintf(buf, "\t\t\t\tstate.Waiters--\n")
	fmt.Fprintf(buf, "\t\t\t\tregistered = false\n")
	fmt.Fprintf(buf, "\t\t\t\tstate.Cond.Signal()\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tstate.Mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, ctx.Err()\n")
	fmt.Fprintf(buf, "\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tstate.Cond.Wait()\n")
	fmt.Fprintf(buf, "\t\tif waiting {\n")
	fmt.Fprintf(buf, "\t\t\t__able_mark_current_task_unblocked()\n")
	fmt.Fprintf(buf, "\t\t\twaiting = false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_mutex_unlock_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_mutex_unlock expects handle argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_int64_from_value(args[0], \"mutex handle\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handle <= 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"mutex handle must be positive\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.MutexStoreState(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.Mu.Lock()\n")
	fmt.Fprintf(buf, "\tif !state.Locked {\n")
	fmt.Fprintf(buf, "\t\tstate.Mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\treturn nil, __able_concurrency_error(\"MutexUnlocked\", \"unlock of unlocked mutex\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.Locked = false\n")
	fmt.Fprintf(buf, "\t__able_notify_mutex_awaiters(handle)\n")
	fmt.Fprintf(buf, "\tif state.Waiters > 0 {\n")
	fmt.Fprintf(buf, "\t\tstate.Cond.Signal()\n")
	fmt.Fprintf(buf, "\t\tfor state.Waiters > 0 && !state.Locked {\n")
	fmt.Fprintf(buf, "\t\t\tstate.Cond.Wait()\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.Mu.Unlock()\n")
	fmt.Fprintf(buf, "\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_mutex_awaitable struct {\n")
	fmt.Fprintf(buf, "\thandle       int64\n")
	fmt.Fprintf(buf, "\tcallback     runtime.Value\n")
	fmt.Fprintf(buf, "\tregistration *__able_mutex_await_registration\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (a *__able_mutex_awaitable) isReady() (bool, error) {\n")
	fmt.Fprintf(buf, "\tif a == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false, fmt.Errorf(\"awaitable not initialized\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.MutexStoreState(a.handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn false, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.Mu.Lock()\n")
	fmt.Fprintf(buf, "\tready := !state.Locked\n")
	fmt.Fprintf(buf, "\tstate.Mu.Unlock()\n")
	fmt.Fprintf(buf, "\treturn ready, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (a *__able_mutex_awaitable) register(waker runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif a == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"awaitable not initialized\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.MutexStoreState(a.handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.Mu.Lock()\n")
	fmt.Fprintf(buf, "\tif !state.Locked {\n")
	fmt.Fprintf(buf, "\t\tstate.Mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\t__able_invoke_await_waker(waker)\n")
	fmt.Fprintf(buf, "\t\ta.registration = nil\n")
	fmt.Fprintf(buf, "\t\treturn __able_make_await_registration_value(nil), nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.Mu.Unlock()\n")
	fmt.Fprintf(buf, "\treg := __able_add_mutex_awaiter(a.handle, waker)\n")
	fmt.Fprintf(buf, "\ta.registration = reg\n")
	fmt.Fprintf(buf, "\tcancelFn := func() {\n")
	fmt.Fprintf(buf, "\t\tif reg != nil {\n")
	fmt.Fprintf(buf, "\t\t\treg.cancel()\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\ta.registration = nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn __able_make_await_registration_value(cancelFn), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (a *__able_mutex_awaitable) commit() (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif a == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"awaitable not initialized\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif a.registration != nil {\n")
	fmt.Fprintf(buf, "\t\ta.registration.cancel()\n")
	fmt.Fprintf(buf, "\t\ta.registration = nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandleVal := bridge.ToInt(a.handle, runtime.IntegerI64)\n")
	fmt.Fprintf(buf, "\t_ = __able_extern_call([]runtime.Value{handleVal}, nil, __able_mutex_lock_impl)\n")
	fmt.Fprintf(buf, "\tif a.callback == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn __able_call_value(a.callback, nil, nil), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (a *__able_mutex_awaitable) toStruct() *runtime.StructInstanceValue {\n")
	fmt.Fprintf(buf, "\tinst := &runtime.StructInstanceValue{Fields: make(map[string]runtime.Value)}\n")
	fmt.Fprintf(buf, "\tisReady := runtime.NativeFunctionValue{\n")
	fmt.Fprintf(buf, "\t\tName:  \"Awaitable.is_ready\",\n")
	fmt.Fprintf(buf, "\t\tArity: 0,\n")
	fmt.Fprintf(buf, "\t\tImpl: func(_ *runtime.NativeCallContext, _ []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\t\tready, err := a.isReady()\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.BoolValue{Val: ready}, nil\n")
	fmt.Fprintf(buf, "\t\t},\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tregister := runtime.NativeFunctionValue{\n")
	fmt.Fprintf(buf, "\t\tName:  \"Awaitable.register\",\n")
	fmt.Fprintf(buf, "\t\tArity: 1,\n")
	fmt.Fprintf(buf, "\t\tImpl: func(_ *runtime.NativeCallContext, args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\t\tif len(args) == 0 {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn nil, fmt.Errorf(\"register expects waker argument\")\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\twaker := args[len(args)-1]\n")
	fmt.Fprintf(buf, "\t\t\treturn a.register(waker)\n")
	fmt.Fprintf(buf, "\t\t},\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcommit := runtime.NativeFunctionValue{\n")
	fmt.Fprintf(buf, "\t\tName:  \"Awaitable.commit\",\n")
	fmt.Fprintf(buf, "\t\tArity: 0,\n")
	fmt.Fprintf(buf, "\t\tImpl: func(_ *runtime.NativeCallContext, _ []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\t\treturn a.commit()\n")
	fmt.Fprintf(buf, "\t\t},\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tisDefault := runtime.NativeFunctionValue{\n")
	fmt.Fprintf(buf, "\t\tName:  \"Awaitable.is_default\",\n")
	fmt.Fprintf(buf, "\t\tArity: 0,\n")
	fmt.Fprintf(buf, "\t\tImpl: func(_ *runtime.NativeCallContext, _ []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.BoolValue{Val: false}, nil\n")
	fmt.Fprintf(buf, "\t\t},\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tinst.Fields[\"is_ready\"] = &runtime.NativeBoundMethodValue{Receiver: inst, Method: isReady}\n")
	fmt.Fprintf(buf, "\tinst.Fields[\"register\"] = &runtime.NativeBoundMethodValue{Receiver: inst, Method: register}\n")
	fmt.Fprintf(buf, "\tinst.Fields[\"commit\"] = &runtime.NativeBoundMethodValue{Receiver: inst, Method: commit}\n")
	fmt.Fprintf(buf, "\tinst.Fields[\"is_default\"] = &runtime.NativeBoundMethodValue{Receiver: inst, Method: isDefault}\n")
	fmt.Fprintf(buf, "\treturn inst\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_mutex_await_lock_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) < 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_mutex_await_lock expects handle and callback\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_int64_from_value(args[0], \"mutex handle\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvar callback runtime.Value\n")
	fmt.Fprintf(buf, "\tif len(args) > 1 {\n")
	fmt.Fprintf(buf, "\t\tcallback = args[1]\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tawaitable := &__able_mutex_awaitable{handle: handle, callback: callback}\n")
	fmt.Fprintf(buf, "\treturn awaitable.toStruct(), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	g.renderRuntimeConcurrencyExternWrappers(buf)
}
