package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderRuntimeCallValueHelper(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "func __able_call_value(fn runtime.Value, args []runtime.Value, call *ast.FunctionCall) (runtime.Value, *__ableControl) {\n")
	g.emitDynamicBoundaryTelemetry(buf, "residual")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_runtime_error_control(call, fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfor {\n")
	fmt.Fprintf(buf, "\t\tif iface, ok, nilPtr := __able_callable_interface_value(fn); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\t\tfn = runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tfn = iface.Underlying\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif partial, ok, nilPtr := __able_callable_partial_value(fn); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\t\tfn = runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\targs = __able_merge_bound_args(partial.BoundArgs, args)\n")
	fmt.Fprintf(buf, "\t\t\tfn = partial.Target\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbreak\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_pushed_call_frame := false\n")
	fmt.Fprintf(buf, "\tif call != nil {\n")
	fmt.Fprintf(buf, "\t\tbridge.PushCallFrame(__able_runtime, call)\n")
	fmt.Fprintf(buf, "\t\t__able_pushed_call_frame = true\n")
	fmt.Fprintf(buf, "\t\tdefer func() {\n")
	fmt.Fprintf(buf, "\t\t\tif __able_pushed_call_frame {\n")
	fmt.Fprintf(buf, "\t\t\t\tbridge.PopCallFrame(__able_runtime)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}()\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif fn != nil {\n")
	fmt.Fprintf(buf, "\t\tenv := __able_runtime.Env()\n")
	fmt.Fprintf(buf, "\t\tvar state any\n")
	fmt.Fprintf(buf, "\t\tif env != nil {\n")
	fmt.Fprintf(buf, "\t\t\tstate = env.RuntimeData()\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tctx := &runtime.NativeCallContext{Env: env, State: state}\n")
	fmt.Fprintf(buf, "\t\tif val, control, handled := __able_call_native_function_value(fn, args, call, ctx); handled {\n")
	fmt.Fprintf(buf, "\t\t\treturn val, control\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif nativeBound, ok, _ := __able_callable_native_bound_method_value(fn); ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_call_native_bound_method(nativeBound, fn, args, call, ctx)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif bound, ok, _ := __able_callable_bound_method_value(fn); ok {\n")
	fmt.Fprintf(buf, "\t\t\tif val, control, handled := __able_call_bound_method(bound, fn, args, call, ctx); handled {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn val, control\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif val, control, handled := __able_call_function_thunk(fn, args, call); handled {\n")
	fmt.Fprintf(buf, "\t\t\treturn val, control\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif val, control, handled := __able_call_function_overload(fn, args, call); handled {\n")
	fmt.Fprintf(buf, "\t\t\treturn val, control\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif apply, ok, err := __able_resolve_apply_callable(fn); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif __able_pushed_call_frame && __able_is_caller_frame_error(err) {\n")
	fmt.Fprintf(buf, "\t\t\t\tbridge.PopCallFrame(__able_runtime)\n")
	fmt.Fprintf(buf, "\t\t\t\t__able_pushed_call_frame = false\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_control_from_error_with_node(call, err)\n")
	fmt.Fprintf(buf, "\t\t} else if ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_call_value(apply, args, call)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_boundary_name := __able_callable_name(fn)\n")
	fmt.Fprintf(buf, "\tif !__able_allow_dynamic_bridge {\n")
	fmt.Fprintf(buf, "\t\terr := fmt.Errorf(\"compiler: unresolved static call value %%s\", __able_boundary_name)\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_runtime_error_control(call, err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_mark_boundary_fallback(__able_boundary_name)\n")
	fmt.Fprintf(buf, "\t__able_mark_boundary_explicit(\"call_value\", __able_boundary_name)\n")
	fmt.Fprintf(buf, "\tval, err := bridge.CallValueWithNode(__able_runtime, fn, args, call)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error_with_node(call, err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
}
