package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderArrayStructHelpers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "func __able_struct_Array_track_handle(value *Array) error {\n")
	fmt.Fprintf(buf, "\tif value == nil {\n")
	fmt.Fprintf(buf, "\t\treturn fmt.Errorf(\"missing Array value\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif runtime.ArrayStoreLeaseTracksWithCleanup(&value.arrayStoreLease, value.Storage_handle) {\n")
	fmt.Fprintf(buf, "\t\treturn nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.ArrayStoreTrackLeaseOwner(value, &value.arrayStoreLease, value.Storage_handle)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_struct_Array_clone(value *Array) (*Array, error) {\n")
	fmt.Fprintf(buf, "\tif value == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_struct_Array_sync(value)\n")
	fmt.Fprintf(buf, "\tif err := __able_struct_Array_track_handle(value); err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tclone := &Array{\n")
	fmt.Fprintf(buf, "\t\tLength: value.Length,\n")
	fmt.Fprintf(buf, "\t\tCapacity: value.Capacity,\n")
	fmt.Fprintf(buf, "\t\tStorage_handle: value.Storage_handle,\n")
	fmt.Fprintf(buf, "\t\tElements: value.Elements,\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif err := __able_struct_Array_track_handle(clone); err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn clone, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_struct_Array_move(target *Array, source *Array) error {\n")
	fmt.Fprintf(buf, "\tif target == nil || source == nil {\n")
	fmt.Fprintf(buf, "\t\treturn fmt.Errorf(\"missing Array value\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif target == source {\n")
	fmt.Fprintf(buf, "\t\t__able_struct_Array_sync(target)\n")
	fmt.Fprintf(buf, "\t\treturn __able_struct_Array_track_handle(target)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t__able_struct_Array_sync(source)\n")
	fmt.Fprintf(buf, "\tif err := __able_struct_Array_track_handle(source); err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif err := runtime.ArrayStoreMoveLease(&target.arrayStoreLease, &source.arrayStoreLease); err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\ttarget.Length = source.Length\n")
	fmt.Fprintf(buf, "\ttarget.Capacity = source.Capacity\n")
	fmt.Fprintf(buf, "\ttarget.Storage_handle = source.Storage_handle\n")
	fmt.Fprintf(buf, "\ttarget.Elements = source.Elements\n")
	fmt.Fprintf(buf, "\tsource.Length = 0\n")
	fmt.Fprintf(buf, "\tsource.Capacity = 0\n")
	fmt.Fprintf(buf, "\tsource.Storage_handle = 0\n")
	fmt.Fprintf(buf, "\tsource.Elements = nil\n")
	fmt.Fprintf(buf, "\treturn __able_struct_Array_track_handle(target)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_struct_Array_sync(value *Array) {\n")
	fmt.Fprintf(buf, "\tif value == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvalue.Length = int32(len(value.Elements))\n")
	fmt.Fprintf(buf, "\tvalue.Capacity = int32(cap(value.Elements))\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_struct_Array_capacity_hint(value *Array) int {\n")
	fmt.Fprintf(buf, "\tif value == nil {\n")
	fmt.Fprintf(buf, "\t\treturn 0\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcapHint := cap(value.Elements)\n")
	fmt.Fprintf(buf, "\tif capHint < int(value.Capacity) {\n")
	fmt.Fprintf(buf, "\t\tcapHint = int(value.Capacity)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif capHint < len(value.Elements) {\n")
	fmt.Fprintf(buf, "\t\tcapHint = len(value.Elements)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn capHint\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_struct_Array_clone_elements(values []runtime.Value, capacityHint int) []runtime.Value {\n")
	fmt.Fprintf(buf, "\tif capacityHint < len(values) {\n")
	fmt.Fprintf(buf, "\t\tcapacityHint = len(values)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcloned := make([]runtime.Value, len(values), capacityHint)\n")
	fmt.Fprintf(buf, "\tcopy(cloned, values)\n")
	fmt.Fprintf(buf, "\treturn cloned\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_struct_instance_state(inst *runtime.StructInstanceValue) ([]runtime.Value, int64, int32, int32, error) {\n")
	fmt.Fprintf(buf, "\tif inst == nil || inst.Definition == nil || inst.Definition.Node == nil || inst.Definition.Node.ID == nil || inst.Definition.Node.ID.Name != \"Array\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil, 0, 0, 0, fmt.Errorf(\"expected Array value\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvar sourceValues []runtime.Value\n")
	fmt.Fprintf(buf, "\tvar sourceHandle int64\n")
	fmt.Fprintf(buf, "\tvar sourceLength int32\n")
	fmt.Fprintf(buf, "\tvar sourceCapacity int32\n")
	fmt.Fprintf(buf, "\tif lengthVal, ok := __able_struct_named_field_value(inst, \"length\"); ok {\n")
	fmt.Fprintf(buf, "\t\tlength, err := bridge.AsInt(lengthVal, 32)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, 0, 0, 0, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tsourceLength = int32(length)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif capacityVal, ok := __able_struct_named_field_value(inst, \"capacity\"); ok {\n")
	fmt.Fprintf(buf, "\t\tcapacity, err := bridge.AsInt(capacityVal, 32)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, 0, 0, 0, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tsourceCapacity = int32(capacity)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif handleVal, ok := __able_struct_named_field_value(inst, \"storage_handle\"); ok {\n")
	fmt.Fprintf(buf, "\t\thandle, err := __able_array_handle_from_value(handleVal)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, 0, 0, 0, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tsourceHandle = handle\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif sourceHandle != 0 {\n")
	fmt.Fprintf(buf, "\t\tstate, err := runtime.ArrayStoreState(sourceHandle)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, 0, 0, 0, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif err := runtime.ArrayStoreTrackStructInstanceLease(inst, sourceHandle); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, 0, 0, 0, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tsourceValues = make([]runtime.Value, len(state.Values), state.Capacity)\n")
	fmt.Fprintf(buf, "\t\tcopy(sourceValues, state.Values)\n")
	fmt.Fprintf(buf, "\t\tsourceLength = int32(len(state.Values))\n")
	fmt.Fprintf(buf, "\t\tsourceCapacity = int32(state.Capacity)\n")
	fmt.Fprintf(buf, "\t} else {\n")
	fmt.Fprintf(buf, "\t\tif sourceCapacity < sourceLength {\n")
	fmt.Fprintf(buf, "\t\t\tsourceCapacity = sourceLength\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif sourceCapacity > 0 {\n")
	fmt.Fprintf(buf, "\t\t\tsourceValues = make([]runtime.Value, int(sourceLength), int(sourceCapacity))\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn sourceValues, sourceHandle, sourceLength, sourceCapacity, nil\n")
	fmt.Fprintf(buf, "}\n\n")
}
