package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderRuntimeStringHelpers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "func __able_int64_from_value(val runtime.Value, label string) (int64, error) {\n")
	fmt.Fprintf(buf, "\tcurrent := __able_unwrap_interface(val)\n")
	fmt.Fprintf(buf, "\tif v, ok, nilPtr := __able_runtime_integer_value(current); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif !ok || nilPtr || v.Val == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"%%s is nil\", label)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !v.Val.IsInt64() {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"%%s must fit in 64-bit integer\", label)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn v.Val.Int64(), nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn 0, fmt.Errorf(\"%%s must be an integer\", label)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_new_array_from_values(values []runtime.Value) (*runtime.ArrayValue, error) {\n")
	fmt.Fprintf(buf, "\tarr := &runtime.ArrayValue{Elements: values}\n")
	fmt.Fprintf(buf, "\tif _, _, err := runtime.ArrayStoreEnsure(arr, len(values)); err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn arr, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_string_bytes_from_struct(inst *runtime.StructInstanceValue) (*runtime.ArrayValue, error) {\n")
	fmt.Fprintf(buf, "\tif inst == nil || inst.Definition == nil || inst.Definition.Node == nil || inst.Definition.Node.ID == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"argument must be a string\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif inst.Definition.Node.ID.Name != \"String\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"argument must be a string\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvar bytesVal runtime.Value\n")
	fmt.Fprintf(buf, "\tif inst.Fields != nil {\n")
	fmt.Fprintf(buf, "\t\tif field, ok := inst.Fields[\"bytes\"]; ok {\n")
	fmt.Fprintf(buf, "\t\t\tbytesVal = field\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif bytesVal == nil && len(inst.Positional) > 0 {\n")
	fmt.Fprintf(buf, "\t\tbytesVal = inst.Positional[0]\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif bytesVal == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"string bytes are missing\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvalues, ok := __able_array_values(bytesVal)\n")
	fmt.Fprintf(buf, "\tif !ok && __able_is_callable_value(bytesVal) {\n")
	fmt.Fprintf(buf, "\t\tresolved := __able_call_value(bytesVal, nil, nil)\n")
	fmt.Fprintf(buf, "\t\tvalues, ok = __able_array_values(resolved)\n")
	fmt.Fprintf(buf, "\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\tbytesVal = resolved\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif !ok && __able_runtime != nil {\n")
	fmt.Fprintf(buf, "\t\tif iter, err := bridge.ResolveIterator(__able_runtime, bytesVal); err == nil && iter != nil {\n")
	fmt.Fprintf(buf, "\t\t\tdefer iter.Close()\n")
	fmt.Fprintf(buf, "\t\t\tvalues = make([]runtime.Value, 0)\n")
	fmt.Fprintf(buf, "\t\t\tfor {\n")
	fmt.Fprintf(buf, "\t\t\t\tnext, done, nextErr := iter.Next()\n")
	fmt.Fprintf(buf, "\t\t\t\tif nextErr != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn nil, nextErr\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tif done {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tvalues = append(values, next)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tok = true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif !ok {\n")
	fmt.Fprintf(buf, "\t\tdetail := fmt.Sprintf(\"%%T\", bytesVal)\n")
	fmt.Fprintf(buf, "\t\tif inst := __able_struct_instance(__able_unwrap_interface(bytesVal)); inst != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil && inst.Definition.Node.ID.Name != \"\" {\n")
	fmt.Fprintf(buf, "\t\t\t\tdetail = fmt.Sprintf(\"%%s:%%s\", detail, inst.Definition.Node.ID.Name)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"string bytes must be an array (got %%s)\", detail)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcloned := make([]runtime.Value, len(values))\n")
	fmt.Fprintf(buf, "\tcopy(cloned, values)\n")
	fmt.Fprintf(buf, "\treturn __able_new_array_from_values(cloned)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_string_from_builtin_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_String_from_builtin expects one argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval := __able_unwrap_interface(args[0])\n")
	fmt.Fprintf(buf, "\tif str, ok, nilPtr := __able_runtime_string_value(val); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"string argument is nil\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tdata := []byte(str.Val)\n")
	fmt.Fprintf(buf, "\t\telements := make([]runtime.Value, len(data))\n")
	fmt.Fprintf(buf, "\t\tfor idx, b := range data {\n")
	fmt.Fprintf(buf, "\t\t\telements[idx] = runtime.IntegerValue{Val: big.NewInt(int64(b)), TypeSuffix: runtime.IntegerU8}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_new_array_from_values(elements)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif inst, ok, nilPtr := __able_runtime_struct_instance_value(val); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"argument must be a string\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_string_bytes_from_struct(inst)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil, fmt.Errorf(\"argument must be a string\")\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_string_to_builtin_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_String_to_builtin expects one argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvalues, ok := __able_array_values(args[0])\n")
	fmt.Fprintf(buf, "\tif !ok {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"argument must be an array\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbytes := make([]byte, len(values))\n")
	fmt.Fprintf(buf, "\tfor idx, element := range values {\n")
	fmt.Fprintf(buf, "\t\tnum, err := __able_int64_from_value(element, fmt.Sprintf(\"array element %%d\", idx))\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif num < 0 || num > 0xff {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"array element %%d must be in range 0..255\", idx)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbytes[idx] = byte(num)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif !utf8.Valid(bytes) {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"invalid UTF-8 byte sequence\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.StringValue{Val: string(bytes)}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_char_from_codepoint_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_char_from_codepoint expects one argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcodepoint, err := __able_int64_from_value(args[0], \"codepoint\")\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif codepoint < 0 || codepoint > utf8.MaxRune {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"codepoint must be within Unicode range 0..0x10FFFF\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tr := rune(codepoint)\n")
	fmt.Fprintf(buf, "\tif !utf8.ValidRune(r) {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"invalid Unicode codepoint %%d\", codepoint)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.CharValue{Val: r}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_char_to_codepoint_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_char_to_codepoint expects one argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval := __able_unwrap_interface(args[0])\n")
	fmt.Fprintf(buf, "\tif ch, ok, nilPtr := __able_runtime_char_value(val); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"char argument is nil\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn runtime.IntegerValue{Val: big.NewInt(int64(ch.Val)), TypeSuffix: runtime.IntegerI32}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil, fmt.Errorf(\"argument must be a char\")\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_string_from_builtin(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_string_from_builtin_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_string_to_builtin(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_string_to_builtin_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_char_from_codepoint(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_char_from_codepoint_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_char_to_codepoint(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_char_to_codepoint_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
}
