package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderRuntimeHelpers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "var __able_divmod_def *runtime.StructDefinitionValue\n")
	fmt.Fprintf(buf, "var __able_index_error_def *runtime.StructDefinitionValue\n\n")
	g.renderControlHelpers(buf)
	g.renderRuntimeBuiltinHelpers(buf)
	g.renderRuntimeAnyHelpers(buf)
	fmt.Fprintf(buf, "func __able_runtime_value_or_nil(value runtime.Value) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif value == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn value\n")
	fmt.Fprintf(buf, "}\n\n")
	g.renderRuntimeNullableHelpers(buf)
	fmt.Fprintf(buf, "func __able_unwrap_interface(val runtime.Value) runtime.Value {\n")
	fmt.Fprintf(buf, "\tfor {\n")
	fmt.Fprintf(buf, "\t\tswitch v := val.(type) {\n")
	fmt.Fprintf(buf, "\t\tcase runtime.InterfaceValue:\n")
	fmt.Fprintf(buf, "\t\t\tval = v.Underlying\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\tcase *runtime.InterfaceValue:\n")
	fmt.Fprintf(buf, "\t\t\tif v != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tval = v.Underlying\n")
	fmt.Fprintf(buf, "\t\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tbreak\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val\n")
	fmt.Fprintf(buf, "}\n\n")
	g.renderRuntimeArrayHelpers(buf)
	g.renderRuntimeHashMapHelpers(buf)
	g.renderRuntimeStringHelpers(buf)
	if g.needsStringFromByteArray {
		g.renderStringFromByteArrayHelper(buf)
	}
	g.renderRuntimeNumericHelpers(buf)
	g.renderRuntimeConcurrencyHelpers(buf)
	g.renderRuntimeFutureHelpers(buf)
	g.renderRuntimeAwaitHelpers(buf)
	g.renderRuntimeInterfaceDispatch(buf)
	fmt.Fprintf(buf, "func __able_index(obj runtime.Value, idx runtime.Value) (runtime.Value, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbase := __able_unwrap_interface(obj)\n")
	fmt.Fprintf(buf, "\tif arr, ok, _ := __able_runtime_array_value(base); ok {\n")
	fmt.Fprintf(buf, "\t\tif arr.Handle == 0 {\n")
	fmt.Fprintf(buf, "\t\t\tval, err := __able_array_index(arr, idx)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn val, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tindex, err := __able_index_from_value(idx)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tlength, err := runtime.ArrayStoreSize(arr.Handle)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif index < 0 || index >= length {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_index_error(index, length), nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tval, err := runtime.ArrayStoreRead(arr.Handle, index)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_index_error(index, length), nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn val, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif inst := __able_struct_instance(base); inst != nil {\n")
	fmt.Fprintf(buf, "\t\tif inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil && inst.Definition.Node.ID.Name == \"Array\" {\n")
	fmt.Fprintf(buf, "\t\t\thandleVal, ok := inst.Fields[\"storage_handle\"]\n")
	fmt.Fprintf(buf, "\t\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_runtime_error_control(nil, fmt.Errorf(\"array value missing storage_handle\"))\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\thandle, err := __able_array_handle_from_value(handleVal)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tindex, err := __able_index_from_value(idx)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tlength, err := runtime.ArrayStoreSize(handle)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif index < 0 || index >= length {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn __able_index_error(index, length), nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tval, err := runtime.ArrayStoreRead(handle, index)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn __able_index_error(index, length), nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn val, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil && inst.Definition.Node.ID.Name == \"HashMap\" {\n")
	fmt.Fprintf(buf, "\t\t\thandleVal, ok := inst.Fields[\"handle\"]\n")
	fmt.Fprintf(buf, "\t\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_runtime_error_control(nil, fmt.Errorf(\"hash map value missing handle\"))\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif _, err := __able_hash_map_handle_from_value(handleVal); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tval, err := __able_hash_map_get_impl([]runtime.Value{handleVal, idx})\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif __able_is_nil(val) {\n")
	fmt.Fprintf(buf, "\t\t\t\tsizeVal, err := __able_hash_map_size_impl([]runtime.Value{handleVal})\n")
	fmt.Fprintf(buf, "\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\tlength, err := __able_array_index_from_value(sizeVal)\n")
	fmt.Fprintf(buf, "\t\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\treturn __able_index_error(-1, length), nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn val, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := bridge.Index(__able_runtime, obj, idx)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_range_endpoint(val runtime.Value) (int, error) {\n")
	fmt.Fprintf(buf, "\tswitch v := val.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tn, ok := v.ToInt64()\n")
	fmt.Fprintf(buf, "\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"Range endpoint must be within int range\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn int(n), nil\n")
	fmt.Fprintf(buf, "\tcase runtime.FloatValue:\n")
	fmt.Fprintf(buf, "\t\tif math.IsNaN(v.Val) || math.IsInf(v.Val, 0) {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"Range endpoint must be finite\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn int(math.Trunc(v.Val)), nil\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn 0, fmt.Errorf(\"range endpoint must be numeric, got %%s\", val.Kind())\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_range(start runtime.Value, end runtime.Value, inclusive bool) runtime.Value {\n")
	fmt.Fprintf(buf, "\tstartVal, err := __able_range_endpoint(start)\n")
	fmt.Fprintf(buf, "\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\tendVal, err := __able_range_endpoint(end)\n")
	fmt.Fprintf(buf, "\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\tstep := 1\n")
	fmt.Fprintf(buf, "\tif startVal > endVal {\n")
	fmt.Fprintf(buf, "\t\tstep = -1\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\telements := make([]runtime.Value, 0)\n")
	fmt.Fprintf(buf, "\tfor current := startVal; ; current += step {\n")
	fmt.Fprintf(buf, "\t\tif step > 0 {\n")
	fmt.Fprintf(buf, "\t\t\tif inclusive {\n")
	fmt.Fprintf(buf, "\t\t\t\tif current > endVal {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t} else if current >= endVal {\n")
	fmt.Fprintf(buf, "\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t} else {\n")
	fmt.Fprintf(buf, "\t\t\tif inclusive {\n")
	fmt.Fprintf(buf, "\t\t\t\tif current < endVal {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t} else if current <= endVal {\n")
	fmt.Fprintf(buf, "\t\t\t\tbreak\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\telements = append(elements, runtime.NewSmallInt(int64(current), runtime.IntegerI32))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn &runtime.ArrayValue{Elements: elements}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_resolve_iterator(iterable runtime.Value) *runtime.IteratorValue {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tit, err := bridge.ResolveIterator(__able_runtime, iterable)\n")
	fmt.Fprintf(buf, "\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\tif it == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"iterator is nil\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn it\n")
	fmt.Fprintf(buf, "}\n\n")
	if g.needsIterator {
		g.renderIteratorHelpers(buf)
	}
	fmt.Fprintf(buf, "func __able_index_set(obj runtime.Value, idx runtime.Value, value runtime.Value) (runtime.Value, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tbase := __able_unwrap_interface(obj)\n")
	fmt.Fprintf(buf, "\tif arr, ok, _ := __able_runtime_array_value(base); ok {\n")
	fmt.Fprintf(buf, "\t\tif arr.Handle == 0 {\n")
	fmt.Fprintf(buf, "\t\t\tval, err := __able_array_index_set(arr, idx, value)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn val, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tindex, err := __able_index_from_value(idx)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tlength, err := runtime.ArrayStoreSize(arr.Handle)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif index < 0 || index >= length {\n")
	fmt.Fprintf(buf, "\t\t\treturn __able_index_error(index, length), nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif err := runtime.ArrayStoreWrite(arr.Handle, index, value); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif inst := __able_struct_instance(base); inst != nil {\n")
	fmt.Fprintf(buf, "\t\tif inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil && inst.Definition.Node.ID.Name == \"Array\" {\n")
	fmt.Fprintf(buf, "\t\t\thandleVal, ok := inst.Fields[\"storage_handle\"]\n")
	fmt.Fprintf(buf, "\t\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_runtime_error_control(nil, fmt.Errorf(\"array value missing storage_handle\"))\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\thandle, err := __able_array_handle_from_value(handleVal)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tindex, err := __able_index_from_value(idx)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tlength, err := runtime.ArrayStoreSize(handle)\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif index < 0 || index >= length {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn __able_index_error(index, length), nil\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif err := runtime.ArrayStoreWrite(handle, index, value); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif inst.Definition != nil && inst.Definition.Node != nil && inst.Definition.Node.ID != nil && inst.Definition.Node.ID.Name == \"HashMap\" {\n")
	fmt.Fprintf(buf, "\t\t\thandleVal, ok := inst.Fields[\"handle\"]\n")
	fmt.Fprintf(buf, "\t\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_runtime_error_control(nil, fmt.Errorf(\"hash map value missing handle\"))\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tif _, err := __able_hash_map_handle_from_value(handleVal); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t_, err := __able_hash_map_set_impl([]runtime.Value{handleVal, idx, value})\n")
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn value, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := bridge.IndexAssign(__able_runtime, obj, idx, value)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	g.renderRuntimeCallHelpers(buf)
	if len(g.diagNodes) > 0 {
		fmt.Fprintf(buf, "func __able_register_diag_nodes() {\n")
		fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
		fmt.Fprintf(buf, "\t\treturn\n")
		fmt.Fprintf(buf, "\t}\n")
		for _, info := range g.diagNodes {
			span := info.Span
			fmt.Fprintf(buf, "\tast.SetSpan(%s, ast.Span{Start: ast.Position{Line: %d, Column: %d}, End: ast.Position{Line: %d, Column: %d}})\n", info.Name, span.Start.Line, span.Start.Column, span.End.Line, span.End.Column)
			if info.Origin != "" {
				fmt.Fprintf(buf, "\tbridge.RegisterNodeOrigin(__able_runtime, %s, %q)\n", info.Name, info.Origin)
			}
		}
		fmt.Fprintf(buf, "}\n\n")
	}
	fmt.Fprintf(buf, "func __able_panic_on_error(err error) {\n")
	fmt.Fprintf(buf, "\tif err == nil {\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tswitch v := err.(type) {\n")
	fmt.Fprintf(buf, "\tcase __able_value_error:\n")
	fmt.Fprintf(buf, "\t\tif __able_runtime != nil {\n")
	fmt.Fprintf(buf, "\t\t\tbridge.RaiseWithContext(__able_runtime, nil, v.value)\n")
	fmt.Fprintf(buf, "\t\t\treturn\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\tcase *__able_value_error:\n")
	fmt.Fprintf(buf, "\t\tif v != nil {\n")
	fmt.Fprintf(buf, "\t\t\tif __able_runtime != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tbridge.RaiseWithContext(__able_runtime, nil, v.value)\n")
	fmt.Fprintf(buf, "\t\t\t\treturn\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tpanic(err)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_is_nil(val runtime.Value) bool {\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t_, ok, nilPtr := __able_runtime_nil_value(val)\n")
	fmt.Fprintf(buf, "\treturn ok || nilPtr\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_is_error(val runtime.Value) bool {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.IsError(__able_runtime, val)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_truthy(val runtime.Value) bool {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.IsTruthy(__able_runtime, val)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_error_to_struct(err runtime.ErrorValue) *runtime.StructInstanceValue {\n")
	fmt.Fprintf(buf, "\tif err.Payload != nil {\n")
	fmt.Fprintf(buf, "\t\tif value, ok := err.Payload[\"value\"]; ok {\n")
	fmt.Fprintf(buf, "\t\t\tif inst, ok, nilPtr := __able_runtime_struct_instance_value(value); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn nil\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\treturn inst\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfields := make(map[string]runtime.Value)\n")
	fmt.Fprintf(buf, "\tif err.Payload != nil {\n")
	fmt.Fprintf(buf, "\t\tfor k, v := range err.Payload {\n")
	fmt.Fprintf(buf, "\t\t\tfields[k] = v\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfields[\"message\"] = runtime.StringValue{Val: err.Message}\n")
	fmt.Fprintf(buf, "\treturn &runtime.StructInstanceValue{Fields: fields}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_struct_instance(value runtime.Value) *runtime.StructInstanceValue {\n")
	fmt.Fprintf(buf, "\tif inst, ok, nilPtr := __able_runtime_struct_instance_value(value); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn inst\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif errVal, ok, nilPtr := __able_runtime_error_value(value); ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\tif !ok || nilPtr {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn __able_error_to_struct(errVal)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_error_value(value runtime.Value) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.ErrorValue(__able_runtime, value)\n")
	fmt.Fprintf(buf, "}\n\n")
	if g.needsAst {
		fmt.Fprintf(buf, "func __able_cast(value runtime.Value, typeExpr ast.TypeExpression) (runtime.Value, *__ableControl) {\n")
		fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
		fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
		fmt.Fprintf(buf, "\t}\n")
		fmt.Fprintf(buf, "\tval, err := bridge.Cast(__able_runtime, typeExpr, value)\n")
		fmt.Fprintf(buf, "\tif err != nil {\n")
		fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
		fmt.Fprintf(buf, "\t}\n")
		fmt.Fprintf(buf, "\tif val == nil {\n")
		fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
		fmt.Fprintf(buf, "\t}\n")
		fmt.Fprintf(buf, "\treturn val, nil\n")
		fmt.Fprintf(buf, "}\n\n")
		fmt.Fprintf(buf, "func __able_try_cast(value runtime.Value, typeExpr ast.TypeExpression) (runtime.Value, bool, *__ableControl) {\n")
		fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
		fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
		fmt.Fprintf(buf, "\t}\n")
		fmt.Fprintf(buf, "\tval, ok, err := bridge.MatchType(__able_runtime, typeExpr, value)\n")
		fmt.Fprintf(buf, "\tif err != nil {\n")
		fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, false, __able_control_from_error(err)\n")
		fmt.Fprintf(buf, "\t}\n")
		fmt.Fprintf(buf, "\tif !ok {\n")
		fmt.Fprintf(buf, "\t\treturn nil, false, nil\n")
		fmt.Fprintf(buf, "\t}\n")
		fmt.Fprintf(buf, "\tif val == nil {\n")
		fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, true, nil\n")
		fmt.Fprintf(buf, "\t}\n")
		fmt.Fprintf(buf, "\treturn val, true, nil\n")
		fmt.Fprintf(buf, "}\n\n")
	}
	fmt.Fprintf(buf, "func __able_stringify(val runtime.Value) string {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstr, err := bridge.Stringify(__able_runtime, val)\n")
	fmt.Fprintf(buf, "\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\treturn str\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_raise_division_by_zero(node ast.Node) *__ableControl {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn __able_raise_control(node, bridge.DivisionByZeroError(__able_runtime))\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_raise_overflow(node ast.Node) *__ableControl {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn __able_raise_control(node, bridge.OverflowError(__able_runtime, \"integer overflow\"))\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_raise_shift_out_of_range(shift int64, node ast.Node) *__ableControl {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn __able_raise_control(node, bridge.ShiftOutOfRangeError(__able_runtime, shift))\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_raise_runtime_error(node ast.Node, message string) *__ableControl {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn __able_runtime_error_control(node, fmt.Errorf(\"%%s\", message))\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_raise_return_type_mismatch(node ast.Node, expected string, actual string) *__ableControl {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\terr := fmt.Errorf(\"Return type mismatch: expected %%s, got %%s\", expected, actual)\n")
	fmt.Fprintf(buf, "\treturn __able_runtime_error_control(node, err)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_signed_bounds(bits int) (int64, int64) {\n")
	fmt.Fprintf(buf, "\tif bits >= 64 {\n")
	fmt.Fprintf(buf, "\t\tmax := int64(^uint64(0) >> 1)\n")
	fmt.Fprintf(buf, "\t\treturn -max - 1, max\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tmax := int64(1<<(bits-1)) - 1\n")
	fmt.Fprintf(buf, "\tmin := -int64(1 << (bits - 1))\n")
	fmt.Fprintf(buf, "\treturn min, max\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_unsigned_max(bits int) uint64 {\n")
	fmt.Fprintf(buf, "\tif bits >= 64 {\n")
	fmt.Fprintf(buf, "\t\treturn ^uint64(0)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn (uint64(1) << uint(bits)) - 1\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_abs_u64(value int64) uint64 {\n")
	fmt.Fprintf(buf, "\tif value >= 0 {\n")
	fmt.Fprintf(buf, "\t\treturn uint64(value)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn uint64(^value) + 1\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_checked_add_signed(a int64, b int64, width int, node ast.Node) (int64, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif width >= 64 {\n")
	fmt.Fprintf(buf, "\t\tresult := int64(uint64(a) + uint64(b))\n")
	fmt.Fprintf(buf, "\t\tif (a > 0 && b > 0 && result < 0) || (a < 0 && b < 0 && result >= 0) {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn result, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tresult := a + b\n")
	fmt.Fprintf(buf, "\tmin, max := __able_signed_bounds(width)\n")
	fmt.Fprintf(buf, "\tif result < min || result > max {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn result, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_checked_sub_signed(a int64, b int64, width int, node ast.Node) (int64, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif width >= 64 {\n")
	fmt.Fprintf(buf, "\t\tresult := int64(uint64(a) - uint64(b))\n")
	fmt.Fprintf(buf, "\t\tif (a >= 0 && b < 0 && result < 0) || (a < 0 && b > 0 && result >= 0) {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn result, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tresult := a - b\n")
	fmt.Fprintf(buf, "\tmin, max := __able_signed_bounds(width)\n")
	fmt.Fprintf(buf, "\tif result < min || result > max {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn result, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_checked_mul_signed(a int64, b int64, width int, node ast.Node) (int64, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif width >= 64 {\n")
	fmt.Fprintf(buf, "\t\tabsA := __able_abs_u64(a)\n")
	fmt.Fprintf(buf, "\t\tabsB := __able_abs_u64(b)\n")
	fmt.Fprintf(buf, "\t\tupper, lower := bits.Mul64(absA, absB)\n")
	fmt.Fprintf(buf, "\t\tif upper != 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tnegative := (a < 0) != (b < 0)\n")
	fmt.Fprintf(buf, "\t\tif !negative {\n")
	fmt.Fprintf(buf, "\t\t\tmax := uint64(^uint64(0) >> 1)\n")
	fmt.Fprintf(buf, "\t\t\tif lower > max {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\treturn int64(lower), nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tlimit := uint64(1) << 63\n")
	fmt.Fprintf(buf, "\t\tif lower > limit {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif lower == limit {\n")
	fmt.Fprintf(buf, "\t\t\treturn int64(lower), nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn -int64(lower), nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tresult := a * b\n")
	fmt.Fprintf(buf, "\tmin, max := __able_signed_bounds(width)\n")
	fmt.Fprintf(buf, "\tif result < min || result > max {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn result, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_checked_add_unsigned(a uint64, b uint64, width int, node ast.Node) (uint64, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif width >= 64 {\n")
	fmt.Fprintf(buf, "\t\tsum, carry := bits.Add64(a, b, 0)\n")
	fmt.Fprintf(buf, "\t\tif carry != 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn sum, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tresult := a + b\n")
	fmt.Fprintf(buf, "\tif result > __able_unsigned_max(width) {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn result, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_checked_sub_unsigned(a uint64, b uint64, width int, node ast.Node) (uint64, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif a < b {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tresult := a - b\n")
	fmt.Fprintf(buf, "\tif width < 64 && result > __able_unsigned_max(width) {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn result, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_checked_mul_unsigned(a uint64, b uint64, width int, node ast.Node) (uint64, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif width >= 64 {\n")
	fmt.Fprintf(buf, "\t\tupper, lower := bits.Mul64(a, b)\n")
	fmt.Fprintf(buf, "\t\tif upper != 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn lower, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tresult := a * b\n")
	fmt.Fprintf(buf, "\tif result > __able_unsigned_max(width) {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn result, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_pow_signed(base int64, exp int64, bits int, node ast.Node) (int64, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif exp < 0 {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_runtime_error(node, \"Negative integer exponent is not supported\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tresult := int64(1)\n")
	fmt.Fprintf(buf, "\tcurrent := base\n")
	fmt.Fprintf(buf, "\tvalue := exp\n")
	fmt.Fprintf(buf, "\tfor value > 0 {\n")
	fmt.Fprintf(buf, "\t\tif value&1 == 1 {\n")
	fmt.Fprintf(buf, "\t\t\tnext, control := __able_checked_mul_signed(result, current, bits, node)\n")
	fmt.Fprintf(buf, "\t\t\tif control != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn 0, control\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tresult = next\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tvalue >>= 1\n")
	fmt.Fprintf(buf, "\t\tif value > 0 {\n")
	fmt.Fprintf(buf, "\t\t\tnext, control := __able_checked_mul_signed(current, current, bits, node)\n")
	fmt.Fprintf(buf, "\t\t\tif control != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn 0, control\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tcurrent = next\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn result, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_pow_unsigned(base uint64, exp uint64, bits int, node ast.Node) (uint64, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tresult := uint64(1)\n")
	fmt.Fprintf(buf, "\tcurrent := base\n")
	fmt.Fprintf(buf, "\tvalue := exp\n")
	fmt.Fprintf(buf, "\tfor value > 0 {\n")
	fmt.Fprintf(buf, "\t\tif value&1 == 1 {\n")
	fmt.Fprintf(buf, "\t\t\tnext, control := __able_checked_mul_unsigned(result, current, bits, node)\n")
	fmt.Fprintf(buf, "\t\t\tif control != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn 0, control\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tresult = next\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tvalue >>= 1\n")
	fmt.Fprintf(buf, "\t\tif value > 0 {\n")
	fmt.Fprintf(buf, "\t\t\tnext, control := __able_checked_mul_unsigned(current, current, bits, node)\n")
	fmt.Fprintf(buf, "\t\t\tif control != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn 0, control\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tcurrent = next\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn result, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_pow_float64(base float64, exp float64) float64 {\n")
	fmt.Fprintf(buf, "\treturn math.Pow(base, exp)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_pow_float32(base float32, exp float32) float32 {\n")
	fmt.Fprintf(buf, "\treturn float32(math.Pow(float64(base), float64(exp)))\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_shift_left_signed(value int64, shift int64, bits int, node ast.Node) (int64, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif shift < 0 || shift >= int64(bits) {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_shift_out_of_range(shift, node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tmin, max := __able_signed_bounds(bits)\n")
	fmt.Fprintf(buf, "\tif shift > 0 {\n")
	fmt.Fprintf(buf, "\t\tif value > max>>shift || value < min>>shift {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn value << shift, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_shift_right_signed(value int64, shift int64, bits int, node ast.Node) (int64, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif shift < 0 || shift >= int64(bits) {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_shift_out_of_range(shift, node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn value >> shift, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_shift_left_unsigned(value uint64, shift uint64, bits int, node ast.Node) (uint64, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif shift > uint64(^uint64(0)>>1) {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_shift_out_of_range(0, node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\ts := int64(shift)\n")
	fmt.Fprintf(buf, "\tif s < 0 || s >= int64(bits) {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_shift_out_of_range(s, node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tmax := __able_unsigned_max(bits)\n")
	fmt.Fprintf(buf, "\tif s > 0 && value > max>>s {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn value << s, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_shift_right_unsigned(value uint64, shift uint64, bits int, node ast.Node) (uint64, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif shift > uint64(^uint64(0)>>1) {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_shift_out_of_range(0, node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\ts := int64(shift)\n")
	fmt.Fprintf(buf, "\tif s < 0 || s >= int64(bits) {\n")
	fmt.Fprintf(buf, "\t\treturn 0, __able_raise_shift_out_of_range(s, node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn value >> s, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_binary_op(op string, left runtime.Value, right runtime.Value) (runtime.Value, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif val, ok, err := __able_ratio_binary_op(op, left, right); ok {\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn val, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val, ok, err := interpreter.ApplyBinaryOperatorFast(op, left, right); ok {\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn val, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := bridge.ApplyBinaryOperator(__able_runtime, op, left, right)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_unary_op(op string, operand runtime.Value) (runtime.Value, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif val, ok, err := interpreter.ApplyUnaryOperatorFast(op, operand); ok {\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn val, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\tpanic(fmt.Errorf(\"compiler: missing runtime\"))\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := bridge.ApplyUnaryOperator(__able_runtime, op, operand)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, __able_control_from_error(err)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_divmod_signed(a int64, b int64, bits int, node ast.Node) (int64, int64, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif b == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn 0, 0, __able_raise_division_by_zero(node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tmin, max := __able_signed_bounds(bits)\n")
	fmt.Fprintf(buf, "\tif b == -1 && a == min {\n")
	fmt.Fprintf(buf, "\t\treturn 0, 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tq := a / b\n")
	fmt.Fprintf(buf, "\tr := a %% b\n")
	fmt.Fprintf(buf, "\tif r < 0 {\n")
	fmt.Fprintf(buf, "\t\tif b > 0 {\n")
	fmt.Fprintf(buf, "\t\t\tq -= 1\n")
	fmt.Fprintf(buf, "\t\t\tr += b\n")
	fmt.Fprintf(buf, "\t\t} else {\n")
	fmt.Fprintf(buf, "\t\t\tq += 1\n")
	fmt.Fprintf(buf, "\t\t\tr -= b\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif q < min || q > max || r < min || r > max {\n")
	fmt.Fprintf(buf, "\t\treturn 0, 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn q, r, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_divmod_unsigned(a uint64, b uint64, bits int, node ast.Node) (uint64, uint64, *__ableControl) {\n")
	fmt.Fprintf(buf, "\tif b == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn 0, 0, __able_raise_division_by_zero(node)\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tq := a / b\n")
	fmt.Fprintf(buf, "\tr := a %% b\n")
	fmt.Fprintf(buf, "\tif bits < 64 {\n")
	fmt.Fprintf(buf, "\t\tmax := __able_unsigned_max(bits)\n")
	fmt.Fprintf(buf, "\t\tif q > max || r > max {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, 0, __able_raise_overflow(node)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn q, r, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_divmod_struct() *runtime.StructDefinitionValue {\n")
	fmt.Fprintf(buf, "\tif __able_divmod_def != nil {\n")
	fmt.Fprintf(buf, "\t\treturn __able_divmod_def\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_runtime != nil {\n")
	fmt.Fprintf(buf, "\t\tif def, err := __able_runtime.StructDefinition(\"DivMod\"); err == nil && def != nil {\n")
	fmt.Fprintf(buf, "\t\t\t__able_divmod_def = def\n")
	fmt.Fprintf(buf, "\t\t\treturn def\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tparam := ast.NewGenericParameter(ast.NewIdentifier(\"T\"), nil)\n")
	fmt.Fprintf(buf, "\tquotientField := ast.NewStructFieldDefinition(ast.NewSimpleTypeExpression(ast.NewIdentifier(\"T\")), ast.NewIdentifier(\"quotient\"))\n")
	fmt.Fprintf(buf, "\tremainderField := ast.NewStructFieldDefinition(ast.NewSimpleTypeExpression(ast.NewIdentifier(\"T\")), ast.NewIdentifier(\"remainder\"))\n")
	fmt.Fprintf(buf, "\tdefinition := ast.NewStructDefinition(ast.NewIdentifier(\"DivMod\"), []*ast.StructFieldDefinition{quotientField, remainderField}, ast.StructKindNamed, []*ast.GenericParameter{param}, nil, false)\n")
	fmt.Fprintf(buf, "\tdef := &runtime.StructDefinitionValue{Node: definition}\n")
	fmt.Fprintf(buf, "\t__able_divmod_def = def\n")
	fmt.Fprintf(buf, "\treturn def\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_divmod_result(quotient runtime.Value, remainder runtime.Value, typeArg ast.TypeExpression) runtime.Value {\n")
	fmt.Fprintf(buf, "\tdef := __able_divmod_struct()\n")
	fmt.Fprintf(buf, "\tfields := map[string]runtime.Value{\"quotient\": quotient, \"remainder\": remainder}\n")
	fmt.Fprintf(buf, "\targs := []ast.TypeExpression{typeArg}\n")
	fmt.Fprintf(buf, "\treturn &runtime.StructInstanceValue{Definition: def, Fields: fields, TypeArguments: args}\n")
	fmt.Fprintf(buf, "}\n\n")
}

func (g *generator) renderIteratorHelpers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "type __able_generator_stop struct{}\n\n")
	fmt.Fprintf(buf, "func (__able_generator_stop) Error() string { return \"generator stopped\" }\n\n")
	fmt.Fprintf(buf, "func __able_is_generator_stop(err error) bool {\n")
	fmt.Fprintf(buf, "\tif err == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tvar stop __able_generator_stop\n")
	fmt.Fprintf(buf, "\treturn errors.As(err, &stop)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_generator_result struct {\n")
	fmt.Fprintf(buf, "\tvalue runtime.Value\n")
	fmt.Fprintf(buf, "\tdone bool\n")
	fmt.Fprintf(buf, "\terr error\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_generator struct {\n")
	fmt.Fprintf(buf, "\trequests chan struct{}\n")
	fmt.Fprintf(buf, "\tresults chan __able_generator_result\n")
	fmt.Fprintf(buf, "\tmu sync.Mutex\n")
	fmt.Fprintf(buf, "\tclosed bool\n")
	fmt.Fprintf(buf, "\tbusy bool\n")
	fmt.Fprintf(buf, "\tdone bool\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_new_iterator(run func(gen *__able_generator) error) *runtime.IteratorValue {\n")
	fmt.Fprintf(buf, "\tgen := &__able_generator{requests: make(chan struct{}), results: make(chan __able_generator_result)}\n")
	fmt.Fprintf(buf, "\tgo gen.run(run)\n")
	fmt.Fprintf(buf, "\treturn runtime.NewIteratorValue(gen.next, gen.close)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (g *__able_generator) run(run func(gen *__able_generator) error) {\n")
	fmt.Fprintf(buf, "\tdefer close(g.results)\n")
	fmt.Fprintf(buf, "\tif !g.awaitRequest() {\n\t\treturn\n\t}\n")
	fmt.Fprintf(buf, "\tvar runErr error\n")
	fmt.Fprintf(buf, "\tfunc() {\n")
	fmt.Fprintf(buf, "\t\tdefer func() {\n")
	fmt.Fprintf(buf, "\t\t\tif r := recover(); r != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tif err, ok := r.(error); ok {\n")
	fmt.Fprintf(buf, "\t\t\t\t\tif __able_is_generator_stop(err) {\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\trunErr = __able_generator_stop{}\n")
	fmt.Fprintf(buf, "\t\t\t\t\t\treturn\n")
	fmt.Fprintf(buf, "\t\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\t\trunErr = err\n")
	fmt.Fprintf(buf, "\t\t\t\t\treturn\n")
	fmt.Fprintf(buf, "\t\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\t\trunErr = bridge.Recover(__able_runtime, nil, r)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t}()\n")
	fmt.Fprintf(buf, "\t\trunErr = run(g)\n")
	fmt.Fprintf(buf, "\t}()\n")
	fmt.Fprintf(buf, "\tif runErr != nil {\n")
	fmt.Fprintf(buf, "\t\tif __able_is_generator_stop(runErr) {\n")
	fmt.Fprintf(buf, "\t\t\tg.results <- __able_generator_result{done: true}\n")
	fmt.Fprintf(buf, "\t\t\treturn\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tg.results <- __able_generator_result{err: runErr, done: true}\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tg.results <- __able_generator_result{done: true}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (g *__able_generator) next() (runtime.Value, bool, error) {\n")
	fmt.Fprintf(buf, "\tg.mu.Lock()\n")
	fmt.Fprintf(buf, "\tif g.busy {\n")
	fmt.Fprintf(buf, "\t\tg.mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\treturn nil, true, fmt.Errorf(\"iterator.next re-entered while suspended at yield\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif g.closed || g.done {\n")
	fmt.Fprintf(buf, "\t\tg.mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\treturn runtime.IteratorEnd, true, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tg.busy = true\n")
	fmt.Fprintf(buf, "\tg.mu.Unlock()\n")
	fmt.Fprintf(buf, "\tg.requests <- struct{}{}\n")
	fmt.Fprintf(buf, "\tres, ok := <-g.results\n")
	fmt.Fprintf(buf, "\tg.mu.Lock()\n")
	fmt.Fprintf(buf, "\tg.busy = false\n")
	fmt.Fprintf(buf, "\tif !ok {\n")
	fmt.Fprintf(buf, "\t\tg.done = true\n")
	fmt.Fprintf(buf, "\t\tg.mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\treturn runtime.IteratorEnd, true, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif res.err != nil {\n")
	fmt.Fprintf(buf, "\t\tg.done = true\n")
	fmt.Fprintf(buf, "\t\tg.mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\treturn nil, true, res.err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif res.done {\n")
	fmt.Fprintf(buf, "\t\tg.done = true\n")
	fmt.Fprintf(buf, "\t\tg.mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\treturn runtime.IteratorEnd, true, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tg.mu.Unlock()\n")
	fmt.Fprintf(buf, "\tif res.value == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, false, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn res.value, false, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (g *__able_generator) close() {\n")
	fmt.Fprintf(buf, "\tg.mu.Lock()\n")
	fmt.Fprintf(buf, "\tif g.closed {\n")
	fmt.Fprintf(buf, "\t\tg.mu.Unlock()\n")
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tg.closed = true\n")
	fmt.Fprintf(buf, "\tclose(g.requests)\n")
	fmt.Fprintf(buf, "\tg.mu.Unlock()\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (g *__able_generator) awaitRequest() bool {\n")
	fmt.Fprintf(buf, "\t_, ok := <-g.requests\n")
	fmt.Fprintf(buf, "\treturn ok\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (g *__able_generator) emit(value runtime.Value) error {\n")
	fmt.Fprintf(buf, "\tg.results <- __able_generator_result{value: value}\n")
	fmt.Fprintf(buf, "\tif !g.awaitRequest() {\n")
	fmt.Fprintf(buf, "\t\treturn __able_generator_stop{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (g *__able_generator) stop() error {\n")
	fmt.Fprintf(buf, "\tg.close()\n")
	fmt.Fprintf(buf, "\treturn __able_generator_stop{}\n")
	fmt.Fprintf(buf, "}\n\n")
}
