package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderRuntimeArrayHelpers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "func __able_index_from_value(val runtime.Value) (int, error) {\n")
	fmt.Fprintf(buf, "\tcurrent := __able_unwrap_interface(val)\n")
	fmt.Fprintf(buf, "\tswitch v := current.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tif v.Val == nil || !v.Val.IsInt64() {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"Array index must be within int range\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn int(v.Val.Int64()), nil\n")
	fmt.Fprintf(buf, "\tcase *runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tif v == nil || v.Val == nil || !v.Val.IsInt64() {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"Array index must be within int range\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn int(v.Val.Int64()), nil\n")
	fmt.Fprintf(buf, "\tcase runtime.FloatValue:\n")
	fmt.Fprintf(buf, "\t\tif math.IsNaN(v.Val) || math.IsInf(v.Val, 0) {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"Array index must be a number\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn int(math.Trunc(v.Val)), nil\n")
	fmt.Fprintf(buf, "\tcase *runtime.FloatValue:\n")
	fmt.Fprintf(buf, "\t\tif v == nil || math.IsNaN(v.Val) || math.IsInf(v.Val, 0) {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"Array index must be a number\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn int(math.Trunc(v.Val)), nil\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn 0, fmt.Errorf(\"Array index must be a number\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_index_error_struct() *runtime.StructDefinitionValue {\n")
	fmt.Fprintf(buf, "\tif __able_index_error_def != nil {\n")
	fmt.Fprintf(buf, "\t\treturn __able_index_error_def\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_runtime != nil {\n")
	fmt.Fprintf(buf, "\t\tif def, err := __able_runtime.StructDefinition(\"IndexError\"); err == nil && def != nil {\n")
	fmt.Fprintf(buf, "\t\t\t__able_index_error_def = def\n")
	fmt.Fprintf(buf, "\t\t\treturn def\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tindexField := ast.NewStructFieldDefinition(ast.NewSimpleTypeExpression(ast.NewIdentifier(\"i64\")), ast.NewIdentifier(\"index\"))\n")
	fmt.Fprintf(buf, "\tlengthField := ast.NewStructFieldDefinition(ast.NewSimpleTypeExpression(ast.NewIdentifier(\"i64\")), ast.NewIdentifier(\"length\"))\n")
	fmt.Fprintf(buf, "\tdefinition := ast.NewStructDefinition(ast.NewIdentifier(\"IndexError\"), []*ast.StructFieldDefinition{indexField, lengthField}, ast.StructKindNamed, nil, nil, false)\n")
	fmt.Fprintf(buf, "\tdef := &runtime.StructDefinitionValue{Node: definition}\n")
	fmt.Fprintf(buf, "\t__able_index_error_def = def\n")
	fmt.Fprintf(buf, "\treturn def\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_index_error(index int, length int) runtime.ErrorValue {\n")
	fmt.Fprintf(buf, "\tdef := __able_index_error_struct()\n")
	fmt.Fprintf(buf, "\tfields := map[string]runtime.Value{\n")
	fmt.Fprintf(buf, "\t\t\"index\": bridge.ToInt(int64(index), runtime.IntegerI64),\n")
	fmt.Fprintf(buf, "\t\t\"length\": bridge.ToInt(int64(length), runtime.IntegerI64),\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tinstance := &runtime.StructInstanceValue{Definition: def, Fields: fields}\n")
	fmt.Fprintf(buf, "\tmessage := fmt.Sprintf(\"index %%d out of bounds for length %%d\", index, length)\n")
	fmt.Fprintf(buf, "\treturn runtime.ErrorValue{Message: message, Payload: map[string]runtime.Value{\"value\": instance}}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_index(arr *runtime.ArrayValue, idx runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif arr == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"array receiver is nil\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tindex, err := __able_index_from_value(idx)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tlength := len(arr.Elements)\n")
	fmt.Fprintf(buf, "\tif index < 0 || index >= length {\n")
	fmt.Fprintf(buf, "\t\treturn __able_index_error(index, length), nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval := arr.Elements[index]\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn __able_index_error(index, length), nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_index_set(arr *runtime.ArrayValue, idx runtime.Value, value runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif arr == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"array receiver is nil\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tindex, err := __able_index_from_value(idx)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif index < 0 || index >= len(arr.Elements) {\n")
	fmt.Fprintf(buf, "\t\treturn __able_index_error(index, len(arr.Elements)), nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tarr.Elements[index] = value\n")
	fmt.Fprintf(buf, "\treturn value, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_values(iterable runtime.Value) ([]runtime.Value, bool) {\n")
	fmt.Fprintf(buf, "\tbase := __able_unwrap_interface(iterable)\n")
	fmt.Fprintf(buf, "\tarr, ok := base.(*runtime.ArrayValue)\n")
	fmt.Fprintf(buf, "\tif !ok {\n")
	fmt.Fprintf(buf, "\t\tinst := __able_struct_instance(base)\n")
	fmt.Fprintf(buf, "\t\tif inst == nil || inst.Definition == nil || inst.Definition.Node == nil || inst.Definition.Node.ID == nil || inst.Definition.Node.ID.Name != \"Array\" {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\thandle, ok := inst.Fields[\"storage_handle\"]\n")
	fmt.Fprintf(buf, "\t\tif !ok {\n")
	fmt.Fprintf(buf, "\t\t\tpanic(fmt.Errorf(\"array value missing storage_handle\"))\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tsizeVal := __able_extern_array_size([]runtime.Value{handle}, nil)\n")
	fmt.Fprintf(buf, "\t\tlength, err := __able_array_index_from_value(sizeVal)\n")
	fmt.Fprintf(buf, "\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\tvalues := make([]runtime.Value, length)\n")
	fmt.Fprintf(buf, "\t\tfor idx := 0; idx < length; idx++ {\n")
	fmt.Fprintf(buf, "\t\t\tidxVal := bridge.ToInt(int64(idx), runtime.IntegerType(\"i32\"))\n")
	fmt.Fprintf(buf, "\t\t\tvalues[idx] = __able_extern_array_read([]runtime.Value{handle, idxVal}, nil)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn values, true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif arr != nil {\n")
	fmt.Fprintf(buf, "\t\tif arr.Handle == 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn arr.Elements, true\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tstate, err := runtime.ArrayStoreState(arr.Handle)\n")
	fmt.Fprintf(buf, "\t\t__able_panic_on_error(err)\n")
	fmt.Fprintf(buf, "\t\treturn state.Values, true\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn nil, false\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_handle_from_value(val runtime.Value) (int64, error) {\n")
	fmt.Fprintf(buf, "\tcurrent := __able_unwrap_interface(val)\n")
	fmt.Fprintf(buf, "\tswitch v := current.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tif v.Val == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"array handle must be an integer\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !v.Val.IsInt64() {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"array handle is out of range\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn v.Val.Int64(), nil\n")
	fmt.Fprintf(buf, "\tcase *runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tif v == nil || v.Val == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"array handle must be an integer\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !v.Val.IsInt64() {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"array handle is out of range\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn v.Val.Int64(), nil\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn 0, fmt.Errorf(\"array handle must be an integer\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_index_from_value(val runtime.Value) (int, error) {\n")
	fmt.Fprintf(buf, "\tcurrent := __able_unwrap_interface(val)\n")
	fmt.Fprintf(buf, "\tswitch v := current.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tif v.Val == nil || v.Val.Sign() < 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"array index must be an integer\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !v.Val.IsInt64() {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"array index out of range\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tidx := v.Val.Int64()\n")
	fmt.Fprintf(buf, "\t\tif idx > math.MaxInt {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"array index out of range\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn int(idx), nil\n")
	fmt.Fprintf(buf, "\tcase *runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tif v == nil || v.Val == nil || v.Val.Sign() < 0 {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"array index must be an integer\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif !v.Val.IsInt64() {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"array index out of range\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tidx := v.Val.Int64()\n")
	fmt.Fprintf(buf, "\t\tif idx > math.MaxInt {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"array index out of range\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn int(idx), nil\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn 0, fmt.Errorf(\"array index must be an integer\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "type __able_value_error struct {\n")
	fmt.Fprintf(buf, "\tvalue runtime.Value\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func (e __able_value_error) Error() string {\n")
	fmt.Fprintf(buf, "\treturn \"runtime error\"\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_call(args []runtime.Value, node ast.Node, fn func([]runtime.Value) (runtime.Value, error)) runtime.Value {\n")
	fmt.Fprintf(buf, "\tif fn == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := fn(args)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\tswitch v := err.(type) {\n")
	fmt.Fprintf(buf, "\t\tcase __able_value_error:\n")
	fmt.Fprintf(buf, "\t\t\tbridge.RaiseWithContext(__able_runtime, node, v.value)\n")
	fmt.Fprintf(buf, "\t\tcase *__able_value_error:\n")
	fmt.Fprintf(buf, "\t\t\tif v != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\tbridge.RaiseWithContext(__able_runtime, node, v.value)\n")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\tdefault:\n")
	fmt.Fprintf(buf, "\t\t\tbridge.RaiseRuntimeErrorWithContext(__able_runtime, node, err)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_new_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_array_new expects no arguments\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle := runtime.ArrayStoreNew()\n")
	fmt.Fprintf(buf, "\treturn bridge.ToInt(handle, runtime.IntegerI64), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_with_capacity_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_array_with_capacity expects capacity argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcapacity, err := __able_array_index_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"capacity must be a non-negative integer\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle := runtime.ArrayStoreNewWithCapacity(capacity)\n")
	fmt.Fprintf(buf, "\treturn bridge.ToInt(handle, runtime.IntegerI64), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_size_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_array_size expects handle\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_array_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tsize, err := runtime.ArrayStoreSize(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.ToUint(uint64(size), runtime.IntegerU64), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_capacity_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_array_capacity expects handle\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_array_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcapacity, err := runtime.ArrayStoreCapacity(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.ToUint(uint64(capacity), runtime.IntegerU64), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_set_len_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 2 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_array_set_len expects handle and length\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_array_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tlength, err := __able_array_index_from_value(args[1])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"length must be a non-negative integer\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif err := runtime.ArrayStoreSetLength(handle, length); err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_read_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 2 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_array_read expects handle and index\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_array_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tidx, err := __able_array_index_from_value(args[1])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tval, err := runtime.ArrayStoreRead(handle, idx)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif val == nil {\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn val, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_write_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 3 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_array_write expects handle, index, and value\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_array_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tidx, err := __able_array_index_from_value(args[1])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif err := runtime.ArrayStoreWrite(handle, idx, args[2]); err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_reserve_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 2 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_array_reserve expects handle and capacity\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_array_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcapacity, err := __able_array_index_from_value(args[1])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"capacity must be a non-negative integer\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif err := runtime.ArrayStoreReserve(handle, capacity); err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.ToInt(handle, runtime.IntegerI64), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_array_clone_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_array_clone expects handle\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_array_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tnewHandle, err := runtime.ArrayStoreClone(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.ToInt(newHandle, runtime.IntegerI64), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_array_new(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_array_new_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_array_with_capacity(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_array_with_capacity_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_array_size(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_array_size_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_array_capacity(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_array_capacity_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_array_set_len(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_array_set_len_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_array_read(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_array_read_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_array_write(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_array_write_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_array_reserve(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_array_reserve_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_array_clone(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_array_clone_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
}
