package compiler

import (
	"bytes"
	"fmt"
)

func (g *generator) renderRuntimeHashMapHelpers(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "func __able_hash_map_handle_from_value(val runtime.Value) (int64, error) {\n")
	fmt.Fprintf(buf, "\tcurrent := __able_unwrap_interface(val)\n")
	fmt.Fprintf(buf, "\tswitch v := current.(type) {\n")
	fmt.Fprintf(buf, "\tcase runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tif n, ok := v.ToInt64(); ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn n, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn 0, fmt.Errorf(\"hash map handle is out of range\")\n")
	fmt.Fprintf(buf, "\tcase *runtime.IntegerValue:\n")
	fmt.Fprintf(buf, "\t\tif v == nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn 0, fmt.Errorf(\"hash map handle must be an integer\")\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif n, ok := v.ToInt64(); ok {\n")
	fmt.Fprintf(buf, "\t\t\treturn n, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn 0, fmt.Errorf(\"hash map handle must be an integer\")\n")
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn 0, fmt.Errorf(\"hash map handle must be an integer\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_hash_map_hash(val runtime.Value) (uint64, error) {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\treturn 0, fmt.Errorf(\"compiler: missing runtime\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.HashMapHashValue(__able_runtime, val)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_hash_map_keys_equal(left runtime.Value, right runtime.Value) (bool, error) {\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\treturn false, fmt.Errorf(\"compiler: missing runtime\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.HashMapKeysEqual(__able_runtime, left, right)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_hash_map_find_entry(state *runtime.HashMapValue, hash uint64, key runtime.Value) (int, bool, error) {\n")
	fmt.Fprintf(buf, "\tif state == nil {\n")
	fmt.Fprintf(buf, "\t\treturn -1, false, fmt.Errorf(\"hash map state is nil\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tfor idx, entry := range state.Entries {\n")
	fmt.Fprintf(buf, "\t\tif entry.Hash != hash {\n")
	fmt.Fprintf(buf, "\t\t\tcontinue\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tequal, err := __able_hash_map_keys_equal(entry.Key, key)\n")
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn -1, false, err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tif equal {\n")
	fmt.Fprintf(buf, "\t\t\treturn idx, true, nil\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn -1, false, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_hash_map_new_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_hash_map_new expects no arguments\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle := runtime.HashMapStoreNew(0)\n")
	fmt.Fprintf(buf, "\treturn bridge.ToInt(handle, runtime.IntegerI64), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_hash_map_with_capacity_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_hash_map_with_capacity expects capacity argument\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcapacity, err := __able_array_index_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"capacity must be a non-negative integer\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle := runtime.HashMapStoreNewWithCapacity(capacity)\n")
	fmt.Fprintf(buf, "\treturn bridge.ToInt(handle, runtime.IntegerI64), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_hash_map_get_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 2 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_hash_map_get expects handle and key\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_hash_map_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.HashMapStoreState(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thash, err := __able_hash_map_hash(args[1])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tidx, found, err := __able_hash_map_find_entry(state, hash, args[1])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif found {\n")
	fmt.Fprintf(buf, "\t\treturn state.Entries[idx].Value, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_hash_map_set_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 3 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_hash_map_set expects handle, key, and value\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_hash_map_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.HashMapStoreState(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thash, err := __able_hash_map_hash(args[1])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tidx, found, err := __able_hash_map_find_entry(state, hash, args[1])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif found {\n")
	fmt.Fprintf(buf, "\t\tstate.Entries[idx].Hash = hash\n")
	fmt.Fprintf(buf, "\t\tstate.Entries[idx].Key = args[1]\n")
	fmt.Fprintf(buf, "\t\tstate.Entries[idx].Value = args[2]\n")
	fmt.Fprintf(buf, "\t\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.Entries = append(state.Entries, runtime.HashMapEntry{Key: args[1], Value: args[2], Hash: hash})\n")
	fmt.Fprintf(buf, "\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_hash_map_remove_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 2 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_hash_map_remove expects handle and key\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_hash_map_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.HashMapStoreState(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thash, err := __able_hash_map_hash(args[1])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tidx, found, err := __able_hash_map_find_entry(state, hash, args[1])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif found {\n")
	fmt.Fprintf(buf, "\t\tval := state.Entries[idx].Value\n")
	fmt.Fprintf(buf, "\t\tstate.Entries = append(state.Entries[:idx], state.Entries[idx+1:]...)\n")
	fmt.Fprintf(buf, "\t\treturn val, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_hash_map_contains_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 2 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_hash_map_contains expects handle and key\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_hash_map_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.HashMapStoreState(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thash, err := __able_hash_map_hash(args[1])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\t_, found, err := __able_hash_map_find_entry(state, hash, args[1])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.BoolValue{Val: found}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_hash_map_size_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_hash_map_size expects handle\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_hash_map_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.HashMapStoreState(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.ToInt(int64(len(state.Entries)), runtime.IntegerI32), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_hash_map_clear_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_hash_map_clear expects handle\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_hash_map_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.HashMapStoreState(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate.Entries = state.Entries[:0]\n")
	fmt.Fprintf(buf, "\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_hash_map_for_each_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 2 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_hash_map_for_each expects handle and callback\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif __able_runtime == nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"compiler: missing runtime\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_hash_map_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tstate, err := runtime.HashMapStoreState(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tcallback := args[1]\n")
	fmt.Fprintf(buf, "\tfor _, entry := range state.Entries {\n")
	fmt.Fprintf(buf, "\t\t_, control := __able_call_value(callback, []runtime.Value{entry.Key, entry.Value}, nil)\n")
	fmt.Fprintf(buf, "\t\tif control != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn nil, __able_control_to_error(__able_runtime, nil, control)\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn runtime.NilValue{}, nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_hash_map_clone_impl(args []runtime.Value) (runtime.Value, error) {\n")
	fmt.Fprintf(buf, "\tif len(args) != 1 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"__able_hash_map_clone expects handle\")\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\thandle, err := __able_hash_map_handle_from_value(args[0])\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tnewHandle, err := runtime.HashMapStoreClone(handle)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn bridge.ToInt(newHandle, runtime.IntegerI64), nil\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_hash_map_new(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_hash_map_new_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_hash_map_with_capacity(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_hash_map_with_capacity_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_hash_map_get(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_hash_map_get_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_hash_map_set(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_hash_map_set_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_hash_map_remove(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_hash_map_remove_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_hash_map_contains(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_hash_map_contains_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_hash_map_size(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_hash_map_size_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_hash_map_clear(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_hash_map_clear_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_hash_map_for_each(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_hash_map_for_each_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
	fmt.Fprintf(buf, "func __able_extern_hash_map_clone(args []runtime.Value, node ast.Node) runtime.Value {\n")
	fmt.Fprintf(buf, "\treturn __able_extern_call(args, node, __able_hash_map_clone_impl)\n")
	fmt.Fprintf(buf, "}\n\n")
}
